//>>built
define("dojox/charting/action2d/_IndicatorElement","dojo/_base/lang,dojo/_base/declare,../plot2d/Base,../plot2d/common,../axis2d/common,dojox/gfx".split(","),function(s,v,w,q,x,t){var y=function(b){var a=b.declaredClass,f;if(-1!=a.indexOf("svg"))try{return s.mixin({},b.rawNode.getBBox())}catch(c){}else{if(-1!=a.indexOf("vml")){var d=b.rawNode,h=d.style.display;d.style.display="inline";a=t.pt2px(parseFloat(d.currentStyle.width));f=t.pt2px(parseFloat(d.currentStyle.height));a={x:0,y:0,width:a,height:f};
u(b,a);d.style.display=h;return a}if(-1!=a.indexOf("silverlight"))return u(b,{width:b.rawNode.actualWidth,height:b.rawNode.actualHeight},0.75);if(b.getTextWidth)return a=b.getTextWidth(),d=b.getFont(),f=t.normalizedLength(d?d.size:t.defaultFont.size),a={width:a,height:f},u(b,a,0.75),a}return null},u=function(b,a,f){var c=a.width,d=a.height,b=b.getShape();switch(b.align){case "end":a.x=b.x-c;break;case "middle":a.x=b.x-c/2;break;default:a.x=b.x}a.y=b.y-d*(f||1);return a};return v(w,{constructor:function(b,
a){a||(a={});this.inter=a.inter},_updateVisibility:function(b,a,f){var c="x"==f?this.inter.plot._hAxis:this.inter.plot._vAxis,d=c.getWindowScale();this.chart.setAxisWindow(c.name,d,c.getWindowOffset()+(b[f]-a[f])/d);this._noDirty=!0;this.chart.render();this._noDirty=!1;this._tracker||this.initTrack()},_trackMove:function(){this._updateIndicator(this.pageCoord);if(this._initTrackPhase)this._initTrackPhase=!1,this._tracker=setInterval(s.hitch(this,this._trackMove),100)},initTrack:function(){this._initTrackPhase=
!0;this._tracker=setTimeout(s.hitch(this,this._trackMove),500)},stopTrack:function(){if(this._tracker)this._initTrackPhase?clearTimeout(this._tracker):clearInterval(this._tracker),this._tracker=null},render:function(){this.isDirty()&&(this.cleanGroup(),this.pageCoord&&this._updateIndicator(this.pageCoord,this.secondCoord))},_updateIndicator:function(b,a){var f=this.inter,c=f.plot,d=f.opt.vertical,h=this.chart.getAxis(c.hAxis),g=this.chart.getAxis(c.vAxis),i=h.name,e=g.name,k=h.getScaler().bounds,
m=g.getScaler().bounds,g=d?"x":"y",h=d?i:e,n=d?k:m;if(a){var j;d?b.x>a.x&&(j=a,a=b,b=j):b.y>a.y&&(j=a,a=b,b=j)}var l=c.toData(b),o;a&&(o=c.toData(a));var p={};p[i]=k.from;p[e]=m.from;j=c.toPage(p);p[i]=k.to;p[e]=m.to;m=c.toPage(p);if(l[h]<n.from){if(!o&&f.opt.autoScroll){this._updateVisibility(b,j,g);return}b[g]=j[g];l=c.toData(b)}else if(l[h]>n.to){if(!o&&f.opt.autoScroll){this._updateVisibility(b,m,g);return}b[g]=m[g];l=c.toData(b)}var k=this._getData(l,g,d),r;null!=k.y&&(a&&(o[h]<n.from?(a[g]=
j[g],o=c.toData(a)):o[h]>n.to&&(a[g]=m[g],o=c.toData(a)),r=this._getData(o,g,d),null==r.y&&(a=null)),c=this._renderIndicator(k,a?1:0,i,e,j,m),a&&(i=this._renderIndicator(r,2,i,e,j,m),e=d?r.y-k.y:r.x-k.y,this._renderText(f.opt.labelFunc?f.opt.labelFunc(k,r,f.opt.fixed,f.opt.precision):q.getLabel(e,f.opt.fixed,f.opt.precision)+" ("+q.getLabel(100*e/(d?k.y:k.x),!0,2)+"%)",f,this.chart.theme,d?(c.x+i.x)/2:c.x,d?c.y:(c.y+i.y)/2,k,r)))},_renderIndicator:function(b,a,f,c,d,h){var g=this.chart.theme,i=this.chart.getCoords(),
e=this.inter,k=e.plot,m=e.opt.vertical,n={};n[f]=b.x;n[c]=b.y;var n=k.toPage(n),f=n.x-i.x,k=n.y-i.y,n=m?f:d.x-i.x,d=m?d.y-i.y:k,c=m?n:h.x-i.x,h=m?h.y-i.y:d,j=e.opt.lineShadow?e.opt.lineShadow:g.indicator.lineShadow,i=e.opt.lineStroke?e.opt.lineStroke:g.indicator.lineStroke,l=e.opt.lineOutline?e.opt.lineOutline:g.indicator.lineOutline;j&&this.group.createLine({x1:n+j.dx,y1:d+j.dy,x2:c+j.dx,y2:h+j.dy}).setStroke(j);if(l)l=q.makeStroke(l),l.width=2*l.width+i.width,this.group.createLine({x1:n,y1:d,x2:c,
y2:h}).setStroke(l);this.group.createLine({x1:n,y1:d,x2:c,y2:h}).setStroke(i);var o=e.opt.markerSymbol?e.opt.markerSymbol:g.indicator.markerSymbol,p="M"+f+" "+k+" "+o,j=e.opt.markerShadow?e.opt.markerShadow:g.indicator.markerShadow,i=e.opt.markerStroke?e.opt.markerStroke:g.indicator.markerStroke,l=e.opt.markerOutline?e.opt.markerOutline:g.indicator.markerOutline;j&&this.group.createPath("M"+(f+j.dx)+" "+(k+j.dy)+" "+o).setFill(j.color).setStroke(j);if(l)l=q.makeStroke(l),l.width=2*l.width+i.width,
this.group.createPath(p).setStroke(l);f=this.group.createPath(p);k=this._shapeFill(e.opt.markerFill?e.opt.markerFill:g.indicator.markerFill,f.getBoundingBox());f.setFill(k).setStroke(i);0==a&&this._renderText(e.opt.labelFunc?e.opt.labelFunc(b,null,e.opt.fixed,e.opt.precision):q.getLabel(m?b.y:b.x,e.opt.fixed,e.opt.precision),e,g,m?n:c+5,m?h+5:d,b);return m?{x:n,y:h+5}:{x:c+5,y:d}},_renderText:function(b,a,f,c,d,h,g){b=x.createText.gfx(this.chart,this.group,c,d,"middle",b,a.opt.font?a.opt.font:f.indicator.font,
a.opt.fontColor?a.opt.fontColor:f.indicator.fontColor);c=y(b,b.getShape().text);c.x-=2;c.y-=1;c.width+=4;c.height+=2;c.r=a.opt.radius?a.opt.radius:f.indicator.radius;var i=a.opt.shadow?a.opt.shadow:f.indicator.shadow,d=a.opt.stroke?a.opt.stroke:f.indicator.stroke,e=a.opt.outline?a.opt.outline:f.indicator.outline;i&&this.group.createRect(c).setFill(i.color).setStroke(i);if(e)e=q.makeStroke(e),e.width=2*e.width+d.width,this.group.createRect(c).setStroke(e);a=a.opt.fillFunc?a.opt.fillFunc(h,g):a.opt.fill?
a.opt.fill:f.indicator.fill;this.group.createRect(c).setFill(this._shapeFill(a,c)).setStroke(d);b.moveToFront()},_getData:function(b,a,f){var c=this.chart.getSeries(this.inter.opt.series).data,d,h,g=c.length;for(d=0;d<g;++d)if(h=c[d],null!=h)if("number"==typeof h){if(d+1>b[a])break}else if(h[a]>b[a])break;var i,e;if("number"==typeof h)g=d+1,0<d&&(i=d,e=c[d-1]);else if(g=h.x,h=h.y,0<d)i=c[d-1].x,e=c[d-1].y;if(0<d&&b[a]<=(f?(g+i)/2:(h+e)/2))g=i,h=e;return{x:g,y:h}},cleanGroup:function(b){this.inherited(arguments);
this.group.moveToFront();return this},getSeriesStats:function(){return s.delegate(q.defaultStats)},isDirty:function(){return!this._noDirty&&(this.dirty||this.inter.plot.isDirty())}})});