define({
//Body
	loadingInfo: "Cargando...",
	emptyInfo: "No hay elementos para mostrar",
	loadFailInfo: "No se han podido cargar los datos.",
	loadMore: "Cargar más",
	loadMoreLoading: "Cargando...",
	loadPrevious: "Cargar anterior",
	loadPreviousLoading: "Cargando...",

//FilterBar
	"clearFilterDialogTitle": "Borrar filtro",
	"filterDefDialogTitle": "Filtrar",
	"defaultRuleTitle": "Regla",
	"ruleTitleTemplate": "Regla ${ruleNumber}",
	"noFilterApplied": "No se aplica ningún filtro.",
	"defineFilter": "Definir filtro",
	"conditionEqual": "es igual a",
	"conditionNotEqual": "no es igual a",
	"conditionLess": "es menor que",
	"conditionLessEqual": "es menor o igual que",
	"conditionGreater": "es mayor que",
	"conditionGreaterEqual": "es mayor o igual que",
	"conditionContain": "contiene",
	"conditionIs": "es",
	"conditionStartWith": "empieza por",
	"conditionEndWith": "termina por",
	"conditionNotContain": "no contiene",
	"conditionIsNot": "no es",
	"conditionNotStartWith": "no empieza por",
	"conditionNotEndWith": "no termina por",
	"conditionBefore": "antes",
	"conditionAfter": "después",
	"conditionRange": "rango",
	"conditionIsEmpty": "está vacío",
	"all": "todas",
	"any": "cualquiera",
	"relationAll": "todas las reglas",
	"waiRelAll": "Coincide con todas las reglas siguientes:",
	"relationAny": "cualquier regla",
	"waiRelAny": "Coincide con cualquiera de las reglas siguientes:",
	"relationMsgFront": "Coincide",
	"relationMsgTail": "",
	"and": "y",
	"or": "o",
	"addRuleButton": "Añadir regla",
	"waiAddRuleButton": "Añadir una regla nueva",
	"removeRuleButton": "Eliminar regla",
	"waiRemoveRuleButtonTemplate": "Eliminar la regla ${0}",
	"addRuleButton": "Añadir regla de filtro",
	"cancelButton": "Cancelar",
	"waiCancelButton": "Cancelar este diálogo",
	"clearButton": "Borrar",
	"waiClearButton": "Borrar el filtro",
	"filterButton": "Filtrar",
	"waiFilterButton": "Enviar el filtro",
	"columnSelectLabel": "Columna",
	"waiColumnSelectTemplate": "Columna para la regla ${0}",
	"conditionSelectLabel": "Condición",
	"waiConditionSelectTemplate": "Condición para la regla ${0}",
	"valueBoxLabel": "Valor",
	"waiValueBoxTemplate": "Escriba el valor que se debe filtrar para la regla ${0}",
	"rangeTo": "a",
	"rangeTemplate": "de ${0} a ${1}",
	"statusTipHeaderColumn": "Columna",
	"statusTipHeaderCondition": "Reglas",
	"statusTipTitle": "Barra de filtros",
	"statusTipMsg": "Pulse la barra de filtros para filtrar los valores de ${0}.",
	"anycolumn": "cualquier columna",
	"statusTipTitleNoFilter": "Barra de filtros",
	"statusTipTitleHasFilter": "Filtrar",
	"statusTipRelPre": "Coincide",
	"statusTipRelPost": "reglas.",
	"statusTipHeaderAll": "Coincidir con todas las reglas.",
	"statusTipHeaderAny": "Coincidir con cualquier regla.",
	"defaultItemsName": "elementos",
	"filterBarMsgHasFilterTemplate": "Se muestran ${0} de ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "No se aplica ningún filtro",
	"filterBarDefButton": "Definir filtro",
	"waiFilterBarDefButton": "Filtrar la tabla",
	"a11yFilterBarDefButton": "Filtrar...",
	"filterBarClearButton": "Borrar filtro",
	"waiFilterBarClearButton": "Borrar el filtro",
	"closeFilterBarBtn": "Cerrar la barra de filtros",
	"clearFilterMsg": "Esto eliminará el filtro y mostrará todos los registros disponibles.",
	"anyColumnOption": "Cualquier columna",
	"trueLabel": "Verdadero",
	"falseLabel": "Falso",
	"radioTrueLabel": "Valor verdadero",
	"radioFalseLabel": "Valor falso",
	"beginTimeRangeLabel": "Valor de inicio de rango de tiempo",
	"endTimeRangeLabel": "Valor de finalización de rango de tiempo",
	"beginDateRangeLabel": "Valor de inicio de rango de fechas",
	"endDateRangeLabel": "Valor de finalización de rango de fechas",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Orden único",
	nestedSort: "Orden anidado",
	ascending: "Pulse para ordenar de forma ascendente",
	descending: "Pulse para ordenar de forma descendente",
	sortingState: "${0} - ${1}",
	unsorted: "No ordenar esta columna",
	waiSingleSortLabel: "${0} - se ordena por ${1}. Elija ordenar por ${2}",
	waiNestedSortLabel:"${0} - se ordena de forma anidada por ${1}. Elija ordenar de forma anidada por ${2}",

//PaginationBar
	pagerWai: 'Buscapersonas',
	pageIndex: '${0}',
	pageIndexTitle: 'Página ${0}',
	firstPageTitle: 'Primera página',
	prevPageTitle: 'Página anterior',
	nextPageTitle: 'Página siguiente',
	lastPageTitle: 'Última página',
	pageSize: '${0}',
	pageSizeTitle: '${0} elementos por página',
	pageSizeAll: 'Todos',
	pageSizeAllTitle: 'Todos los elementos',
	description: '${0} - ${1} de ${2} elementos.',
	descriptionEmpty: 'La cuadrícula está vacía.',
	// OneUI blueprint
	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Seleccionados: ${1}',
	gotoBtnTitle: 'Ir a una página específica',
	gotoDialogTitle: 'Ir a la página',
	gotoDialogMainMsg: 'Especifique el número de página:',
	gotoDialogPageCount: ' (${0} páginas)',
	gotoDialogOKBtn: 'Ir',
	gotoDialogCancelBtn: 'Cancelar',
	// for drop down pagination bar
	pageLabel: 'Página',
	pageSizeLabel: 'Filas',

//QuickFilter
	filterLabel: 'Filtrar',
	clearButtonTitle: 'Borrar filtro',
	buildFilterMenuLabel: 'Crear filtro&hellip;',
	apply: 'Aplicar filtro',

//SummaryBar
	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Seleccionados: ${1}'
});
