define(
({
	"clearFilterDialogTitle": "Brisanje filtera",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Nijedan filter nije primijenjen",
	"defineFilter": "Definisanje filtera",
	"conditionEqual": "jednako",
	"conditionNotEqual": "nije jednako",
	"conditionLess": "manje je od",
	"conditionLessEqual": "manje od ili jednako",
	"conditionGreater": "veće je od",
	"conditionGreaterEqual": "veće od ili jednako",
	"conditionContain": "sadrži",
	"conditionIs": "je",
	"conditionStartWith": "počinje sa",
	"conditionEndWith": "završava sa",
	"conditionNotContain": "ne sadrži",
	"conditionIsNot": "nije",
	"conditionNotStartWith": "ne počinje sa",
	"conditionNotEndWith": "ne završava sa",
	"conditionBefore": "prije",
	"conditionAfter": "nakon",
	"conditionRange": "interval",
	"conditionIsEmpty": "je prazno",
	"all": "svi",
	"any": "bilo koji",
	"relationAll": "sva pravila",
	"waiRelAll": "Spari sve sljedeća pravila:",
	"relationAny": "bilo koje pravilo",
	"waiRelAny": "Spari bilo koje od sljedećih pravila:",
	"relationMsgFront": "Spari",
	"relationMsgTail": "",
	"and": "i",
	"or": "ili",
	"addRuleButton": "Dodaj pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Ukloni pravilo",
	"waiRemoveRuleButtonTemplate": "Ukloni pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtera",
	"cancelButton": "Odustani",
	"waiCancelButton": "Odustani od ovog prijedloga",
	"clearButton": "Briši",
	"waiClearButton": "Briši filter",
	"filterButton": "Filter",
	"waiFilterButton": "Submitiraj filter",
	"columnSelectLabel": "Kolona:",
	"waiColumnSelectTemplate": "Kolona za pravilo ${0}",
	"conditionSelectLabel": "Uslov:",
	"waiConditionSelectTemplate": "Uslov za pravilo ${0}",
	"valueBoxLabel": "Vrijednost:",
	"waiValueBoxTemplate": "Unos vrijednosti u filter za  pravilo ${0}",
	"rangeTo": "u",
	"rangeTemplate": "iz ${0} u ${1}",
	"statusTipHeaderColumn": "Kolona",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Traka filtera",
	"statusTipMsg": "Kliknite ovdje traku za filtriranje po vrijednostima u ${0}.",
	"anycolumn": "bilo koja kolona",
	"statusTipTitleNoFilter": "Traka filtera",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Spari",
	"statusTipRelPost": "pravila.",
	"statusTipHeaderAll": "Spari sva pravila",
	"statusTipHeaderAny": "Spari bilo koja pravila.",
	"defaultItemsName": "stavke",
	"filterBarMsgHasFilterTemplate": "${0} od ${1} ${2} je prikazano.",
	"filterBarMsgNoFilterTemplate": "Nijedan filter nije primijenjen",
	"filterBarDefButton": "Definiši filter",
	"waiFilterBarDefButton": "Filtriraj tabelu",
	"a11yFilterBarDefButton": "Filtriranje...",
	"filterBarClearButton": "Briši filter",
	"waiFilterBarClearButton": "Briši filter",
	"closeFilterBarBtn": "Zatvori traku filtera",
	"clearFilterMsg": "To će ukloniti filter i pokazati sve raspoložive slogove.",
	"anyColumnOption": "Bilo koju kolonu",
	"trueLabel": "Tačno",
	"falseLabel": "Netačno",
	"radioTrueLabel": "Vrijednost tačno",
	"radioFalseLabel": "Vrijednost netačno",
	"beginTimeRangeLabel": "Početak vrijednosti intervala vremena",
	"endTimeRangeLabel": "Kraj vrijednosti intervala vremena",
	"beginDateRangeLabel": "Početak vrijednosti intervala datuma",
	"endDateRangeLabel": "Kraj vrijednosti intervala datuma",
	"startsWithExpr": "${0}*"
})
);

