define(
({
	"clearFilterDialogTitle": "Tyhjennä suodatin",
	"filterDefDialogTitle": "Suodata",
	"defaultRuleTitle": "Sääntö",
	"ruleTitleTemplate": "Sääntö ${ruleNumber}",
	"noFilterApplied": "Suodatinta ei ole käytössä.",
	"defineFilter": "Määritä suodatin",
	"conditionEqual": "on yhtä suuri kuin",
	"conditionNotEqual": "ei ole yhtä suuri kuin",
	"conditionLess": "on pienempi kuin",
	"conditionLessEqual": "on pienempi tai yhtä suuri kuin",
	"conditionGreater": "on suurempi kuin",
	"conditionGreaterEqual": "on suurempi tai yhtä suuri kuin",
	"conditionContain": "sisältää",
	"conditionIs": "on",
	"conditionStartWith": "alkaa merkeillä",
	"conditionEndWith": "loppuu merkkeihin",
	"conditionNotContain": "ei sisällä",
	"conditionIsNot": "ei ole",
	"conditionNotStartWith": "ei ala merkeillä",
	"conditionNotEndWith": "ei lopu merkkihin",
	"conditionBefore": "ennen",
	"conditionAfter": "jälkeen",
	"conditionRange": "vaihtelualue",
	"conditionIsEmpty": "on tyhjä",
	"all": "kaikki",
	"any": "mikä tahansa",
	"relationAll": "kaikki säännöt",
	"waiRelAll": "Vastaa kaikkia seuraavia sääntöjä:",
	"relationAny": "mitkä tahansa säännöt",
	"waiRelAny": "Vastaa jotakin seuraavista säännöistä:",
	"relationMsgFront": "Vastaa",
	"relationMsgTail": "",
	"and": "ja",
	"or": "tai",
	"addRuleButton": "Lisää sääntö",
	"waiAddRuleButton": "Lisää uusi sääntö",
	"removeRuleButton": "Poista sääntö",
	"waiRemoveRuleButtonTemplate": "Poista sääntö ${0}",
	"addRuleButton": "Lisää suodatussääntö",
	"cancelButton": "Peruuta",
	"waiCancelButton": "Peruuta tämä valintaikkuna",
	"clearButton": "Tyhjennä",
	"waiClearButton": "Tyhjennä suodatin",
	"filterButton": "Suodata",
	"waiFilterButton": "Lähetä suodatin",
	"columnSelectLabel": "Sarake",
	"waiColumnSelectTemplate": "Sarake säännölle ${0}",
	"conditionSelectLabel": "Ehto",
	"waiConditionSelectTemplate": "Ehto säännölle ${0}",
	"valueBoxLabel": "Arvo",
	"waiValueBoxTemplate": "Anna suodatusarvo säännölle ${0}",
	"rangeTo": "-",
	"rangeTemplate": "${0} - ${1}",
	"statusTipHeaderColumn": "Sarake",
	"statusTipHeaderCondition": "Säännöt",
	"statusTipTitle": "Suodatinpalkki",
	"statusTipMsg": "Napsauta suodatinpalkkia tässä ja suodata arvot kohteessa ${0}.",
	"anycolumn": "mikä tahansa sarake",
	"statusTipTitleNoFilter": "Suodatinpalkki",
	"statusTipTitleHasFilter": "Suodata",
	"statusTipRelPre": "Vastaa",
	"statusTipRelPost": "sääntöä.",
	"statusTipHeaderAll": "Vastaa kaikkia sääntöjä.",
	"statusTipHeaderAny": "Vastaa jotakin sääntöä.",
	"defaultItemsName": "kohdetta",
	"filterBarMsgHasFilterTemplate": "${0} / ${1} ${2} näkyy.",
	"filterBarMsgNoFilterTemplate": "Suodatinta ei ole käytössä",
	"filterBarDefButton": "Määritä suodatin",
	"waiFilterBarDefButton": "Suodata taulukko",
	"a11yFilterBarDefButton": "Suodata...",
	"filterBarClearButton": "Tyhjennä suodatin",
	"waiFilterBarClearButton": "Tyhjennä suodatin",
	"closeFilterBarBtn": "Sulje suodatinpalkki",
	"clearFilterMsg": "Tämä poistaa suodattimen ja näyttää kaikki käytettävissä olevat tietueet.",
	"anyColumnOption": "Mikä tahansa sarake",
	"trueLabel": "Tosi",
	"falseLabel": "Epätosi",
	"radioTrueLabel": "Arvo tosi",
	"radioFalseLabel": "Arvo epätosi",
	"beginTimeRangeLabel": "Aikavälin alkuarvo",
	"endTimeRangeLabel": "Aikavälin loppuarvo",
	"beginDateRangeLabel": "Päivämäärävälin alkuarvo",
	"endDateRangeLabel": "Päivämäärävälin loppuarvo",
	"startsWithExpr": "${0}*"
})
);

