//>>built
define("dojox/html/ext-dojo/style","dojo/_base/kernel,dojo/dom-style,dojo/_base/lang,dojo/_base/html,dojo/_base/sniff,dojo/_base/window,dojo/dom,dojo/dom-construct,dojo/dom-style,dojo/dom-attr".split(","),function(K,M,z,u,D,I,E,J,x,L){K.experimental("dojox.html.ext-dojo.style");z.getObject("dojox.html.ext-dojo.style",!0);var F=z.getObject("dojox.html");z.mixin(F["ext-dojo"].style,{supportsTransform:!0,_toPx:function(l){var m=u.style,j=this._conversion;if("number"===typeof l)return l+"px";if(-1!=l.toLowerCase().indexOf("px"))return l;
!j.parentNode&&J.place(j,I.body());m(j,"margin",l);return m(j,"margin")},init:function(){var l=I.doc.documentElement.style,m=F["ext-dojo"].style,j=x.get,b=x.set;x.get=function(b,c){var f="transformOrigin"==c;return"transform"==c?m.getTransform(b):f?m.getTransformOrigin(b):2==arguments.length?j(b,c):j(b)};x.set=function(c,f,j){var l="transform"==f,u="transformOrigin"==f,v=E.byId(c);return l?m.setTransform(v,j,!0):u?m.setTransformOrigin(v,j):3==arguments.length?b(v,f,j):b(v,f)};for(var f=0,c=["WebkitT",
"MozT","OT","msT","t"];f<c.length;f++){if("undefined"!==typeof l[c[f]+"ransform"])this.tPropertyName=c[f]+"ransform";if("undefined"!==typeof l[c[f]+"ransformOrigin"])this.toPropertyName=c[f]+"ransformOrigin"}if(this.tPropertyName)this.setTransform=function(b,c){return x.set(b,this.tPropertyName,c)},this.getTransform=function(b){return x.get(b,this.tPropertyName)};else if(D("ie"))this.setTransform=this._setTransformFilter,this.getTransform=this._getTransformFilter;this.toPropertyName?(this.setTransformOrigin=
function(c,f){return b(c,this.toPropertyName,f)},this.getTransformOrigin=function(b){return j(b,this.toPropertyName)}):D("ie")?(this.setTransformOrigin=this._setTransformOriginFilter,this.getTransformOrigin=this._getTransformOriginFilter):this.supportsTransform=!1;this._conversion=J.create("div",{style:{position:"absolute",top:"-100px",left:"-100px",fontSize:0,width:"0",backgroundPosition:"50% 50%"}})},_notSupported:function(){console.warn("Sorry, this browser doesn't support transform and transform-origin")},
_setTransformOriginFilter:function(l,m){for(var j=z.trim(m).replace(" top"," 0").replace("left ","0 ").replace(" center","50%").replace("center ","50% ").replace(" bottom"," 100%").replace("right ","100% ").replace(/\s+/," ").split(" "),b=E.byId(l),f=this.getTransform(b),c=!0,h=0;h<j.length;h++)c=c&&/^0|(\d+(%|px|pt|in|pc|mm|cm))$/.test(j[h]),-1==j[h].indexOf("%")&&(j[h]=this._toPx(j[h]));if(!c||!j.length||2<j.length)return m;u.attr(b,"dojo-transform-origin",j.join(" "));f&&this.setTransform(l,f);
return m},_getTransformOriginFilter:function(l){return u.attr(l,"dojo-transform-origin")||"50% 50%"},_setTransformFilter:function(l,m){var j=m.replace(/\s/g,""),b=E.byId(l),f=j.split(")"),c=1,h=1,j=L.has,q=u.attr,o=Math.PI,x=Math.cos,z=Math.sin,v=Math.tan,n=Math.max,r=Math.min,A=Math.abs,B=o/180,C=o/200,d="",d="",d=[],s=0,y=0,w=0,G=0,p=0,k=0,c=0,c=1,g=h=0,e=1,t=0,i=0,a=[c,h,g,e,t,i],y=!1,o=u.style,H="absolute"==o(b,"position")?"absolute":"relative",p=o(b,"width")+o(b,"paddingLeft")+o(b,"paddingRight"),
s=o(b,"height")+o(b,"paddingTop")+o(b,"paddingBottom"),w=this._toPx;!j(b,"dojo-transform-origin")&&this.setTransformOrigin(b,"50% 50%");k=0;for(G=f.length;k<G;k++){d=(d=f[k].match(/matrix|rotate|scaleX|scaleY|scale|skewX|skewY|skew|translateX|translateY|translate/))?d[0]:"";switch(d){case "matrix":d=f[k].replace(/matrix\(|\)/g,"");i=d.split(",");c=a[0]*i[0]+a[1]*i[2];h=a[0]*i[1]+a[1]*i[3];g=a[2]*i[0]+a[3]*i[2];e=a[2]*i[1]+a[3]*i[3];t=a[4]+i[4];i=a[5]+i[5];break;case "rotate":d=f[k].replace(/rotate\(|\)/g,
"");c=-1!=d.indexOf("deg")?B:-1!=d.indexOf("grad")?C:1;c*=parseFloat(d);e=z(c);d=x(c);c=a[0]*d+a[1]*e;h=-a[0]*e+a[1]*d;g=a[2]*d+a[3]*e;e=-a[2]*e+a[3]*d;break;case "skewX":d=f[k].replace(/skewX\(|\)/g,"");c=-1!=d.indexOf("deg")?B:-1!=d.indexOf("grad")?C:1;e=v(parseFloat(d)*c);c=a[0];h=a[0]*e+a[1];g=a[2];e=a[2]*e+a[3];break;case "skewY":d=f[k].replace(/skewY\(|\)/g,"");c=-1!=d.indexOf("deg")?B:-1!=d.indexOf("grad")?C:1;e=v(parseFloat(d)*c);c=a[0]+a[1]*e;h=a[1];g=a[2]+a[3]*e;e=a[3];break;case "skew":d=
f[k].replace(/skew\(|\)/g,"");g=d.split(",");g[1]=g[1]||"0";c=-1!=g[0].indexOf("deg")?B:-1!=g[0].indexOf("grad")?C:1;h=-1!=g[1].indexOf("deg")?B:-1!=g[1].indexOf("grad")?C:1;e=v(parseFloat(g[0])*c);g=v(parseFloat(g[1])*h);c=a[0]+a[1]*g;h=a[0]*e+a[1];g=a[2]+a[3]*g;e=a[2]*e+a[3];break;case "scaleX":d=parseFloat(f[k].replace(/scaleX\(|\)/g,""))||1;c=a[0]*d;h=a[1];g=a[2]*d;e=a[3];break;case "scaleY":d=parseFloat(f[k].replace(/scaleY\(|\)/g,""))||1;c=a[0];h=a[1]*d;g=a[2];e=a[3]*d;break;case "scale":d=
f[k].replace(/scale\(|\)/g,"");e=d.split(",");e[1]=e[1]||e[0];c=a[0]*e[0];h=a[1]*e[1];g=a[2]*e[0];e=a[3]*e[1];break;case "translateX":d=parseInt(f[k].replace(/translateX\(|\)/g,""))||1;c=a[0];h=a[1];g=a[2];e=a[3];(t=w(d))&&q(b,"dojo-transform-matrix-tx",t);break;case "translateY":d=parseInt(f[k].replace(/translateY\(|\)/g,""))||1;c=a[0];h=a[1];g=a[2];e=a[3];(i=w(d))&&q(b,"dojo-transform-matrix-ty",i);break;case "translate":d=f[k].replace(/translate\(|\)/g,""),c=a[0],h=a[1],g=a[2],e=a[3],i=d.split(","),
i[0]=parseInt(w(i[0]))||0,i[1]=parseInt(w(i[1]))||0,t=i[0],i=i[1],t&&q(b,"dojo-transform-matrix-tx",t),i&&q(b,"dojo-transform-matrix-ty",i)}a=[c,h,g,e,t,i]}f=r(p*c+s*h,r(r(p*c,s*h),0));r=r(p*g+s*e,r(r(p*g,s*e),0));w=-f;G=-r;if(8>D("ie"))b.style.zoom="1","absolute"!=H&&(r=o(l.parentNode,"width"),f=A(p*c),A=A(s*h),n=n(f+A,n(n(A,f),0)),w-=(n-p)/2-(r>n?0:(n-r)/2));else if(8==D("ie"))"auto"==o(b,"zIndex")&&(b.style.zIndex="0");try{y=!!b.filters.item("DXImageTransform.Microsoft.Matrix")}catch(F){y=!1}y?
(b.filters.item("DXImageTransform.Microsoft.Matrix").M11=c,b.filters.item("DXImageTransform.Microsoft.Matrix").M12=h,b.filters.item("DXImageTransform.Microsoft.Matrix").M21=g,b.filters.item("DXImageTransform.Microsoft.Matrix").M22=e,b.filters.item("DXImageTransform.Microsoft.Matrix").filterType="bilinear",b.filters.item("DXImageTransform.Microsoft.Matrix").Dx=0,b.filters.item("DXImageTransform.Microsoft.Matrix").Dy=0,b.filters.item("DXImageTransform.Microsoft.Matrix").sizingMethod="auto expand"):
b.style.filter+=" progid:DXImageTransform.Microsoft.Matrix(M11="+c+",M12="+h+",M21="+g+",M22="+e+",FilterType='bilinear',Dx=0,Dy=0,sizingMethod='auto expand')";t=parseInt(q(b,"dojo-transform-matrix-tx")||"0");i=parseInt(q(b,"dojo-transform-matrix-ty")||"0");n=q(b,"dojo-transform-origin").split(" ");for(k=0;2>k;k++)n[k]=n[k]||"50%";p=-1!=n[0].toString().indexOf("%")?0.01*p*parseInt(n[0]):n[0];k=-1!=n[1].toString().indexOf("%")?0.01*s*parseInt(n[1]):n[1];j(b,"dojo-startX")?s=parseInt(q(b,"dojo-startX")):
(s=parseInt(o(b,"left")),q(b,"dojo-startX","absolute"==H?s:"0"));j(b,"dojo-startY")?y=parseInt(q(b,"dojo-startY")):(y=parseInt(o(b,"top")),q(b,"dojo-startY","absolute"==H?y:"0"));o(b,{position:H,left:s-parseInt(w)+parseInt(p)-((parseInt(p)-t)*c+(parseInt(k)-i)*h)+"px",top:y-parseInt(G)+parseInt(k)-((parseInt(p)-t)*g+(parseInt(k)-i)*e)+"px"});return m},_getTransformFilter:function(l){try{var m=E.byId(l).filters.item(0);return"matrix("+m.M11+", "+m.M12+", "+m.M21+", "+m.M22+", "+(u.attr(l,"dojo-transform-tx")||
"0")+", "+(u.attr(l,"dojo-transform-ty")||"0")+")"}catch(j){return"matrix(1, 0, 0, 1, 0, 0)"}},setTransform:function(){this._notSupported()},setTransformOrigin:function(){this._notSupported()}});F["ext-dojo"].style.init();return u.style});