define({
//Body
	loadingInfo: "Lataus on meneillään...",
	emptyInfo: "Näytettäviä tietoja ei ole",
	loadFailInfo: "Tietojen lataus ei onnistunut.",
	loadMore: "Lataa seuraavat",
	loadMoreLoading: "Lataus on meneillään...",
	loadPrevious: "Lataa edelliset",
	loadPreviousLoading: "Lataus on meneillään...",

//FilterBar
	"clearFilterDialogTitle": "Tyhjennä suodatin",
	"filterDefDialogTitle": "Suodatin",
	"defaultRuleTitle": "Sääntö",
	"ruleTitleTemplate": "Sääntö ${ruleNumber}",
	"noFilterApplied": "Mikään suodatin ei ole käytössä.",
	"defineFilter": "Määritä suodatin",
	"conditionEqual": "yhtä suuri kuin",
	"conditionNotEqual": "ei ole yhtä suuri kuin",
	"conditionLess": "on pienempi kuin",
	"conditionLessEqual": "pienempi tai yhtä suuri kuin",
	"conditionGreater": "on suurempi kuin",
	"conditionGreaterEqual": "suurempi tai yhtä suuri kuin",
	"conditionContain": "sisältää",
	"conditionIs": "on",
	"conditionStartWith": "alussa on",
	"conditionEndWith": "lopussa on",
	"conditionNotContain": "ei sisällä",
	"conditionIsNot": "ei ole",
	"conditionNotStartWith": "alussa ei ole",
	"conditionNotEndWith": "lopussa ei ole",
	"conditionBefore": "ennen",
	"conditionAfter": "jälkeen",
	"conditionRange": "vaihtelualue",
	"conditionIsEmpty": "on tyhjä",
	"all": "kaikki",
	"any": "mikä tahansa",
	"relationAll": "kaikki säännöt",
	"waiRelAll": "Täsmäytä kaikki seuraavat säännöt:",
	"relationAny": "mitkä tahansa säännöt",
	"waiRelAny": "Täsmäytä mitkä tahansa seuraavista säännöistä:",
	"relationMsgFront": "Vastine",
	"relationMsgTail": "",
	"and": "ja",
	"or": "tai",
	"addRuleButton": "Lisää sääntö",
	"waiAddRuleButton": "Lisää uusi sääntö",
	"removeRuleButton": "Poista sääntö",
	"waiRemoveRuleButtonTemplate": "Poista sääntö ${0}",
	"addRuleButton": "Lisää suodatussääntö",
	"cancelButton": "Peruuta",
	"waiCancelButton": "Peruuta keskustelu",
	"clearButton": "Tyhjennä",
	"waiClearButton": "Tyhjennä suodatin",
	"filterButton": "Suodata",
	"waiFilterButton": "Lähetä suodatin",
	"columnSelectLabel": "Sarake",
	"waiColumnSelectTemplate": "Säännön ${0} sarake",
	"conditionSelectLabel": "Ehto",
	"waiConditionSelectTemplate": "Säännön ${0} ehto",
	"valueBoxLabel": "Arvo",
	"waiValueBoxTemplate": "Syötä säännön ${0} suodatettava arvo",
	"rangeTo": "kohde",
	"rangeTemplate": "lähde ${0}, kohde ${1}",
	"statusTipHeaderColumn": "Sarake",
	"statusTipHeaderCondition": "Säännöt",
	"statusTipTitle": "Suodatinpalkki",
	"statusTipMsg": "Napsauta suodatinpalkkia kohteen ${0} arvojen suodattamiseksi.",
	"anycolumn": "mikä tahansa sarake",
	"statusTipTitleNoFilter": "Suodatinpalkki",
	"statusTipTitleHasFilter": "Suodatin",
	"statusTipRelPre": "Vastine",
	"statusTipRelPost": "säännöt.",
	"statusTipHeaderAll": "Täsmäytä kaikki säännöt.",
	"statusTipHeaderAny": "Täsmäytä mitkä tahansa säännöt.",
	"defaultItemsName": "nimikkeet",
	"filterBarMsgHasFilterTemplate": "näkyvissä ${0} / ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Mikään suodatin ei ole käytössä",
	"filterBarDefButton": "Määritä suodatin",
	"waiFilterBarDefButton": "Suodata taulukko",
	"a11yFilterBarDefButton": "Suodata...",
	"filterBarClearButton": "Tyhjennä suodatin",
	"waiFilterBarClearButton": "Tyhjennä suodatin",
	"closeFilterBarBtn": "Sulje suodatinpalkki",
	"clearFilterMsg": "Tämä toimenpide poistaa suodattimen ja näyttää kaikki saatavilla olevat tallenteet.",
	"anyColumnOption": "Mikä tahansa sarake",
	"trueLabel": "Tosi",
	"falseLabel": "Epätosi",
	"radioTrueLabel": "Arvo tosi",
	"radioFalseLabel": "Arvo epätosi",
	"beginTimeRangeLabel": "Aikajakson alkuarvo",
	"endTimeRangeLabel": "Aikajakson lopetusarvo",
	"beginDateRangeLabel": "Päivämäärävälin alkuarvo",
	"endDateRangeLabel": "Päivämäärävälin loppuarvo",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Yksinkertainen lajittelu",
	nestedSort: "Sisäkkäinen lajittelu",
	ascending: "Lajittele nousevaan järjestykseen napsauttamalla",
	descending: "Lajittele laskevaan järjestykseen napsauttamalla",
	sortingState: "${0} - ${1}",
	unsorted: "Älä lajittele tätä saraketta",
	waiSingleSortLabel: "${0} - järjestetty arvon ${1} mukaan. Järjestä arvon ${2} mukaan.",
	waiNestedSortLabel:"${0} - järjestetty sisäkkäin arvon ${1} mukaan. Järjestä sisäkkäin arvon ${2} mukaan.",

//PaginationBar
	pagerWai: 'Sivutustoiminto',

	pageIndex: '${0}',
	pageIndexTitle: 'Sivu ${0}',

	firstPageTitle: 'Ensimmäinen sivu',
	prevPageTitle: 'Edellinen sivu',
	nextPageTitle: 'Seuraava sivu',
	lastPageTitle: 'Viimeinen sivu',

	pageSize: '${0}',
	pageSizeTitle: '${0} nimikettä sivua kohti',
	pageSizeAll: 'Kaikki',
	pageSizeAllTitle: 'Kaikki nimikkeet',

	description: '${0} - ${1} / ${2} nimikettä.',
	descriptionEmpty: 'Ruudukko on tyhjä.',

	summary: 'Yhteensä: ${0}',
	summaryWithSelection: 'Yhteensä: ${0} Valittu: ${1}',

	gotoBtnTitle: 'Siirry tietylle sivulle',

	gotoDialogTitle: 'Siirry sivulle',
	gotoDialogMainMsg: 'Määritä sivunumero:',
	gotoDialogPageCount: ' (${0} sivua)',
	gotoDialogOKBtn: 'Siirry',
	gotoDialogCancelBtn: 'Peruuta',
	// for drop down pagination bar
	pageLabel: 'Sivu',
	pageSizeLabel: 'Rivit',

//QuickFilter
	filterLabel: 'Suodatin',
	clearButtonTitle: 'Tyhjennä suodatin',
	buildFilterMenuLabel: 'Muodosta suodatin&hellip;',
	apply: 'Käytä suodatinta',

//Sort
	helpMsg: '${0} - Lajittele napsauttamalla tai lisää lajitteluehtoihin pitämällä Ctrl-näppäintä painettuna ja napsauttamalla',
	singleHelpMsg: '${0} - Lajittele napsauttamalla',
	priorityOrder: 'lajitteluprioriteetti ${0}',

//SummaryBar
	summaryTotal: 'Yhteensä: ${0}',
	summarySelected: 'Valittu: ${0}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Press SPACE to select all.",	//need translation
	indirectDeselectAll: "Press SPACE to deselect all.",	//need translation
	treeExpanded: "Control + left arrow key to collapse this row.",	//need translation
	treeCollapsed: "Control + right arrow key to expand this row."	//need translation
});
