define({      
//begin v1.x content
	"clearFilterDialogTitle": "Cancella filtro",
	"filterDefDialogTitle": "Filtro",
	"defaultRuleTitle": "Regola",
	"ruleTitleTemplate": "Regola ${ruleNumber}",
	"noFilterApplied": "Nessun filtro applicato.",
	"defineFilter": "Definisci filtro",
	"conditionEqual": "uguale a",
	"conditionNotEqual": "non uguale a",
	"conditionLess": "minore di",
	"conditionLessEqual": "minore di o uguale a",
	"conditionGreater": "maggiore di",
	"conditionGreaterEqual": "maggiore di o uguale a",
	"conditionContain": "contiene",
	"conditionIs": "è",
	"conditionStartWith": "inizia con",
	"conditionEndWith": "finisce con",
	"conditionNotContain": "non contiene",
	"conditionIsNot": "non è",
	"conditionNotStartWith": "non inizia con",
	"conditionNotEndWith": "non finisce con",
	"conditionBefore": "prima",
	"conditionAfter": "dopo",
	"conditionRange": "intervallo",
	"conditionIsEmpty": "è vuoto",
	"all": "tutti",
	"any": "qualsiasi",
	"relationAll": "tutte le regole",
	"waiRelAll": "Confronta con tutte le seguenti regole:",
	"relationAny": "qualsiasi regola",
	"waiRelAny": "Confronta con qualsiasi delle seguenti regole:",
	"relationMsgFront": "Corrispondenza",
	"relationMsgTail": "",
	"and": "e",
	"or": "o",
	"addRuleButton": "Aggiungi regola",
	"waiAddRuleButton": "Aggiungi una nuova regola",
	"removeRuleButton": "Rimuovi regola",
	"waiRemoveRuleButtonTemplate": "Rimuovi regola ${0}",
	"addRuleButton": "Aggiungi regola filtro",
	"cancelButton": "Annulla",
	"waiCancelButton": "Annulla questa finestra di dialogo",
	"clearButton": "Cancella",
	"waiClearButton": "Cancella il filtro",
	"filterButton": "Filtro",
	"waiFilterButton": "Inoltra il filtro",
	"columnSelectLabel": "Colonna",
	"waiColumnSelectTemplate": "Colonna per la regola ${0}",
	"conditionSelectLabel": "Condizione",
	"waiConditionSelectTemplate": "Condizione per la regola ${0}",
	"valueBoxLabel": "Valore",
	"waiValueBoxTemplate": "Immettere il valore da filtrare per la regola ${0}",
	"rangeTo": "a",
	"rangeTemplate": "da ${0} a ${1}",
	"statusTipHeaderColumn": "Colonna",
	"statusTipHeaderCondition": "Regole",
	"statusTipTitle": "Barra di filtro",
	"statusTipMsg": "Fare clic sulla barra di filtro qui per filtrare sui valori in ${0}.",
	"anycolumn": "qualsiasi colonna",
	"statusTipTitleNoFilter": "Barra di filtro",
	"statusTipTitleHasFilter": "Filtro",
	"statusTipRelPre": "Corrispondenza",
	"statusTipRelPost": "regole.",
	"statusTipHeaderAll": "Corrispondenza totale delle regole.",
	"statusTipHeaderAny": "Qualsiasi corrispondenza regola.",
	"defaultItemsName": "elementi",
	"filterBarMsgHasFilterTemplate": "${0} di ${1} ${2} visualizzati.",
	"filterBarMsgNoFilterTemplate": "Nessun filtro applicato",
	"filterBarDefButton": "Definisci filtro",
	"waiFilterBarDefButton": "Filtra la tabella",
	"a11yFilterBarDefButton": "Filtro...",
	"filterBarClearButton": "Cancella filtro",
	"waiFilterBarClearButton": "Cancella il filtro",
	"closeFilterBarBtn": "Chiudi barra di filtro",
	"clearFilterMsg": "Il filtro verrà rimosso e verranno visualizzati tutti i record disponibili.",
	"anyColumnOption": "Qualsiasi colonna",
	"trueLabel": "Vero",
	"falseLabel": "Falso",
	"radioTrueLabel": "Valore Vero",
	"radioFalseLabel": "Valore Falso",
	"beginTimeRangeLabel": "Valore iniziale intervallo di tempo",
	"endTimeRangeLabel": "Valore finale intervallo di tempo",
	"beginDateRangeLabel": "Valore iniziale intervallo di date",
	"endDateRangeLabel": "Valore finale intervallo di date",
	"startsWithExpr": "${0}*"
//end v1.x content
});

