define({     
//Body
	loadingInfo: "Caricamento in corso...",
	emptyInfo: "Nessun elemento da visualizzare",
	loadFailInfo: "Impossibile caricare i dati.",
	loadMore: "Carica altro",
	loadMoreLoading: "Caricamento in corso...",
	loadPrevious: "Carica precedente",
	loadPreviousLoading: "Caricamento in corso...",

//FilterBar
	"clearFilterDialogTitle": "Cancella filtro",
	"filterDefDialogTitle": "Filtra",
	"defaultRuleTitle": "Regola",
	"ruleTitleTemplate": "Regola ${ruleNumber}",
	"noFilterApplied": "Nessun filtro applicato.",
	"defineFilter": "Definisci filtro",
	"conditionEqual": "uguale a",
	"conditionNotEqual": "diverso da",
	"conditionLess": "minore di",
	"conditionLessEqual": "minore o uguale",
	"conditionGreater": "maggiore di",
	"conditionGreaterEqual": "maggiore o uguale",
	"conditionContain": "contiene",
	"conditionIs": "è",
	"conditionStartWith": "inizia con",
	"conditionEndWith": "termina con",
	"conditionNotContain": "non contiene",
	"conditionIsNot": "non è",
	"conditionNotStartWith": "non inizia con",
	"conditionNotEndWith": "non termina con",
	"conditionBefore": "prima",
	"conditionAfter": "dopo",
	"conditionRange": "intervallo",
	"conditionIsEmpty": "è vuoto",
	"all": "tutte",
	"any": "qualsiasi",
	"relationAll": "tutte le regole",
	"waiRelAll": "Corrispondenza con tutte le regole seguenti:",
	"relationAny": "qualsiasi regola",
	"waiRelAny": "Corrispondenza una qualsiasi delle regole seguenti:",
	"relationMsgFront": "Corrispondenza",
	"relationMsgTail": "",
	"and": "e",
	"or": "o",
	"addRuleButton": "Aggiungi regola",
	"waiAddRuleButton": "Aggiungi una nuova regola",
	"removeRuleButton": "Rimuovi regola",
	"waiRemoveRuleButtonTemplate": "Rimuovi regola ${0}",
	"addRuleButton": "Aggiungi regola di filtro",
	"cancelButton": "Annulla",
	"waiCancelButton": "Annulla questa finestra di dialogo",
	"clearButton": "Cancella",
	"waiClearButton": "Annulla il filtro",
	"filterButton": "Filtra",
	"waiFilterButton": "Inoltra il filtro",
	"columnSelectLabel": "Colonna:",
	"waiColumnSelectTemplate": "Colonna per la regola ${0}",
	"conditionSelectLabel": "Condizione:",
	"waiConditionSelectTemplate": "Condizione per la regola ${0}",
	"valueBoxLabel": "Valore:",
	"waiValueBoxTemplate": "Immettere il valore da filtrare per la regola ${0}",
	"rangeTo": "a",
	"rangeTemplate": "da ${0} a ${1}",
	"statusTipHeaderColumn": "Colonna",
	"statusTipHeaderCondition": "Regole",
	"statusTipTitle": "Barra filtro",
	"statusTipMsg": "Fare clic sulla barra filtro per filtrare in base ai valori in ${0}.",
	"anycolumn": "qualsiasi colonna",
	"statusTipTitleNoFilter": "Barra filtro",
	"statusTipTitleHasFilter": "Filtra",
	"statusTipRelPre": "Corrispondenza",
	"statusTipRelPost": "regole.",
	"statusTipHeaderAll": "Corrispondenza con tutte le regole.",
	"statusTipHeaderAny": "Corrispondenza con qualsiasi regola.",
	"defaultItemsName": "elementi",
	"filterBarMsgHasFilterTemplate": "${0} di ${1} ${2} mostrate.",
	"filterBarMsgNoFilterTemplate": "Nessun filtro applicato",
	"filterBarDefButton": "Definisci filtro",
	"waiFilterBarDefButton": "Filtra la tabella",
	"a11yFilterBarDefButton": "Filtro...",
	"filterBarClearButton": "Cancella filtro",
	"waiFilterBarClearButton": "Annulla il filtro",
	"closeFilterBarBtn": "Chiudi barra filtro",
	"clearFilterMsg": "Questa operazione rimuoverà il filtro e visualizzerà tutti i record disponibili.",
	"anyColumnOption": "Qualsiasi colonna",
	"trueLabel": "Vero",
	"falseLabel": "Falso",
	"radioTrueLabel": "Valore Vero",
	"radioFalseLabel": "Valore Falso",
	"beginTimeRangeLabel": "Valore iniziale intervallo di ora",
	"endTimeRangeLabel": "Valore finale intervallo di ora",
	"beginDateRangeLabel": "Valore iniziale intervallo di data",
	"endDateRangeLabel": "Valore finale intervallo di data",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Ordinamento singolo",
	nestedSort: "Ordinamento nidificato",
	ascending: "Fare clic per ordinare in modo crescente",
	descending: "Fare clic per ordinare in modo decrescente",
	sortingState: "${0} - ${1}",
	unsorted: "Non ordinare questa colonna",
	waiSingleSortLabel: "${0} - ordinamento per ${1}. Scegliere l'ordinamento per ${2}",
	waiNestedSortLabel:"${0} - ordinamento nidificato per ${1}. Scegliere l'ordinamento nidificato per ${2}",

//PaginationBar
	pagerWai: 'Paginatore',

	pageIndex: '${0}',
	pageIndexTitle: 'Pagina ${0}',

	firstPageTitle: 'Prima pagina',
	prevPageTitle: 'Pagina precedente',
	nextPageTitle: 'Pagina successiva',
	lastPageTitle: 'Ultima pagina',

	pageSize: '${0}',
	pageSizeTitle: '${0} elementi per pagina',
	pageSizeAll: 'Tutti',
	pageSizeAllTitle: 'Tutti gli elementi',

	description: '${0} - ${1} di ${2} elementi.',
	descriptionEmpty: 'La griglia è vuota.',

	summary: 'Totale: ${0}',
	summaryWithSelection: 'Totale: ${0} Selezionati: ${1}',

	gotoBtnTitle: 'Vai a pagina specifica',

	gotoDialogTitle: 'Vai a pagina',
	gotoDialogMainMsg: 'Specificare il numero di pagina:',
	gotoDialogPageCount: '(${0} pagine)',
	gotoDialogOKBtn: 'Vai',
	gotoDialogCancelBtn: 'Annulla',
	// for drop down pagination bar
	pageLabel: 'Pagina',
	pageSizeLabel: 'Righe',

//QuickFilter
	filterLabel: 'Filtra',
	clearButtonTitle: 'Cancella filtro',
	buildFilterMenuLabel: 'Crea filtro&hellip;',
	apply: 'Applica filtro',

//Sort
	helpMsg: '${0} - Fare clic per ordinare o Ctrl-clic per aggiungere all\'ordinamento',
	singleHelpMsg: '${0} - Fare clic per ordinare',
	priorityOrder: 'priorità di ordinamento ${0}',

//SummaryBar
	summaryTotal: 'Totale: ${0}',
	summarySelected: 'Selezionati: ${0}',
	summaryRange: 'Intervallo: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Premere SPAZIO per selezionare tutto.",	//need translation
	indirectDeselectAll: "Premere SPAZIO per deselezionare tutto.",	//need translation
	treeExpanded: "Ctrl+freccia a sinistra per comprimere questa riga.",	//need translation
	treeCollapsed: "Ctrl+freccia a destra per espandere questa riga."	//need translation
});

