define({     
//Body
	loadingInfo: "正在装入...",
	emptyInfo: "没有要显示的项",
	loadFailInfo: "加载数据失败！",
	loadMore: "加载更多",
	loadMoreLoading: "正在装入...",
	loadPrevious: "加载上一页",
	loadPreviousLoading: "正在装入...",

//FilterBar
	"clearFilterDialogTitle": "清除过滤器",
	"filterDefDialogTitle": "过滤器",
	"defaultRuleTitle": "规则",
	"ruleTitleTemplate": "规则 ${ruleNumber}",
	"noFilterApplied": "未应用过滤器",
	"defineFilter": "定义过滤器",
	"conditionEqual": "等于",
	"conditionNotEqual": "不等于",
	"conditionLess": "小于",
	"conditionLessEqual": "小于或等于",
	"conditionGreater": "大于",
	"conditionGreaterEqual": "大于或等于",
	"conditionContain": "包含",
	"conditionIs": "是",
	"conditionStartWith": "开始于",
	"conditionEndWith": "结束于",
	"conditionNotContain": "不包含",
	"conditionIsNot": "不是",
	"conditionNotStartWith": "不是开始于",
	"conditionNotEndWith": "不是结束于",
	"conditionBefore": "之前",
	"conditionAfter": "之后",
	"conditionRange": "范围",
	"conditionIsEmpty": "为空",
	"all": "所有",
	"any": "任意",
	"relationAll": "所有规则",
	"waiRelAll": "符合以下所有规则：",
	"relationAny": "任何规则",
	"waiRelAny": "符合以下任意规则：",
	"relationMsgFront": "符合",
	"relationMsgTail": "",
	"and": "和",
	"or": "或",
	"addRuleButton": "添加规则",
	"waiAddRuleButton": "添加新规则",
	"removeRuleButton": "除去规则",
	"waiRemoveRuleButtonTemplate": "除去规则 ${0}",
	"addRuleButton": "添加过滤器规则",
	"cancelButton": "取消",
	"waiCancelButton": "取消此对话框",
	"clearButton": "清除",
	"waiClearButton": "清除过滤器",
	"filterButton": "过滤器",
	"waiFilterButton": "提交过滤器",
	"columnSelectLabel": "列：",
	"waiColumnSelectTemplate": "规则 ${0} 的列",
	"conditionSelectLabel": "条件：",
	"waiConditionSelectTemplate": "规则 ${0} 的条件",
	"valueBoxLabel": "值：",
	"waiValueBoxTemplate": "为 ${0} 规则向过滤器输入值",
	"rangeTo": "到",
	"rangeTemplate": "从 ${0} 到 ${1}",
	"statusTipHeaderColumn": "列",
	"statusTipHeaderCondition": "规则",
	"statusTipTitle": "过滤器栏",
	"statusTipMsg": "单击此处的过滤器栏以过滤 ${0} 中的值。",
	"anycolumn": "任意列",
	"statusTipTitleNoFilter": "过滤器栏",
	"statusTipTitleHasFilter": "过滤器",
	"statusTipRelPre": "符合",
	"statusTipRelPost": "规则。",
	"statusTipHeaderAll": "与所有规则匹配。",
	"statusTipHeaderAny": "与任何规则匹配。",
	"defaultItemsName": "项目数",
	"filterBarMsgHasFilterTemplate": "显示 ${0} 个 ${2}（共 ${1} 个）。",
	"filterBarMsgNoFilterTemplate": "未应用过滤器",
	"filterBarDefButton": "定义过滤器",
	"waiFilterBarDefButton": "过滤表",
	"a11yFilterBarDefButton": "过滤...",
	"filterBarClearButton": "清除过滤器",
	"waiFilterBarClearButton": "清除过滤器",
	"closeFilterBarBtn": "关闭过滤器栏",
	"clearFilterMsg": "此操作将除去过滤器并显示所有可用记录。",
	"anyColumnOption": "任意列",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "值 True",
	"radioFalseLabel": "值 False",
	"beginTimeRangeLabel": "时间范围值开始",
	"endTimeRangeLabel": "时间范围值结束",
	"beginDateRangeLabel": "日期范围值开始",
	"endDateRangeLabel": "日期范围值结束",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "单一排序",
	nestedSort: "嵌套排序",
	ascending: "单击以按升序排序",
	descending: "单击以按降序排序",
	sortingState: "${0} - ${1}",
	unsorted: "不要对此列排序",
	waiSingleSortLabel: "${0} - 按照 ${1} 排序。选择此选项可按照 ${2} 排序",
	waiNestedSortLabel:"${0} - 按照 ${1} 嵌套排序。选择此选项可按照 ${2} 嵌套排序",

//PaginationBar
	pagerWai: '寻呼机',

	pageIndex: '${0}',
	pageIndexTitle: '第 ${0} 页',

	firstPageTitle: '第一页',
	prevPageTitle: '上一页',
	nextPageTitle: '下一页',
	lastPageTitle: '最后一页',

	pageSize: '${0}',
	pageSizeTitle: '每页的 ${0} 项',
	pageSizeAll: '全部',
	pageSizeAllTitle: '所有项',

	description: '${0} - ${1} 项（共 ${2} 项）。',
	descriptionEmpty: '网格为空。',

	summary: '总数：${0}',
	summaryWithSelection: '总数：${0} 已选择：${1}',

	gotoBtnTitle: '转至特定页',

	gotoDialogTitle: '转至页',
	gotoDialogMainMsg: '指定页码：',
	gotoDialogPageCount: '（共 ${0} 页）',
	gotoDialogOKBtn: '运行',
	gotoDialogCancelBtn: '取消',
	// for drop down pagination bar
	pageLabel: '页面',
	pageSizeLabel: '行',

//QuickFilter
	filterLabel: '过滤器',
	clearButtonTitle: '清除过滤器',
	buildFilterMenuLabel: '构建过滤器&hellip;',
	apply: '应用过滤器',

//Sort
	helpMsg: '${0} - 单击以排序，或者使用 Control 键并单击以添加到排序',
	singleHelpMsg: '${0} - 单击以排序',
	priorityOrder: '排序优先级 ${0}',

//SummaryBar
	summaryTotal: '总数：${0}',
	summarySelected: '已选择：${0}',
	summaryRange: '范围：${0}-${1}',	//need translation

//Other
	indirectSelectAll: "按空格键以全选。",	//need translation
	indirectDeselectAll: "按空格键以取消全选。",	//need translation
	treeExpanded: "按 Control 键 + 左方向键以折叠此行。",	//need translation
	treeCollapsed: "按 Control 键 + 右方向键以展开此行。"	//need translation
});

