define({
//Body
	loadingInfo: "正在加载...",
	emptyInfo: "没有要显示的项",
	loadFailInfo: "加载数据失败！",
	loadMore: "加载更多",
	loadMoreLoading: "正在加载...",
	loadPrevious: "加载上一页",
	loadPreviousLoading: "正在加载...",

//FilterBar
	"clearFilterDialogTitle": "清除过滤器",
	"filterDefDialogTitle": "过滤器",
	"defaultRuleTitle": "规则 ",
	"ruleTitleTemplate": "规则 ${ruleNumber}",
	"noFilterApplied": "未应用任何过滤器。",
	"defineFilter": "定义过滤器",
	"conditionEqual": "等于",
	"conditionNotEqual": "不等于",
	"conditionLess": "小于",
	"conditionLessEqual": "小于或等于",
	"conditionGreater": "大于",
	"conditionGreaterEqual": "大于或等于",
	"conditionContain": "包含",
	"conditionIs": "是",
	"conditionStartWith": "开始于",
	"conditionEndWith": "结束于",
	"conditionNotContain": "不包含",
	"conditionIsNot": "非",
	"conditionNotStartWith": "不是开始于",
	"conditionNotEndWith": "不是结束于",
	"conditionBefore": "先于",
	"conditionAfter": "后于",
	"conditionRange": "范围",
	"conditionIsEmpty": "为空",
	"all": "全部",
	"any": "任何",
	"relationAll": "所有规则",
	"waiRelAll": "符合以下所有规则：",
	"relationAny": "任何规则",
	"waiRelAny": "符合以下任何规则：",
	"relationMsgFront": "匹配",
	"relationMsgTail": "",
	"and": "和",
	"or": "或",
	"addRuleButton": "添加规则",
	"waiAddRuleButton": "添加新规则",
	"removeRuleButton": "除去规则",
	"waiRemoveRuleButtonTemplate": "除去规则 ${0}",
	"addRuleButton": "添加过滤规则",
	"cancelButton": "取消",
	"waiCancelButton": "取消该对话",
	"clearButton": "清除",
	"waiClearButton": "清除过滤器",
	"filterButton": "过滤器",
	"waiFilterButton": "提交过滤器",
	"columnSelectLabel": "列",
	"waiColumnSelectTemplate": "规则 ${0} 的列",
	"conditionSelectLabel": "条件",
	"waiConditionSelectTemplate": "规则 ${0} 的条件",
	"valueBoxLabel": "值",
	"waiValueBoxTemplate": "将规则 ${0} 的值输入过滤器",
	"rangeTo": "到",
	"rangeTemplate": "从 ${0} 到 ${1}",
	"statusTipHeaderColumn": "列",
	"statusTipHeaderCondition": "规则",
	"statusTipTitle": "过滤器栏",
	"statusTipMsg": "单击此处的过滤器栏以过滤 ${0} 中的值。",
	"anycolumn": "任何列",
	"statusTipTitleNoFilter": "过滤器栏",
	"statusTipTitleHasFilter": "过滤器",
	"statusTipRelPre": "匹配",
	"statusTipRelPost": "规则。",
	"statusTipHeaderAll": "与所有规则匹配。",
	"statusTipHeaderAny": "与任何规则匹配。",
	"defaultItemsName": "项目",
	"filterBarMsgHasFilterTemplate": "显示的 ${1} ${2} 的 ${0}。",
	"filterBarMsgNoFilterTemplate": "未使用过滤器",
	"filterBarDefButton": "定义过滤器",
	"waiFilterBarDefButton": "过滤表",
	"a11yFilterBarDefButton": "过滤器...",
	"filterBarClearButton": "清除过滤器",
	"waiFilterBarClearButton": "清除过滤器",
	"closeFilterBarBtn": "关闭过滤器栏",
	"clearFilterMsg": "该操作将除去过滤器并显示所有现有记录。",
	"anyColumnOption": "任何列",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "值 True",
	"radioFalseLabel": "值 False",
	"beginTimeRangeLabel": "时间范围值起点",
	"endTimeRangeLabel": "时间范围值终点",
	"beginDateRangeLabel": "日期范围值起点",
	"endDateRangeLabel": "日期范围值终点",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "单层排序",
	nestedSort: "嵌套排序",
	ascending: "单击以按“升序”排序",
	descending: "单击以按“降序”排序",
	sortingState: "${0} - ${1}",
	unsorted: "请勿对此列进行排序",
	waiSingleSortLabel: "${0} - 已按 ${1} 排序。请选择按 ${2} 排序",
	waiNestedSortLabel:"${0} - 已按 ${1} 嵌套排序。请选择按 ${2} 嵌套排序",

//PaginationBar
	pagerWai: '调页程序',

	pageIndex: '${0}',
	pageIndexTitle: '第 ${0} 页',

	firstPageTitle: '第一页',
	prevPageTitle: '上一页',
	nextPageTitle: '下一页',
	lastPageTitle: '最后一页',

	pageSize: '${0}',
	pageSizeTitle: '每页 ${0} 项',
	pageSizeAll: '所有',
	pageSizeAllTitle: '所有项',

	description: '第 ${0} - ${2} 项（共 ${1} 项）。',
	descriptionEmpty: '网格为空。',

	summary: '总计：${0}',
	summaryWithSelection: '总计：${0} 已选择：${1}',

	gotoBtnTitle: '转到特定页面',

	gotoDialogTitle: '转到页面',
	gotoDialogMainMsg: '指定页码：',
	gotoDialogPageCount: ' （${0} 页）',
	gotoDialogOKBtn: '确定',
	gotoDialogCancelBtn: '取消',
	// for drop down pagination bar
	pageLabel: '页面',
	pageSizeLabel: '行',

//QuickFilter
	filterLabel: '过滤器',
	clearButtonTitle: '清除过滤器',
	buildFilterMenuLabel: '构建过滤器&hellip;',
	apply: '应用过滤器',

//Sort
	helpMsg: '${0} - 单击以排序，或者按 Ctrl 键并单击以添加到排序项',
	singleHelpMsg: '${0} - 单击以排序',
	priorityOrder: '排序优先级 ${0}',

//SummaryBar
	summaryTotal: '总计：${0}',
	summarySelected: '已选择：${0}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Press SPACE to select all.",	//need translation
	indirectDeselectAll: "Press SPACE to deselect all.",	//need translation
	treeExpanded: "Control + left arrow key to collapse this row.",	//need translation
	treeCollapsed: "Control + right arrow key to expand this row."	//need translation
});
