//>>built
(function(j,x){var p,ga,y=function(){},ya=function(a){for(var b in a)return 0;return 1},ha={}.toString,z=function(a){return"[object Function]"==ha.call(a)},C=function(a){return"[object String]"==ha.call(a)},ia=function(a){return"[object Array]"==ha.call(a)},o=function(a,b){if(a)for(var d=0;d<a.length;)b(a[d++])},h=function(a,b){for(var d in b)a[d]=b[d];return a},q=function(a,b){return h(Error(a),{src:"dojoLoader",info:b})},Wa=1,za=function(){return"_"+Wa++},f=function(a,b,d){return Aa(a,b,d,0,f)},
G=this,s=G.document,Xa=s&&s.createElement("DiV"),i=f.has=function(a){return z(A[a])?A[a]=A[a](G,s,Xa):A[a]},A=i.cache=x.hasCache;i.add=function(a,b,d,c){(void 0===A[a]||c)&&(A[a]=b);return d&&i(a)};for(var Ba in j.has)i.add(Ba,j.has[Ba],0,1);var k=0,D=[],ja=0,ka=y,Ca=y,Q;f.isXdUrl=y;f.initSyncLoader=function(a,b,d){ja||(ja=a,ka=b,Ca=d);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:D,modules:l,execQ:n,getModule:t,injectModule:R,setArrived:E,signal:r,finishExec:H,
execModule:I,dojoRequirePlugin:ja,getLegacyMode:function(){return k},guardCheckComplete:J}};var Ya=location.protocol,Da=location.host;f.isXdUrl=function(a){if(/^\./.test(a))return!1;return/^\/\//.test(a)?!0:(a=a.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(a[1]!=Ya||Da&&a[2]!=Da)};i.add("dojo-force-activex-xhr",!s.addEventListener&&"file:"==window.location.protocol);i.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(i("native-xhr")&&!i("dojo-force-activex-xhr"))Q=function(){return new XMLHttpRequest};
else{var Za=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],la;for(p=0;3>p;)try{if(la=Za[p++],new ActiveXObject(la))break}catch(lb){}Q=function(){return new ActiveXObject(la)}}f.getXhr=Q;i.add("dojo-gettext-api",1);f.getText=function(a,b,d){var c=Q();c.open("GET",S(a),!1);c.send(null);if(200==c.status||!location.host&&!c.status)d&&d(c.responseText,b);else throw q("xhrFailed",c.status);return c.responseText};var $a=new Function("return eval(arguments[0]);");f.eval=function(a,b){return $a(a+
"\r\n////@ sourceURL="+b)};var ma={},r=f.signal=function(a,b){var d=ma[a];o(d&&d.slice(0),function(a){a.apply(null,ia(b)?b:[b])})},ab=f.on=function(a,b){var d=ma[a]||(ma[a]=[]);d.push(b);return{remove:function(){for(var a=0;a<d.length;a++)if(d[a]===b){d.splice(a,1);break}}}},Ea=[],bb={},Fa=[],u={},Ga=f.map={},T=[],l={},na="",v={},U={},V={},W=function(a){var b,d,c,e;for(b in U)d=U[b],(c=b.match(/^url\:(.+)/))?v["url:"+Ha(c[1],a)]=d:"*now"==b?e=d:"*noref"!=b&&(c=K(b,a),v[c.mid]=v["url:"+c.url]=d);e&&
e(oa(a));U={}},Ia=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},pa=function(a,b){b.splice(0,b.length);for(var d in a)b.push([d,a[d],RegExp("^"+Ia(d)+"(/|$)"),d.length]);b.sort(function(a,b){return b[3]-a[3]});return b},Ja=function(a){var b=a.name;b||(b=a,a={name:b});a=h({main:"main"},a);a.location=a.location?a.location:b;if(a.packageMap)Ga[b]=a.packageMap;if(!a.main.indexOf("./"))a.main=a.main.substring(2);u[b]=a},X=function(a,b,d){for(var c in a){if("waitSeconds"==
c)f.waitms=1E3*(a[c]||0);"cacheBust"==c&&(na=a[c]?C(a[c])?a[c]:(new Date).getTime()+"":"");if("baseUrl"==c||"combo"==c)f[c]=a[c];if("async"==c){var e=a[c];f.legacyMode=k=C(e)&&/sync|legacyAsync/.test(e)?e:!e?"sync":!1;f.async=!k}a[c]!==A&&(f.rawConfig[c]=a[c],"has"!=c&&i.add("config-"+c,a[c],0,b))}if(!f.baseUrl)f.baseUrl="./";/\/$/.test(f.baseUrl)||(f.baseUrl+="/");for(c in a.has)i.add(c,a.has[c],0,b);o(a.packages,Ja);for(ga in a.packagePaths)o(a.packagePaths[ga],function(a){var b=ga+"/"+a;C(a)&&
(a={name:a});a.location=b;Ja(a)});pa(h(Ga,a.map),T);o(T,function(a){a[1]=pa(a[1],[]);if("*"==a[0])T.star=a[1]});pa(h(bb,a.paths),Fa);o(a.aliases,function(a){C(a[0])&&(a[0]=RegExp("^"+Ia(a[0])+"$"));Ea.push(a)});for(c in a.config)b=t(c,d),b.config=h(b.config||{},a.config[c]);if(a.cache)W(),U=a.cache,a.cache["*noref"]&&W();r("config",[a,f.rawConfig])};i("dojo-cdn");var Ka=s.getElementsByTagName("script");p=0;for(var Y,B,Z,M;p<Ka.length;)if(Y=Ka[p++],(Z=Y.getAttribute("src"))&&(M=Z.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))){B=
M[3]||"";x.baseUrl=x.baseUrl||B;(Z=Y.getAttribute("data-dojo-config")||Y.getAttribute("djConfig"))&&(V=f.eval("({ "+Z+" })","data-dojo-config"));break}f.rawConfig={};X(x,1);if(i("dojo-cdn"))(u.dojo.location=B)&&(B+="/"),u.dijit.location=B+"../dijit/",u.dojox.location=B+"../dojox/";X(j,1);X(V,1);var N=function(a){J(function(){o(a.deps,R)})},Aa=function(a,b,d,c,e){var g;if(C(a)){if((g=t(a,c,!0))&&g.executed)return g.result;throw q("undefinedModule",a);}ia(a)||(X(a,0,c),a=b,b=d);if(ia(a))if(a.length){for(var d=
"require*"+za(),L,i=[],j=0;j<a.length;)L=a[j++],i.push(t(L,c));g=h($("",d,0,""),{injected:2,deps:i,def:b||y,require:c?c.require:f,gc:1});l[g.mid]=g;N(g);var m=O&&"sync"!=k;J(function(){I(g,m)});g.executed||n.push(g);F()}else b&&b();return e},oa=function(a){if(!a)return f;var b=a.require;if(!b)b=function(d,c,e){return Aa(d,c,e,a,b)},a.require=h(b,f),b.module=a,b.toUrl=function(b){return Ha(b,a)},b.toAbsMid=function(b){return qa(b,a)},b.syncLoadNls=function(b){var b=K(b,a),c=l[b.mid];if(!c||!c.executed)if(w=
v[b.mid]||v["url:"+b.url])aa(w),c=l[b.mid];return c&&c.executed&&c.result};return b},n=[],ba=[],m={},cb=function(a){a.injected=1;m[a.mid]=1;a.url&&(m[a.url]=a.pack||1);La()},E=function(a){a.injected=2;delete m[a.mid];a.url&&delete m[a.url];ya(m)&&(ca(),"xd"==k&&(k="sync"))},db=f.idle=function(){return!ba.length&&ya(m)&&!n.length&&!O},ra=function(a,b){if(b)for(var d=0;d<b.length;d++)if(b[d][2].test(a))return b[d];return 0},Ma=function(a){for(var b=[],d,c,a=a.replace(/\\/g,"/").split("/");a.length;)d=
a.shift(),".."==d&&b.length&&".."!=c?(b.pop(),c=b[b.length-1]):"."!=d&&b.push(c=d);return b.join("/")},$=function(a,b,d,c){var e=f.isXdUrl(c);return{pid:a,mid:b,pack:d,url:c,executed:0,def:0,isXd:e,isAmd:!!(e||u[a]&&u[a].isAmd)}},Na=function(a,b,d,c,e,f,L,k){var j,l,h,m;m=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||m&&!b)return $(0,a,0,a);a=Ma(m?b.mid+"/../"+a:a);if(/^\./.test(a))throw q("irrationalPath",a);b&&(h=ra(b.mid,f));(h=(h=h||f.star)&&ra(a,h[1]))&&(a=h[1]+a.substring(h[3]));b=(M=a.match(/^([^\/]+)(\/(.+))?$/))?
M[1]:"";(j=d[b])?a=b+"/"+(l=M[3]||j.main):b="";var n=0;o(Ea,function(b){var c=a.match(b[0]);c&&0<c.length&&(n=z(b[1])?a.replace(b[0],b[1]):b[1])});if(n)return Na(n,0,d,c,e,f,L,k);if(d=c[a])return k?$(d.pid,d.mid,d.pack,d.url):c[a];c=(h=ra(a,L))?h[1]+a.substring(h[3]):b?j.location+"/"+l:i("config-tlmSiblingOfDojo")?"../"+a:a;/(^\/)|(\:)/.test(c)||(c=e+c);return $(b,a,j,Ma(c+".js"))},K=function(a,b){return Na(a,b,u,l,f.baseUrl,T,Fa)},Oa=function(a,b,d){return a.normalize?a.normalize(b,function(a){return qa(a,
d)}):qa(b,d)},Pa=0,t=function(a,b,d){var c,e;(c=a.match(/^(.+?)\!(.*)$/))?(e=t(c[1],b,d),"sync"==k&&!e.executed&&(R(e),2===e.injected&&!e.executed&&J(function(){I(e)}),e.executed?da(e):n.unshift(e)),5===e.executed&&!e.load&&da(e),e.load?(c=Oa(e,c[2],b),a=e.mid+"!"+(e.dynamic?++Pa+"!":"")+c):(c=c[2],a=e.mid+"!"+ ++Pa+"!waitingForPlugin"),a={plugin:e,mid:a,req:oa(b),prid:c}):a=K(a,b);return l[a.mid]||!d&&(l[a.mid]=a)},qa=f.toAbsMid=function(a,b){return K(a,b).mid},Ha=f.toUrl=function(a,b){var d=K(a+
"/x",b),c=d.url;return S(0===d.pid?a:c.substring(0,c.length-5))},Qa={injected:2,executed:5,def:3,result:3},sa=function(a){return l[a]=h({mid:a},Qa)},eb=sa("require"),fb=sa("exports"),gb=sa("module"),ea={},ta=0,da=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},hb=function(a){var b={};o(a.loadQ,function(c){var d=Oa(a,c.prid,c.req.module),f=a.dynamic?c.mid.replace(/waitingForPlugin$/,d):a.mid+"!"+d,d=h(h({},c),{mid:f,prid:d,injected:0});l[f]||Ra(l[f]=d);
b[c.mid]=l[f];E(c);delete l[c.mid]});a.loadQ=0;var d=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},c;for(c in l)d(l[c]);o(n,d)},H=function(a){f.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=ta++;o(a.provides,function(a){a()});a.loadQ&&(da(a),hb(a));for(p=0;p<n.length;)n[p]===a?n.splice(p,1):p++;/^require\*/.test(a.mid)&&delete l[a.mid]},ib=[],I=function(a,b){if(4===a.executed)return f.trace("loader-circular-dependency",[ib.concat(a.mid).join("->")]),
!a.def||b?ea:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return ea;var d=a.mid,c=a.deps||[],e,g=[],h=0;for(a.executed=4;h<c.length;){e=c[h++];e=e===eb?oa(a):e===fb?a.cjs.exports:e===gb?a.cjs:I(e,b);if(e===ea)return a.executed=0,f.trace("loader-exec-module",["abort",d]),ea;g.push(e)}f.trace("loader-run-factory",[a.mid]);var d=a.def,j;D.unshift(a);if(i("config-dojo-loader-catches"))try{j=z(d)?d.apply(null,g):d}catch(k){r("error",a.result=q("factoryThrew",[a,k]))}else j=z(d)?d.apply(null,g):d;a.result=
void 0===j&&a.cjs?a.cjs.exports:j;D.shift(a);H(a)}return a.result},O=0,J=function(a){try{O++,a()}finally{O--}db()&&r("idle",[])},F=function(){O||J(function(){ka();for(var a,b,d=0;d<n.length;)a=ta,b=n[d],I(b),a!=ta?(ka(),d=0):d++})};void 0===i("dojo-loader-eval-hint-url")&&i.add("dojo-loader-eval-hint-url",1);var S=function(a){a+="";return a+(na?(/\?/.test(a)?"&":"?")+na:"")},Ra=function(a){var b=a.plugin;5===b.executed&&!b.load&&da(b);var d=function(b){a.result=b;E(a);H(a);F()};b.load?b.load(a.prid,
a.req,d):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],n.unshift(b),R(b))},w=0,P=0,ua=0,aa=function(a,b){i("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));ua=1;if(i("config-dojo-loader-catches"))try{a===w?w.call(null):f.eval(a,i("dojo-loader-eval-hint-url")?b.url:b.mid)}catch(d){r("error",q("evalModuleThrew",b))}else a===w?w.call(null):f.eval(a,i("dojo-loader-eval-hint-url")?b.url:b.mid);ua=0},R=function(a){var b=a.mid,d=a.url;if(!a.executed&&!a.injected&&!(m[b]||a.url&&(a.pack&&m[a.url]===a.pack||
1==m[a.url])))if(cb(a),a.plugin)Ra(a);else{var c=function(){Sa(a);2!==a.injected&&(E(a),h(a,Qa),f.trace("loader-define-nonmodule",[a.url]));k?!D.length&&F():F()};if(w=v[b]||v["url:"+a.url])f.trace("loader-inject",["cache",a.mid,d]),aa(w,a),c();else{if(k)if(a.isXd)"sync"==k&&(k="xd");else if(!(a.isAmd&&"sync"!=k)){var e=function(e){if("sync"==k){D.unshift(a);aa(e,a);D.shift();Sa(a);a.cjs||(E(a),H(a));if(a.finish){var e=b+"*finish",g=a.finish;delete a.finish;va(e,["dojo",("dojo/require!"+g.join(",")).replace(/\./g,
"/")],function(a){o(g,function(b){a.require(b)})});n.unshift(t(e))}c()}else(e=Ca(a,e))?(aa(e,a),c()):(P=a,f.injectUrl(S(d),c,a),P=0)};f.trace("loader-inject",["xhr",a.mid,d,"sync"!=k]);if(i("config-dojo-loader-catches"))try{f.getText(d,"sync"!=k,e)}catch(g){r("error",q("xhrInjectFailed",[a,g]))}else f.getText(d,"sync"!=k,e);return}f.trace("loader-inject",["script",a.mid,d]);P=a;f.injectUrl(S(d),c,a);P=0}}},wa=function(a,b,d){f.trace("loader-define-module",[a.mid,b]);var c=a.mid;if(2===a.injected)return r("error",
q("multipleDefine",a)),a;h(a,{deps:b,def:d,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var e=0;e<b.length;e++)b[e]=t(b[e],a);k&&!m[c]&&(N(a),n.push(a),F());E(a);if(!z(d)&&!b.length)a.result=d,H(a);return a},Sa=function(a,b){for(var d=[],c,e;ba.length;)e=ba.shift(),b&&(e[0]=b.shift()),c=e[0]&&t(e[0])||a,d.push([c,e[1],e[2]]);W(a);o(d,function(a){N(wa.apply(null,a))})},fa=0,ca=y,La=y;ca=function(){fa&&clearTimeout(fa);
fa=0};La=function(){ca();f.waitms&&(fa=window.setTimeout(function(){ca();r("error",q("timeout",m))},f.waitms))};i.add("ie-event-behavior",!!s.attachEvent&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var xa=function(a,b,d,c){if(i("ie-event-behavior"))return a.attachEvent(d,c),function(){a.detachEvent(d,c)};a.addEventListener(b,c,!1);return function(){a.removeEventListener(b,c,!1)}},jb=xa(window,"load","onload",function(){f.pageLoaded=1;"complete"!=s.readyState&&(s.readyState=
"complete");jb()}),Ta=s.getElementsByTagName("script")[0],kb=Ta.parentNode;f.injectUrl=function(a,b,d){var d=d.node=s.createElement("script"),c=xa(d,"load","onreadystatechange",function(a){var a=a||window.event,d=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(d.readyState))c(),e(),b&&b()}),e=xa(d,"error","onerror",function(b){c();e();r("error",q("scriptError",[a,b]))});d.type="text/javascript";d.charset="utf-8";d.src=a;kb.insertBefore(d,Ta);return d};f.log=function(){try{for(var a=
0;a<arguments.length;a++);}catch(b){}};f.trace=y;var va=function(a,b,d){var c=arguments.length,e=["require","exports","module"],g=[0,a,b];1==c?g=[0,z(a)?e:[],a]:2==c&&C(a)?g=[a,z(b)?e:[],b]:3==c&&(g=[a,b,d]);f.trace("loader-define",g.slice(0,2));if((c=g[0]&&t(g[0]))&&!m[c.mid])N(wa(c,g[1],g[2]));else if(!i("ie-event-behavior")||ua)ba.push(g);else{c=c||P;if(!c)for(a in m)if((e=l[a])&&e.node&&"interactive"===e.node.readyState){c=e;break}c?(W(c),N(wa(c,g[1],g[2]))):r("error",q("ieDefineFailed",g[0]));
F()}};va.amd={vendor:"dojotoolkit.org"};h(h(f,x.loaderPatch),j.loaderPatch);ab("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(d){}});h(f,{uid:za,cache:v,packs:u});if(G.define)r("error",q("defineAlreadyDefined",0));else{G.define=va;G.require=f;var Ua=V.deps||j.deps||x.deps,Va=V.callback||j.callback||x.callback;f.boot=Ua||Va?[Ua||[],Va]:0}})(this.dojoConfig||this.djConfig||this.require||{},{async:0,hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,
"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../dojox",name:"dojox"},{location:"../dijit",name:"dijit"},{location:".",name:"dojo"},{location:"../util/doh",name:"doh"}]});(function(){var j=this.require;j({cache:{}});!j.async&&j(["dojo"]);j.boot&&j.apply(null,j.boot)})();