//>>built
define("dojo/fx","./_base/lang,./Evented,./_base/kernel,./_base/array,./_base/connect,./_base/fx,./dom,./dom-style,./dom-geometry,./ready,require".split(","),function(g,p,f,h,c,i,m,o,q,j,r){f.isAsync||j(0,function(){r(["./fx/Toggler"])});var f=f.fx={},j={_fire:function(a,b){this[a]&&this[a].apply(this,b||[]);return this}},k=function(a){this._index=-1;this._animations=a||[];this._current=this._onAnimateCtx=this._onEndCtx=null;this.duration=0;h.forEach(this._animations,function(a){this.duration+=a.duration;
a.delay&&(this.duration+=a.delay)},this)};k.prototype=new p;g.extend(k,{_onAnimate:function(){this._fire("onAnimate",arguments)},_onEnd:function(){c.disconnect(this._onAnimateCtx);c.disconnect(this._onEndCtx);this._onAnimateCtx=this._onEndCtx=null;this._index+1==this._animations.length?this._fire("onEnd"):(this._current=this._animations[++this._index],this._onAnimateCtx=c.connect(this._current,"onAnimate",this,"_onAnimate"),this._onEndCtx=c.connect(this._current,"onEnd",this,"_onEnd"),this._current.play(0,
!0))},play:function(a,b){if(!this._current)this._current=this._animations[this._index=0];if(!b&&"playing"==this._current.status())return this;var d=c.connect(this._current,"beforeBegin",this,function(){this._fire("beforeBegin")}),e=c.connect(this._current,"onBegin",this,function(a){this._fire("onBegin",arguments)}),l=c.connect(this._current,"onPlay",this,function(a){this._fire("onPlay",arguments);c.disconnect(d);c.disconnect(e);c.disconnect(l)});this._onAnimateCtx&&c.disconnect(this._onAnimateCtx);
this._onAnimateCtx=c.connect(this._current,"onAnimate",this,"_onAnimate");this._onEndCtx&&c.disconnect(this._onEndCtx);this._onEndCtx=c.connect(this._current,"onEnd",this,"_onEnd");this._current.play.apply(this._current,arguments);return this},pause:function(){if(this._current){var a=c.connect(this._current,"onPause",this,function(b){this._fire("onPause",arguments);c.disconnect(a)});this._current.pause()}return this},gotoPercent:function(a,b){this.pause();var d=this.duration*a;this._current=null;
h.some(this._animations,function(a){if(a.duration<=d)return this._current=a,!0;d-=a.duration;return!1});this._current&&this._current.gotoPercent(d/this._current.duration,b);return this},stop:function(a){if(this._current){if(a){for(;this._index+1<this._animations.length;++this._index)this._animations[this._index].stop(!0);this._current=this._animations[this._index]}var b=c.connect(this._current,"onStop",this,function(a){this._fire("onStop",arguments);c.disconnect(b)});this._current.stop()}return this},
status:function(){return this._current?this._current.status():"stopped"},destroy:function(){this._onAnimateCtx&&c.disconnect(this._onAnimateCtx);this._onEndCtx&&c.disconnect(this._onEndCtx)}});g.extend(k,j);f.chain=function(a){return new k(a)};var n=function(a){this._animations=a||[];this._connects=[];this.duration=this._finished=0;h.forEach(a,function(a){var b=a.duration;a.delay&&(b+=a.delay);if(this.duration<b)this.duration=b;this._connects.push(c.connect(a,"onEnd",this,"_onEnd"))},this);this._pseudoAnimation=
new i.Animation({curve:[0,1],duration:this.duration});var b=this;h.forEach("beforeBegin,onBegin,onPlay,onAnimate,onPause,onStop,onEnd".split(","),function(a){b._connects.push(c.connect(b._pseudoAnimation,a,function(){b._fire(a,arguments)}))})};g.extend(n,{_doAction:function(a,b){h.forEach(this._animations,function(d){d[a].apply(d,b)});return this},_onEnd:function(){++this._finished>this._animations.length&&this._fire("onEnd")},_call:function(a,b){var d=this._pseudoAnimation;d[a].apply(d,b)},play:function(a,
b){this._finished=0;this._doAction("play",arguments);this._call("play",arguments);return this},pause:function(){this._doAction("pause",arguments);this._call("pause",arguments);return this},gotoPercent:function(a,b){var d=this.duration*a;h.forEach(this._animations,function(a){a.gotoPercent(a.duration<d?1:d/a.duration,b)});this._call("gotoPercent",arguments);return this},stop:function(a){this._doAction("stop",arguments);this._call("stop",arguments);return this},status:function(){return this._pseudoAnimation.status()},
destroy:function(){h.forEach(this._connects,c.disconnect)}});g.extend(n,j);f.combine=function(a){return new n(a)};f.wipeIn=function(a){var b=a.node=m.byId(a.node),d=b.style,e,a=i.animateProperty(g.mixin({properties:{height:{start:function(){e=d.overflow;d.overflow="hidden";if("hidden"==d.visibility||"none"==d.display)return d.height="1px",d.display="",d.visibility="",1;var a=o.get(b,"height");return Math.max(a,1)},end:function(){return b.scrollHeight}}}},a)),l=function(){d.height="auto";d.overflow=
e};c.connect(a,"onStop",l);c.connect(a,"onEnd",l);return a};f.wipeOut=function(a){var b=(a.node=m.byId(a.node)).style,d,a=i.animateProperty(g.mixin({properties:{height:{end:1}}},a));c.connect(a,"beforeBegin",function(){d=b.overflow;b.overflow="hidden";b.display=""});var e=function(){b.overflow=d;b.height="auto";b.display="none"};c.connect(a,"onStop",e);c.connect(a,"onEnd",e);return a};f.slideTo=function(a){var b=null,d=null,e=function(a){return function(){var c=o.getComputedStyle(a),e=c.position;
b="absolute"==e?a.offsetTop:parseInt(c.top)||0;d="absolute"==e?a.offsetLeft:parseInt(c.left)||0;if("absolute"!=e&&"relative"!=e)c=q.position(a,!0),b=c.y,d=c.x,a.style.position="absolute",a.style.top=b+"px",a.style.left=d+"px"}}(a.node=m.byId(a.node));e();a=i.animateProperty(g.mixin({properties:{top:a.top||0,left:a.left||0}},a));c.connect(a,"beforeBegin",a,e);return a};return f});