define({      
//begin v1.x content
	"clearFilterDialogTitle": "Szűrő törlése",
	"filterDefDialogTitle": "Szűrő",
	"defaultRuleTitle": "Szabály",
	"ruleTitleTemplate": "${ruleNumber} szabály",
	"noFilterApplied": "Nincs alkalmazva szűrő.",
	"defineFilter": "Szűrő meghatározása",
	"conditionEqual": "egyenlő",
	"conditionNotEqual": "nem egyenlő",
	"conditionLess": "kisebb mint",
	"conditionLessEqual": "kisebb vagy egyenlő",
	"conditionGreater": "nagyobb mint",
	"conditionGreaterEqual": "nagyobb vagy egyenlő",
	"conditionContain": "tartalmazza",
	"conditionIs": "pontosan",
	"conditionStartWith": "kezdete",
	"conditionEndWith": "vége",
	"conditionNotContain": "nem tartalmazza",
	"conditionIsNot": "nem",
	"conditionNotStartWith": "nem kezdete",
	"conditionNotEndWith": "nem vége",
	"conditionBefore": "előtt",
	"conditionAfter": "után",
	"conditionRange": "tartomány",
	"conditionIsEmpty": "üres",
	"all": "mind",
	"any": "bármely",
	"relationAll": "minden szabály",
	"waiRelAll": "Megfelel a következő összes szabálynak:",
	"relationAny": "bármely szabály",
	"waiRelAny": "Megfelel a következő bármely szabálynak:",
	"relationMsgFront": "Megfelel",
	"relationMsgTail": "",
	"and": "és",
	"or": "vagy",
	"addRuleButton": "Szabály hozzáadása",
	"waiAddRuleButton": "Új szabály hozzáadása",
	"removeRuleButton": "Szabály eltávolítása",
	"waiRemoveRuleButtonTemplate": "${0} szabály eltávolítása",
	"addRuleButton": "Szűrőszabály hozzáadása",
	"cancelButton": "Mégse",
	"waiCancelButton": "A párbeszédablak bezárása",
	"clearButton": "Törlés",
	"waiClearButton": "A szűrő törlése",
	"filterButton": "Szűrő",
	"waiFilterButton": "A szűrő elküldése",
	"columnSelectLabel": "Oszlop",
	"waiColumnSelectTemplate": "Oszlop a(z) ${0} szabályhoz",
	"conditionSelectLabel": "Feltétel",
	"waiConditionSelectTemplate": "Feltétel a(z) ${0} szabályhoz",
	"valueBoxLabel": "Érték",
	"waiValueBoxTemplate": "Írja be a szűrni kívánt értéket a(z) ${0} szabályhoz",
	"rangeTo": "-",
	"rangeTemplate": "${0} - ${1}",
	"statusTipHeaderColumn": "Oszlop",
	"statusTipHeaderCondition": "Szabályok",
	"statusTipTitle": "Szűrősáv",
	"statusTipMsg": "Kattintson a szűrősávra az értékek szűréséhez a következőben: ${0}.",
	"anycolumn": "bármely oszlop",
	"statusTipTitleNoFilter": "Szűrősáv",
	"statusTipTitleHasFilter": "Szűrő",
	"statusTipRelPre": "Megfelel",
	"statusTipRelPost": "szabálynak.",
	"statusTipHeaderAll": "Minden szabálynak megfelel.",
	"statusTipHeaderAny": "Bármely szabálynak megfelel.",
	"defaultItemsName": "elemek",
	"filterBarMsgHasFilterTemplate": "${0} / ${1} ${2} megjelenítve.",
	"filterBarMsgNoFilterTemplate": "Nincs szűrő alkalmazva.",
	"filterBarDefButton": "Szűrő meghatározása",
	"waiFilterBarDefButton": "Táblázat szűrése",
	"a11yFilterBarDefButton": "Szűrés...",
	"filterBarClearButton": "Szűrő törlése",
	"waiFilterBarClearButton": "A szűrő törlése",
	"closeFilterBarBtn": "Szűrősáv bezárása",
	"clearFilterMsg": "Eltávolítja a szűrőt és megjeleníti az összes elérhető rekordot.",
	"anyColumnOption": "Bármely oszlop",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "Az érték True",
	"radioFalseLabel": "Az érték False",
	"beginTimeRangeLabel": "Időtartam érték kezdete",
	"endTimeRangeLabel": "Időtartam érték vége",
	"beginDateRangeLabel": "Dátumtartomány érték kezdete",
	"endDateRangeLabel": "Dátumtartomány érték vége",
	"startsWithExpr": "${0}*"
//end v1.x content
});

