define({     
//Body
	loadingInfo: "Memuatkan...",
	emptyInfo: "Tidak ada item untuk ditampilkan",
	loadFailInfo: "Tidak dapat memuat data!",
	loadMore: "Muatkan Lebih Banyak",
	loadMoreLoading: "Memuatkan...",
	loadPrevious: "Muatkan Sebelumnya",
	loadPreviousLoading: "Memuatkan...",

//FilterBar
	"clearFilterDialogTitle": "Kosongkan Filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Penggaris",
	"ruleTitleTemplate": "Penggaris ${ruleNumber}",
	"noFilterApplied": "Tidak ada filter yang diterapkan.",
	"defineFilter": "Menetapkan filter",
	"conditionEqual": "sama dengan",
	"conditionNotEqual": "tidak sama dengan",
	"conditionLess": "kurang dari",
	"conditionLessEqual": "kurang dari atau sama dengan",
	"conditionGreater": "lebih dari",
	"conditionGreaterEqual": "lebih dari atau sama dengan",
	"conditionContain": "berisi",
	"conditionIs": "adalah",
	"conditionStartWith": "dimulai dengan",
	"conditionEndWith": "diakhiri dengan",
	"conditionNotContain": "tidak memuat",
	"conditionIsNot": "tidak",
	"conditionNotStartWith": "dimulai dengan",
	"conditionNotEndWith": "tidak dimulai dengan",
	"conditionBefore": "sebelum",
	"conditionAfter": "setelah",
	"conditionRange": "rentang",
	"conditionIsEmpty": "kosong",
	"all": "semua",
	"any": "apa pun",
	"relationAll": "semua penggaris",
	"waiRelAll": "Sesuaikan semua penggaris:",
	"relationAny": "penggaris apa pun",
	"waiRelAny": "Sesuaikan semua penggaris berikut:",
	"relationMsgFront": "Sesuaikan",
	"relationMsgTail": "",
	"and": "dan",
	"or": "atau",
	"addRuleButton": "Tambah Penggaris",
	"waiAddRuleButton": "Tambahkan penggaris baru",
	"removeRuleButton": "Hapus Penggaris",
	"waiRemoveRuleButtonTemplate": "Hapus penggaris ${0}",
	"addRuleButton": "Tambahkan Penggaris Filter",
	"cancelButton": "Batal",
	"waiCancelButton": "Batalkan dialog ini",
	"clearButton": "Kosongkan",
	"waiClearButton": "Kosongkan filter",
	"filterButton": "Filter",
	"waiFilterButton": "Kirimkan filter",
	"columnSelectLabel": "Kolom",
	"waiColumnSelectTemplate": "Kolom untuk penggaris ${0}",
	"conditionSelectLabel": "Kondisi",
	"waiConditionSelectTemplate": "Kondisi untuk penggaris ${0}",
	"valueBoxLabel": "Nilai",
	"waiValueBoxTemplate": "Masukkan nilai untuk menyaring penggaris ${0}",
	"rangeTo": "hingga",
	"rangeTemplate": "dari ${0} hingga ${1}",
	"statusTipHeaderColumn": "Kolom",
	"statusTipHeaderCondition": "Penggaris",
	"statusTipTitle": "Bilah Filter",
	"statusTipMsg": "Klik bilah filter di sini untuk menyaring nilai pada ${0}.",
	"anycolumn": "kolom mana pun",
	"statusTipTitleNoFilter": "Bilah Bar",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Sesuai",
	"statusTipRelPost": "penggaris.",
	"statusTipHeaderAll": "Sesuaikan semua penggaris.",
	"statusTipHeaderAny": "Sesuaikan semua penggaris berikut.",
	"defaultItemsName": "item",
	"filterBarMsgHasFilterTemplate": "${0} dari ${1} ${2} diperlihatkan.",
	"filterBarMsgNoFilterTemplate": "Tidak ada filter yang diterapkan",
	"filterBarDefButton": "Tentukan filter",
	"waiFilterBarDefButton": "Saring tabel",
	"a11yFilterBarDefButton": "Saring...",
	"filterBarClearButton": "Kosongkan filter",
	"waiFilterBarClearButton": "Kosongkan filter",
	"closeFilterBarBtn": "Tutup bilah filter",
	"clearFilterMsg": "Menutup bilah filter akan menghapus semua filter dan memperlihatkan semua catatan yang tersedia.",
	"anyColumnOption": "kolom mana pun",
	"trueLabel": "Benar",
	"falseLabel": "Salah",
	"radioTrueLabel": "Nilai Benar",
	"radioFalseLabel": "Nilai Salah",
	"beginTimeRangeLabel": "Awal Nilai Rentang Waktu",
	"endTimeRangeLabel": "Akhir Nilai Rentang Waktu",
	"beginDateRangeLabel": "Awal Nilai Rentang Tanggal",
	"endDateRangeLabel": "Akhir Nilai Rentang Tanggal",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Pengurutan Tunggal",
	nestedSort: "Pengurutan Berkelompok",
	ascending: "Klik untuk mengurutkan Ke Atas",
	descending: "Klik untuk mengurutkan Ke Bawah ",
	sortingState: "${0} - ${1}",
	unsorted: "Jangan mengurutkan kolom ini",
	waiSingleSortLabel: "${0} - diurutkan oleh ${1}. Pilih untuk mengurutkan berdasarkan ${2}",
	waiNestedSortLabel:"${0} - diurutkan secara berkelompok oleh ${1}. Pilih untuk mengurutkan secara berkelompok berdasarkan ${2}",

//PaginationBar
	pagerWai: 'Penyeranta',

	pageIndex: '${0}',
	pageIndexTitle: 'Halaman ${0}',

	firstPageTitle: 'Halaman pertama',
	prevPageTitle: 'Halaman sebelumnya',
	nextPageTitle: 'Halaman berikutnya',
	lastPageTitle: 'Halaman terakhir',

	pageSize: '${0}',
	pageSizeTitle: '${0} item per halaman',
	pageSizeAll: 'Semua',
	pageSizeAllTitle: 'Semua item',

	description: '${0} - ${1} dari ${2} item.',
	descriptionEmpty: 'Kisi dalam keadaan kosong.',

	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Dipilih: ${1}',

	gotoBtnTitle: 'Beralih ke halaman tertentu',

	gotoDialogTitle: 'Beralih ke Halaman',
	gotoDialogMainMsg: 'Tentukan nomor halaman:',
	gotoDialogPageCount: '(${0} halaman)',
	gotoDialogOKBtn: 'Beralih',
	gotoDialogCancelBtn: 'Batal',
	// for drop down pagination bar
	pageLabel: 'Halaman',
	pageSizeLabel: 'Baris',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Kosongkan Filter',
	buildFilterMenuLabel: 'Buat Filter&hellip;',
	apply: 'Terapkan Filter',

//Sort
	helpMsg: '${0} - Cliquez pour effectuer le tri ou cliquez et maintenez la touche Ctrl enfoncée pour ajouter un élément au tri',
	singleHelpMsg: '${0} - Cliquez pour effectuer le tri',
	priorityOrder: 'priorité de tri ${0}',

//SummaryBar
	summaryTotal: 'Total: ${0}',
	summarySelected: 'Total: ${0} Dipilih: ${1}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Press SPACE to select all.",	//need translation
	indirectDeselectAll: "Press SPACE to deselect all.",	//need translation
	treeExpanded: "Control + left arrow key to collapse this row.",	//need translation
	treeCollapsed: "Control + right arrow key to expand this row."	//need translation
});

