define({      
//begin v1.x content
	"clearFilterDialogTitle": "Brisanje filtera",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Filter nije primijenjen.",
	"defineFilter": "Definiraj filter",
	"conditionEqual": "jednako",
	"conditionNotEqual": "nije jednako",
	"conditionLess": "je manje od",
	"conditionLessEqual": "manje ili jednako",
	"conditionGreater": "je veće od",
	"conditionGreaterEqual": "veće ili jednako",
	"conditionContain": "sadrži",
	"conditionIs": "je",
	"conditionStartWith": "počinje sa",
	"conditionEndWith": "završava sa",
	"conditionNotContain": "ne sadrži",
	"conditionIsNot": "nije",
	"conditionNotStartWith": "ne počinje sa",
	"conditionNotEndWith": "ne završava sa",
	"conditionBefore": "prije",
	"conditionAfter": "poslije",
	"conditionRange": "raspon",
	"conditionIsEmpty": "je prazan",
	"all": "sve",
	"any": "bilo koje",
	"relationAll": "sva pravila",
	"waiRelAll": "Usporedi sva sljedeća pravila:",
	"relationAny": "bilo koja pravila",
	"waiRelAny": "Usporedi bilo koje od sljedećih pravila:",
	"relationMsgFront": "Usporedi",
	"relationMsgTail": "",
	"and": "i",
	"or": "ili",
	"addRuleButton": "Bilo koje pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Ukloni pravilo",
	"waiRemoveRuleButtonTemplate": "Ukloni pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtera",
	"cancelButton": "Opoziv",
	"waiCancelButton": "Opoziv ovog dijaloga",
	"clearButton": "Obriši",
	"waiClearButton": "Obriši filter",
	"filterButton": "Filter",
	"waiFilterButton": "Predaj filter",
	"columnSelectLabel": "Stupac",
	"waiColumnSelectTemplate": "Stupac za pravilo ${0}",
	"conditionSelectLabel": "Uvjet",
	"waiConditionSelectTemplate": "Uvjet za pravilo ${0}",
	"valueBoxLabel": "Vrijednost",
	"waiValueBoxTemplate": "Unesite vrijednost filtera za pravilo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Stupac",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Traka filtera",
	"statusTipMsg": "Kliknite traku filtera za filtriranje po vrijednostima u ${0}.",
	"anycolumn": "bilo koji stupac",
	"statusTipTitleNoFilter": "Traka filtera",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Usporedi",
	"statusTipRelPost": "pravila.",
	"statusTipHeaderAll": "Usporedi sva pravila.",
	"statusTipHeaderAny": "Usporedi bilo koje pravilo.",
	"defaultItemsName": "stavke",
	"filterBarMsgHasFilterTemplate": "${0} od ${1} ${2} prikazano.",
	"filterBarMsgNoFilterTemplate": "Filter nije primijenjen",
	"filterBarDefButton": "Definiraj filter",
	"waiFilterBarDefButton": "Filtriraj tablicu",
	"a11yFilterBarDefButton": "Filtriraj...",
	"filterBarClearButton": "Obriši filter",
	"waiFilterBarClearButton": "Obriši filter",
	"closeFilterBarBtn": "Zatvori traku filtera",
	"clearFilterMsg": "Ovo uklanja filter i prikazuje sve raspoložive slogove.",
	"anyColumnOption": "Bilo koji stupac",
	"trueLabel": "Istinito",
	"falseLabel": "Neistinito",
	"radioTrueLabel": "Istinita vrijednost",
	"radioFalseLabel": "Neistinita vrijednost",
	"beginTimeRangeLabel": "Početna vrijednost raspona vremena",
	"endTimeRangeLabel": "Završna vrijednost raspona vremena",
	"beginDateRangeLabel": "Početna vrijednost raspona datuma",
	"endDateRangeLabel": "Završna vrijednost raspona datuma",
	"startsWithExpr": "${0}*"
//end v1.x content
});

