define([
	'gridxdoh/status/Core',
	'gridxdoh/status/Header',
	'gridxdoh/status/Body',
	'gridxdoh/status/VScroller',
	'gridxdoh/status/RowHeader',
	'gridxdoh/status/HScroller',
	'gridxdoh/status/VLayout',

	'gridxdoh/status/autoHeight',
	'gridxdoh/status/autoWidth',
	'gridxdoh/status/headerHidden',
	'gridxdoh/actions/headerHidden',
	'gridxdoh/status/sortInitialOrder',
	'gridxdoh/status/hiddenColumnsInit',
	'gridxdoh/status/indirectSelectAll',
	'gridxdoh/status/indirectSelectPosition',
	'gridxdoh/status/indirectSelectWidth',
	'gridxdoh/status/rowHeaderWidth',
	'gridxdoh/status/columnLockCount',
	'gridxdoh/status/filterBarFilterData',
	'gridxdoh/status/filterBarCloseButton',
	'gridxdoh/actions/filterBarCloseButton',
	'gridxdoh/status/filterBarDefineFilterButton',
	'gridxdoh/actions/filterBarDefineFilterButton',
	'gridxdoh/status/paginationBarGotoButton',
	'gridxdoh/actions/paginationBarGotoButton',
	'gridxdoh/status/paginationBarSizeSwitch',
	'gridxdoh/actions/paginationBarSizeSwitch',
	'gridxdoh/status/paginationBarStepper',
	'gridxdoh/actions/paginationBarStepper',
	'gridxdoh/status/paginationBarDescription',
	'gridxdoh/actions/paginationBarDescription',
	'gridxdoh/status/paginationBarSizes',
	'gridxdoh/actions/paginationBarSizes',
	'gridxdoh/status/paginationBarSizeSeparator',
	'gridxdoh/actions/paginationBarSizeSeparator',
	'gridxdoh/status/paginationBarPosition',
	'gridxdoh/actions/filterBarMaxRuleCount'
//    'gridx/doh/actions/filterBarRuleCountToConfirmClearFilter',


//    'gridxdoh/actions/HiddenColumns',
//    'gridxdoh/actions/VScroller',
//    'gridxdoh/actions/Header',
//    'gridxdoh/actions/Body',
//    'gridxdoh/actions/HScrolsler',
// 'gridxdoh/actions/SelectRow',
], function(){
});
