//>>built
define("dojox/calendar/Mouse","dojo/_base/array,dojo/_base/declare,dojo/_base/event,dojo/_base/lang,dojo/_base/window,dojo/dom-geometry,dojo/mouse,dojo/on,dojo/keys".split(","),function(j,k,g,d,h,l,i,e){return k("dojox.calendar.Mouse",null,{triggerExtent:3,postMixInProperties:function(){this.inherited(arguments);this.on("rendererCreated",d.hitch(this,function(b){var a=b.renderer,c;if(!a.__handles)a.__handles=[];c=e(a.domNode,"click",d.hitch(this,function(b){g.stop(b);this._onItemClick({triggerEvent:b,
renderer:a,item:this.renderItemToItem(a.item,this.get("store"))})}));a.__handles.push(c);c=e(a.domNode,"dblclick",d.hitch(this,function(b){g.stop(b);this._onItemDoubleClick({triggerEvent:b,renderer:a,item:this.renderItemToItem(a.item,this.get("store"))})}));a.__handles.push(c);c=e(a.domNode,"contextmenu",d.hitch(this,function(b){this._onItemContextMenu({triggerEvent:b,renderer:a,item:this.renderItemToItem(a.item,this.get("store"))})}));a.__handles.push(c);a.resizeStartHandle&&(c=e(a.resizeStartHandle,
"mousedown",d.hitch(this,function(b){this._onRendererHandleMouseDown(b,a,"resizeStart")})),a.__handles.push(c));a.moveHandle&&(c=e(a.moveHandle,"mousedown",d.hitch(this,function(b){this._onRendererHandleMouseDown(b,a,"move")})),a.__handles.push(c));a.resizeEndHandle&&(c=e(a.resizeEndHandle,"mousedown",d.hitch(this,function(b){this._onRendererHandleMouseDown(b,a,"resizeEnd")})),a.__handles.push(c));c=e(a.domNode,"mousedown",d.hitch(this,function(b){this._rendererMouseDownHandler(b,a)}));a.__handles.push(c);
c=e(b.container,i.enter,d.hitch(this,function(c){a.item&&!this._editingGesture&&(this._setHoveredItem(a.item.item,b.renderer),this._onItemRollOver(this.__fixEvt({item:this.renderItemToItem(a.item,this.get("store")),renderer:a,triggerEvent:c})))}));a.__handles.push(c);c=e(a.domNode,i.leave,d.hitch(this,function(b){a.item&&!this._editingGesture&&(this._setHoveredItem(null),this._onItemRollOut(this.__fixEvt({item:this.renderItemToItem(a.item,this.get("store")),renderer:a,triggerEvent:b})))}));a.__handles.push(c)}))},
_onItemRollOver:function(b){this._dispatchCalendarEvt(b,"onItemRollOver")},onItemRollOver:function(){},_onItemRollOut:function(b){this._dispatchCalendarEvt(b,"onItemRollOut")},onItemRollOut:function(){},_rendererMouseDownHandler:function(b,a){g.stop(b);var c=this.renderItemToItem(a.item,this.get("store"));this.selectFromEvent(b,c,a,!0);this._setTabIndexAttr&&this[this._setTabIndexAttr].focus()},_onRendererHandleMouseDown:function(b,a,c){g.stop(b);this.showFocus=!1;var f=a.item.item;if(!this.isItemBeingEdited(f))this._isEditing&&
this._endItemEditing("mouse",!1),this.selectFromEvent(b,this.renderItemToItem(a.item,this.get("store")),a,!0),this._setTabIndexAttr&&this[this._setTabIndexAttr].focus(),this._edProps={editKind:c,editedItem:f,rendererKind:a.rendererKind,tempEditedItem:f,liveLayout:this.liveLayout},this.set("focusedItem",this._edProps.editedItem);a=[];a.push(e(h.doc,"mouseup",d.hitch(this,this._editingMouseUpHandler)));a.push(e(h.doc,"mousemove",d.hitch(this,this._editingMouseMoveHandler)));f=this._edProps;f.handles=
a;f.eventSource="mouse";f.editKind=c;this._startPoint={x:b.screenX,y:b.screenY}},_editingMouseMoveHandler:function(b){var a=this._edProps;if(this._editingGesture)this._autoScroll(b.pageX,b.pageY,!0)||this._moveOrResizeItemGesture([this.getTime(b)],"mouse",b);else if(Math.abs(this._startPoint.x-b.screenX)>=this.triggerExtent||Math.abs(this._startPoint.y-b.screenY)>=this.triggerExtent)this._isEditing||this._startItemEditing(a.editedItem,"mouse"),a=this._edProps,this._startItemEditingGesture([this.getTime(b)],
a.editKind,"mouse",b)},_editingMouseUpHandler:function(b){var a=this._edProps;this._stopAutoScroll();this._isEditing?(this._editingGesture&&this._endItemEditingGesture("mouse",b),this._endItemEditing("mouse",!1)):j.forEach(a.handles,function(a){a.remove()})},_autoScroll:function(b,a,c){if(!this.scrollable||!this.autoScroll)return!1;var d=l.position(this.scrollContainer,!0),b=c?a-d.y:b-d.x,c=c?d.h:d.w;if(0>b||b>c)return step=Math.floor((0>b?b:b-c)/2)/3,this._startAutoScroll(step),!0;this._stopAutoScroll();
return!1}})});