define(
({
	"clearFilterDialogTitle": "Сүзгіні тазалау",
	"filterDefDialogTitle": "Сүзгі",
	"defaultRuleTitle": "Ереже",
	"ruleTitleTemplate": "${ruleNumber} ережесі",
	"noFilterApplied": "Сүзгі қолданылмады.",
	"defineFilter": "Сүзгіні анықтау",
	"conditionEqual": "тең",
	"conditionNotEqual": "тең емес",
	"conditionLess": "аздау",
	"conditionLessEqual": "кем немесе тең",
	"conditionGreater": "үлкендеу",
	"conditionGreaterEqual": "артық немесе тең",
	"conditionContain": "құрамында бар",
	"conditionIs": "–",
	"conditionStartWith": "басталады",
	"conditionEndWith": "аяқталады",
	"conditionNotContain": "құрамында жоқ",
	"conditionIsNot": "емес",
	"conditionNotStartWith": "басталмайды",
	"conditionNotEndWith": "аяқталмайды",
	"conditionBefore": "алдында",
	"conditionAfter": "артында",
	"conditionRange": "ауқым",
	"conditionIsEmpty": "бос",
	"all": "барлығы",
	"any": "кез келген",
	"relationAll": "барлық ережелер",
	"waiRelAll": "Барлық мына ережелерге сәйкес:",
	"relationAny": "кез келген ереже",
	"waiRelAny": "Мына ережелерге сәйкес:",
	"relationMsgFront": "Сәйкестендіру",
	"relationMsgTail": "",
	"and": "және",
	"or": "немесе",
	"addRuleButton": "Ереже қосу",
	"waiAddRuleButton": "Жаңа ереже қосу",
	"removeRuleButton": "Ережені алып тастау",
	"waiRemoveRuleButtonTemplate": "${0} ережесін алып тастау",
	"addRuleButton": "Сүзгі ережесін қосу",
	"cancelButton": "Болдырмау",
	"waiCancelButton": "Осы тілқатысу терезесін болдырмау",
	"clearButton": "Тазалау",
	"waiClearButton": "Сүзгіні тазалау",
	"filterButton": "Сүзгі",
	"waiFilterButton": "Сүзгіні жіберу",
	"columnSelectLabel": "Баған",
	"waiColumnSelectTemplate": "${0} ережесінің бағаны",
	"conditionSelectLabel": "Шарт",
	"waiConditionSelectTemplate": "${0} ережесінің шарты",
	"valueBoxLabel": "Мән",
	"waiValueBoxTemplate": "${0} ережесін сүзу үшін мәнді енгізу",
	"rangeTo": "неге",
	"rangeTemplate": "${0} мәнінен ${1} мәніне",
	"statusTipHeaderColumn": "Баған",
	"statusTipHeaderCondition": "Ережелер",
	"statusTipTitle": "Сүзгі тақтасы",
	"statusTipMsg": "${0} ішіндегі мәндер бойынша сүзу үшін сүзгі тақтасын нұқыңыз.",
	"anycolumn": "кез келген баған",
	"statusTipTitleNoFilter": "Сүзгі тақтасы",
	"statusTipTitleHasFilter": "Сүзгі",
	"statusTipRelPre": "Сәйкестендіру",
	"statusTipRelPost": "ережелер.",
	"statusTipHeaderAll": "Барлық ережелерді сәйкестендіріңіз.",
	"statusTipHeaderAny": "Кез келген ережелерді сәйкестендіріңіз.",
	"defaultItemsName": "элементтер",
	"filterBarMsgHasFilterTemplate": "${1} ${2} ішінен ${0} көрсетілді.",
	"filterBarMsgNoFilterTemplate": "Сүзгі қолданылмады",
	"filterBarDefButton": "Сүзгіні анықтау",
	"waiFilterBarDefButton": "Кестені сүзу",
	"a11yFilterBarDefButton": "Сүзгі...",
	"filterBarClearButton": "Сүзгіні тазалау",
	"waiFilterBarClearButton": "Сүзгіні тазалау",
	"closeFilterBarBtn": "Сүзгі тақтасын жабу",
	"clearFilterMsg": "Бұл сүзгіні жояды және барлық қол жетімді жазбаларды көрсетеді.",
	"anyColumnOption": "Кез келген баған",
	"trueLabel": "Шын",
	"falseLabel": "Жалған",
	"radioTrueLabel": "Рас мән",
	"radioFalseLabel": "Жалған мән",
	"beginTimeRangeLabel": "Уақыт ауқымы мәнінің басы",
	"endTimeRangeLabel": "Уақыт ауқымы мәнінің соңы",
	"beginDateRangeLabel": "Күн ауқымы мәнінің басы",
	"endDateRangeLabel": "Күн ауқымы мәнінің соңы",
	"startsWithExpr": "${0}*"
})
);

