define(
({
	"clearFilterDialogTitle": "Zrušiť filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravidlo",
	"ruleTitleTemplate": "Pravidlo ${ruleNumber}",
	"noFilterApplied": "Nepoužíva sa žiadny filter.",
	"defineFilter": "Definovať filter",
	"conditionEqual": "rovné",
	"conditionNotEqual": "nerovné",
	"conditionLess": "menšie ako",
	"conditionLessEqual": "menšie ako alebo rovné",
	"conditionGreater": "väčšie ako",
	"conditionGreaterEqual": "väčšie ako alebo rovné",
	"conditionContain": "obsahuje",
	"conditionIs": "je",
	"conditionStartWith": "začína s",
	"conditionEndWith": "končí s",
	"conditionNotContain": "neobsahuje",
	"conditionIsNot": "nie je",
	"conditionNotStartWith": "nezačína s",
	"conditionNotEndWith": "nekončí s",
	"conditionBefore": "pred",
	"conditionAfter": "za",
	"conditionRange": "rozsah",
	"conditionIsEmpty": "je prázdne",
	"all": "všetko",
	"any": "žiadne",
	"relationAll": "všetky pravidlá",
	"waiRelAll": "Vyhovovať všetkým týmto pravidlám:",
	"relationAny": "ľubovoľné pravidlá",
	"waiRelAny": "Vyhovovať ľubovoľným z týchto pravidiel:",
	"relationMsgFront": "Vyhovieť",
	"relationMsgTail": "",
	"and": "a",
	"or": "alebo",
	"addRuleButton": "Pridať pravidlo",
	"waiAddRuleButton": "Pridať nové pravidlo",
	"removeRuleButton": "Odstrániť pravidlo",
	"waiRemoveRuleButtonTemplate": "Odstrániť pravidlo ${0}",
	"addRuleButton": "Pridať filtrovacie pravidlo",
	"cancelButton": "Zrušiť",
	"waiCancelButton": "Zrušiť toto dialógové okno",
	"clearButton": "Zrušiť",
	"waiClearButton": "Zrušiť filter",
	"filterButton": "Filter",
	"waiFilterButton": "Odoslať filter",
	"columnSelectLabel": "Stĺpec",
	"waiColumnSelectTemplate": "Stĺpec pre pravidlo ${0}",
	"conditionSelectLabel": "Podmienka",
	"waiConditionSelectTemplate": "Podmienka pre pravidlo ${0}",
	"valueBoxLabel": "Hodnota",
	"waiValueBoxTemplate": "Zadajte hodnotu na filtrovanie pre pravidlo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Stĺpec",
	"statusTipHeaderCondition": "Pravidlá",
	"statusTipTitle": "Lišta filtra",
	"statusTipMsg": "Kliknite na lištu filtra, ak chcete filtrovať podľa hodnôt v ${0}.",
	"anycolumn": "ľubovoľný stĺpec",
	"statusTipTitleNoFilter": "Lišta filtra",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Vyhovieť",
	"statusTipRelPost": "pravidlá.",
	"statusTipHeaderAll": "Vyhovieť všetkým pravidlám.",
	"statusTipHeaderAny": "Vyhovieť ľubovoľným pravidlám.",
	"defaultItemsName": "položky",
	"filterBarMsgHasFilterTemplate": "Zobrazuje sa ${0} z ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Nepoužíva sa žiadny filter",
	"filterBarDefButton": "Definovať filter",
	"waiFilterBarDefButton": "Filtrovať tabuľku",
	"a11yFilterBarDefButton": "Filtrovať...",
	"filterBarClearButton": "Zrušiť filter",
	"waiFilterBarClearButton": "Zrušiť filter",
	"closeFilterBarBtn": "Zatvoriť lištu filtra",
	"clearFilterMsg": "Toto odstráni filter a zobrazí všetky dostupné záznamy",
	"anyColumnOption": "Ľubovoľný stĺpec",
	"trueLabel": "Pravda",
	"falseLabel": "Nepravda",
	"radioTrueLabel": "Hodnota pravda",
	"radioFalseLabel": "Hodnota nepravda",
	"beginTimeRangeLabel": "Začiatočná hodnota rozsahu časov",
	"endTimeRangeLabel": "Koncová hodnota rozsahu časov",
	"beginDateRangeLabel": "Začiatočná hodnota rozsahu dátumov",
	"endDateRangeLabel": "Koncová hodnota rozsahu dátumov",
	"startsWithExpr": "${0}*"
})
);

