define({     
//Body
	loadingInfo: "S'està carregant...",
	emptyInfo: "No hi ha cap element per visualitzar",
	loadFailInfo: "No s'han pogut carregar les dades",
	loadMore: "Més càrrega",
	loadMoreLoading: "S'està carregant...",
	loadPrevious: "Càrrega anterior",
	loadPreviousLoading: "S'està carregant...",

//FilterBar
	"clearFilterDialogTitle": "Netejar el filtre",
	"filterDefDialogTitle": "Filtre",
	"defaultRuleTitle": "Regla",
	"ruleTitleTemplate": "Regla ${ruleNumber}",
	"noFilterApplied": "No s'ha aplicat cap filtre.",
	"defineFilter": "Defineix filtre",
	"conditionEqual": "igual que",
	"conditionNotEqual": "no és igual que",
	"conditionLess": "és menys que",
	"conditionLessEqual": "és menys o igual que",
	"conditionGreater": "és més que",
	"conditionGreaterEqual": "és més o igual que",
	"conditionContain": "conté",
	"conditionIs": "és",
	"conditionStartWith": "comença per",
	"conditionEndWith": "acaba per",
	"conditionNotContain": "no conté",
	"conditionIsNot": "no és",
	"conditionNotStartWith": "no comença per",
	"conditionNotEndWith": "no acaba per",
	"conditionBefore": "abans",
	"conditionAfter": "després",
	"conditionRange": "interval",
	"conditionIsEmpty": "és buit",
	"all": "tot",
	"any": "qualsevol",
	"relationAll": "totes les regles",
	"waiRelAll": "Fes coincidir totes les regles següents:",
	"relationAny": "qualsevol regla",
	"waiRelAny": "Fes coincidir qualsevol de les regles següents:",
	"relationMsgFront": "Coincidència",
	"relationMsgTail": "",
	"and": "i",
	"or": "o",
	"addRuleButton": "Afegeix regla",
	"waiAddRuleButton": "Afegeix una regla nova",
	"removeRuleButton": "Elimina regla",
	"waiRemoveRuleButtonTemplate": "Elimina la regla ${0}",
	"addRuleButton": "Afegeix regla de filtre",
	"cancelButton": "Cancel·la",
	"waiCancelButton": "Cancel·la aquest diàleg",
	"clearButton": "Esborra",
	"waiClearButton": "Neteja el filtre",
	"filterButton": "Filtre",
	"waiFilterButton": "Envia el filtre",
	"columnSelectLabel": "Columna:",
	"waiColumnSelectTemplate": "Columna per a la regla ${0}",
	"conditionSelectLabel": "Condició:",
	"waiConditionSelectTemplate": "Condició per a la regla ${0}",
	"valueBoxLabel": "Valor:",
	"waiValueBoxTemplate": "Especifiqueu el valor de filtre per a la regla ${0}",
	"rangeTo": "a",
	"rangeTemplate": "de ${0} a ${1}",
	"statusTipHeaderColumn": "Columna",
	"statusTipHeaderCondition": "Regles",
	"statusTipTitle": "Barra de filtre",
	"statusTipMsg": "Feu clic aquí a la barra de filtre per filtrar els valors a ${0}.",
	"anycolumn": "qualsevol columna",
	"statusTipTitleNoFilter": "Barra de filtre",
	"statusTipTitleHasFilter": "Filtre",
	"statusTipRelPre": "Coincidència",
	"statusTipRelPost": "regles.",
	"statusTipHeaderAll": "Coincideix amb totes les regles.",
	"statusTipHeaderAny": "Coincideix amb qualsevol regla.",
	"defaultItemsName": "elements",
	"filterBarMsgHasFilterTemplate": "Es mostren ${0} de ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "No s'ha aplicat cap filtre",
	"filterBarDefButton": "Defineix filtre",
	"waiFilterBarDefButton": "Filtra la taula",
	"a11yFilterBarDefButton": "Filtre...",
	"filterBarClearButton": "Netejar filtre",
	"waiFilterBarClearButton": "Neteja el filtre",
	"closeFilterBarBtn": "Tancar la barra de filtre",
	"clearFilterMsg": "Això eliminarà el filtre i mostrarà tots els registres disponibles.",
	"anyColumnOption": "Qualsevol columna",
	"trueLabel": "Cert",
	"falseLabel": "Fals",
	"radioTrueLabel": "Valor Cert",
	"radioFalseLabel": "Valor Fals",
	"beginTimeRangeLabel": "Inici del valor de l'interval d'hora",
	"endTimeRangeLabel": "Finalització del valor de l'interval d'hora",
	"beginDateRangeLabel": "Inici del valor de l'interval de data",
	"endDateRangeLabel": "Finalització del valor de l'interval de data",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Ordre únic",
	nestedSort: "Ordre imbricat",
	ascending: "Feu clic per ordenar de forma ascendent",
	descending: "Feu clic per ordenar de forma descendent",
	sortingState: "${0} - ${1}",
	unsorted: "No ordenis aquesta finestra",
	waiSingleSortLabel: "${0} - s'ha ordenat per ${1}. Trieu que s'ordeni per ${2}",
	waiNestedSortLabel:"${0} - s'ha ordenat de forma imbricada per ${1}. Trieu que s'ordeni de forma imbricada per ${2}",

//PaginationBar
	pagerWai: 'Buscapersones',

	pageIndex: '${0}',
	pageIndexTitle: 'Pàgina ${0}',

	firstPageTitle: 'Primera pàgina',
	prevPageTitle: 'Pàgina anterior',
	nextPageTitle: 'Pàgina següent',
	lastPageTitle: 'Darrera pàgina',

	pageSize: '${0}',
	pageSizeTitle: '${0} elements per pàgina',
	pageSizeAll: 'Tots',
	pageSizeAllTitle: 'Tots els elements',

	description: '${0} - ${1} de ${2} elements.',
	descriptionEmpty: 'La graella està buida.',

	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Seleccionat: ${1}',

	gotoBtnTitle: 'Vés a una pàgina específica',

	gotoDialogTitle: 'Vés a pàgina',
	gotoDialogMainMsg: 'Especifiqueu el número de pàgina:',
	gotoDialogPageCount: ' (${0} pàgines)',
	gotoDialogOKBtn: 'Vés-hi',
	gotoDialogCancelBtn: 'Cancel·la',
	// for drop down pagination bar
	pageLabel: 'Pàgina',
	pageSizeLabel: 'Files',

//QuickFilter
	filterLabel: 'Filtre',
	clearButtonTitle: 'Netejar el filtre',
	buildFilterMenuLabel: 'Muntar el filtre&hellip;',
	apply: 'Aplicar el filtre',

//Sort
	helpMsg: '${0} - Feu clic per ordenar o control+clic per afegir a l\'ordenació',
	singleHelpMsg: '${0} - Feu clic per ordenar',
	priorityOrder: 'prioritat d\'ordenació ${0}',

//SummaryBar
	summaryTotal: 'Total: ${0}',
	summarySelected: 'Seleccionat: ${0}',
	summaryRange: 'Interval: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Feu clic a ESPAI per seleccionar-ho tot.",	//need translation
	indirectDeselectAll: "Feu clic a ESPAI per deseleccionar-ho tot.",	//need translation
	treeExpanded: "Control + tecla de fletxa a l'esquerra per reduir aquesta fila.",	//need translation
	treeCollapsed: "Control + tecla de fletxa a la dreta per expandir aquesta fila."	//need translation
});

