//>>built
define("dijit/Calendar","dojo/_base/array,dojo/date,dojo/date/locale,dojo/_base/declare,dojo/dom-attr,dojo/dom-class,dojo/_base/event,dojo/_base/kernel,dojo/keys,dojo/_base/lang,dojo/sniff,./CalendarLite,./_Widget,./_CssStateMixin,./_TemplatedMixin,./form/DropDownButton".split(","),function(i,s,t,g,j,b,k,l,d,m,n,o,h,p,q,r){var f=g("dijit.Calendar",[o,h,p],{cssStateNodes:{decrementMonth:"dijitCalendarArrow",incrementMonth:"dijitCalendarArrow",previousYearLabelNode:"dijitCalendarPreviousYear",nextYearLabelNode:"dijitCalendarNextYear"},
setValue:function(a){l.deprecated("dijit.Calendar:setValue() is deprecated.  Use set('value', ...) instead.","","2.0");this.set("value",a)},_createMonthWidget:function(){return new f._MonthDropDownButton({id:this.id+"_mddb",tabIndex:-1,onMonthSelect:m.hitch(this,"_onMonthSelect"),lang:this.lang,dateLocaleModule:this.dateLocaleModule},this.monthNode)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onkeydown","_onKeyDown");this.connect(this.dateRowsNode,"onmouseover","_onDayMouseOver");
this.connect(this.dateRowsNode,"onmouseout","_onDayMouseOut");this.connect(this.dateRowsNode,"onmousedown","_onDayMouseDown");this.connect(this.dateRowsNode,"onmouseup","_onDayMouseUp")},_onMonthSelect:function(a){var c=new this.dateClassObj(this.currentFocus);c.setDate(1);c.setMonth(a);var a=this.dateModule.getDaysInMonth(c),d=this.currentFocus.getDate();c.setDate(Math.min(d,a));this._setCurrentFocusAttr(c)},_onDayMouseOver:function(a){if((a=b.contains(a.target,"dijitCalendarDateLabel")?a.target.parentNode:
a.target)&&(a.dijitDateValue&&!b.contains(a,"dijitCalendarDisabledDate")||a==this.previousYearLabelNode||a==this.nextYearLabelNode))b.add(a,"dijitCalendarHoveredDate"),this._currentNode=a},_onDayMouseOut:function(a){if(this._currentNode&&!(a.relatedTarget&&a.relatedTarget.parentNode==this._currentNode))a="dijitCalendarHoveredDate",b.contains(this._currentNode,"dijitCalendarActiveDate")&&(a+=" dijitCalendarActiveDate"),b.remove(this._currentNode,a),this._currentNode=null},_onDayMouseDown:function(a){if((a=
a.target.parentNode)&&a.dijitDateValue&&!b.contains(a,"dijitCalendarDisabledDate"))b.add(a,"dijitCalendarActiveDate"),this._currentNode=a},_onDayMouseUp:function(a){(a=a.target.parentNode)&&a.dijitDateValue&&b.remove(a,"dijitCalendarActiveDate")},handleKey:function(a){var c=-1,b,e=this.currentFocus;switch(a.keyCode){case d.RIGHT_ARROW:c=1;case d.LEFT_ARROW:b="day";this.isLeftToRight()||(c*=-1);break;case d.DOWN_ARROW:c=1;case d.UP_ARROW:b="week";break;case d.PAGE_DOWN:c=1;case d.PAGE_UP:b=a.ctrlKey||
a.altKey?"year":"month";break;case d.END:e=this.dateModule.add(e,"month",1),b="day";case d.HOME:e=new this.dateClassObj(e);e.setDate(1);break;case d.ENTER:case d.SPACE:this.set("value",this.currentFocus);break;default:return!0}b&&(e=this.dateModule.add(e,b,c));this._setCurrentFocusAttr(e);return!1},_onKeyDown:function(a){this.handleKey(a)||k.stop(a)},onValueSelected:function(){},onChange:function(a){this.onValueSelected(a)},getClassForDate:function(){}});f._MonthDropDownButton=g("dijit.Calendar._MonthDropDownButton",
r,{onMonthSelect:function(){},postCreate:function(){this.inherited(arguments);this.dropDown=new f._MonthDropDown({id:this.id+"_mdd",onChange:this.onMonthSelect})},_setMonthAttr:function(a){var c=this.dateLocaleModule.getNames("months","wide","standAlone",this.lang,a);this.dropDown.set("months",c);this.containerNode.innerHTML=(6==n("ie")?"":"<div class='dijitSpacer'>"+this.dropDown.domNode.innerHTML+"</div>")+"<div class='dijitCalendarMonthLabel dijitCalendarCurrentMonthLabel'>"+c[a.getMonth()]+"</div>"}});
f._MonthDropDown=g("dijit.Calendar._MonthDropDown",[h,q],{months:[],templateString:"<div class='dijitCalendarMonthMenu dijitMenu' data-dojo-attach-event='onclick:_onClick,onmouseover:_onMenuHover,onmouseout:_onMenuHover'></div>",_setMonthsAttr:function(a){this.domNode.innerHTML=i.map(a,function(a,b){return a?"<div class='dijitCalendarMonthLabel' month='"+b+"'>"+a+"</div>":""}).join("")},_onClick:function(a){this.onChange(j.get(a.target,"month"))},onChange:function(){},_onMenuHover:function(a){b.toggle(a.target,
"dijitCalendarMonthLabelHover","mouseover"==a.type)}});return f});