define(
({
	"clearFilterDialogTitle": "Ştergere filtru",
	"filterDefDialogTitle": "Filtru",
	"defaultRuleTitle": "Regulă",
	"ruleTitleTemplate": "Regulă ${ruleNumber}",
	"noFilterApplied": "Nu este aplicat niciun filtru.",
	"defineFilter": "Definire filtru",
	"conditionEqual": "egal",
	"conditionNotEqual": "nu este egal",
	"conditionLess": "este mai mic decât",
	"conditionLessEqual": "mai mic sau egal",
	"conditionGreater": "este mai mare decât",
	"conditionGreaterEqual": "mai mare sau egal",
	"conditionContain": "conţine",
	"conditionIs": "este",
	"conditionStartWith": "începe cu",
	"conditionEndWith": "se termină cu",
	"conditionNotContain": "nu conţine",
	"conditionIsNot": "nu este",
	"conditionNotStartWith": "nu începe cu",
	"conditionNotEndWith": "nu se termină cu",
	"conditionBefore": "înaintea",
	"conditionAfter": "după",
	"conditionRange": "interval",
	"conditionIsEmpty": "este gol",
	"all": "toate",
	"any": "oricare",
	"relationAll": "toate regulile",
	"waiRelAll": "Răspundeţi tuturor regulilor următoare:",
	"relationAny": "oricare reguli",
	"waiRelAny": "Răspundeţi oricărei dintre regulile următoare:",
	"relationMsgFront": "Răspuns",
	"relationMsgTail": "",
	"and": "şi",
	"or": "sau",
	"addRuleButton": "Adăugare regulă",
	"waiAddRuleButton": "Adăugare regulă nouă",
	"removeRuleButton": "Înlăturare regulă",
	"waiRemoveRuleButtonTemplate": "Înlăturare regulă ${0}",
	"addRuleButton": "Adăugare regulă filtru",
	"cancelButton": "Anulare",
	"waiCancelButton": "Anulaţi acest dialog",
	"clearButton": "Ştergere",
	"waiClearButton": "Ştergeţi filtrul",
	"filterButton": "Filtru",
	"waiFilterButton": "Lansaţi în execuţie filtrul",
	"columnSelectLabel": "Coloană",
	"waiColumnSelectTemplate": "Coloană pentru regulă ${0}",
	"conditionSelectLabel": "Condiţie",
	"waiConditionSelectTemplate": "Condiţie pentru regula ${0}",
	"valueBoxLabel": "Valoare",
	"waiValueBoxTemplate": "Introduceţi valoarea pentru filtrarea pentru regulă ${0}",
	"rangeTo": "la",
	"rangeTemplate": "din ${0} la ${1}",
	"statusTipHeaderColumn": "Coloană",
	"statusTipHeaderCondition": "Reguli",
	"statusTipTitle": "Bară de filtru",
	"statusTipMsg": "Faceţi clic pe bara de filtru aici pentru a filtra valorile în ${0}.",
	"anycolumn": "orice coloană",
	"statusTipTitleNoFilter": "Bară de filtru",
	"statusTipTitleHasFilter": "Filtru",
	"statusTipRelPre": "Răspuns",
	"statusTipRelPost": "reguli.",
	"statusTipHeaderAll": "Potrivire cu toate regulile.",
	"statusTipHeaderAny": "Potrivire cu orice regulă.",
	"defaultItemsName": "articole",
	"filterBarMsgHasFilterTemplate": "${0} din ${1} ${2} afişate.",
	"filterBarMsgNoFilterTemplate": "Niciun filtru nu este aplicat",
	"filterBarDefButton": "Definire filtru",
	"waiFilterBarDefButton": "Filtrare tabelă",
	"a11yFilterBarDefButton": "Filtru...",
	"filterBarClearButton": "Ştergere filtru",
	"waiFilterBarClearButton": "Ştergeţi filtrul",
	"closeFilterBarBtn": "Închidere bară de filtru",
	"clearFilterMsg": "Aceasta va înlătura filtrul şi va afişa toate înregistrările disponibile.",
	"anyColumnOption": "Orice coloană",
	"trueLabel": "Adevărat",
	"falseLabel": "Fals",
	"radioTrueLabel": "Valoare Adevărat",
	"radioFalseLabel": "Valoare Fals",
	"beginTimeRangeLabel": "Valoare de început interval timp",
	"endTimeRangeLabel": "Valoare de sfârşit interval timp",
	"beginDateRangeLabel": "Valoare de început interval dată",
	"endDateRangeLabel": "Valoare de sfârşit interval dată",
	"startsWithExpr": "${0}*"
})
);

