define(
({
	"clearFilterDialogTitle": "清除過濾器",
	"filterDefDialogTitle": "過濾器",
	"defaultRuleTitle": "規則",
	"ruleTitleTemplate": "規則 ${ruleNumber}",
	"noFilterApplied": "無已套用的過濾器。",
	"defineFilter": "定義過濾器",
	"conditionEqual": "等於",
	"conditionNotEqual": "不等於",
	"conditionLess": "小於",
	"conditionLessEqual": "小於或等於",
	"conditionGreater": "大於",
	"conditionGreaterEqual": "大於或等於",
	"conditionContain": "包含",
	"conditionIs": "是",
	"conditionStartWith": "開始於",
	"conditionEndWith": "結束於",
	"conditionNotContain": "不包含",
	"conditionIsNot": "不是",
	"conditionNotStartWith": "不起始於",
	"conditionNotEndWith": "不結束於",
	"conditionBefore": "之前",
	"conditionAfter": "之後",
	"conditionRange": "範圍",
	"conditionIsEmpty": "為空白",
	"all": "全部",
	"any": "任何",
	"relationAll": "任何規則",
	"waiRelAll": "全部符合下列規則︰",
	"relationAny": "任何規則",
	"waiRelAny": "任意相符下列規則︰",
	"relationMsgFront": "符合",
	"relationMsgTail": "",
	"and": "和",
	"or": "或",
	"addRuleButton": "新增規則",
	"waiAddRuleButton": "新增規則",
	"removeRuleButton": "移除規則",
	"waiRemoveRuleButtonTemplate": "移除規則 ${0}",
	"addRuleButton": "新增過濾器規則",
	"cancelButton": "取消",
	"waiCancelButton": "取消此對話",
	"clearButton": "清除",
	"waiClearButton": "清除過濾器",
	"filterButton": "過濾器",
	"waiFilterButton": "提交過濾器",
	"columnSelectLabel": "直欄",
	"waiColumnSelectTemplate": "規則 ${0} 的直欄",
	"conditionSelectLabel": "條件",
	"waiConditionSelectTemplate": "規則 ${0} 的條件",
	"valueBoxLabel": "值",
	"waiValueBoxTemplate": "針對規則 ${0} 輸入值以進行過濾",
	"rangeTo": "至",
	"rangeTemplate": "從 ${0} 至 ${1}",
	"statusTipHeaderColumn": "直欄",
	"statusTipHeaderCondition": "規則",
	"statusTipTitle": "過濾列",
	"statusTipMsg": "按一下這裡的過濾列，在 ${0} 的值進行過濾。",
	"anycolumn": "全部直欄",
	"statusTipTitleNoFilter": "過濾列",
	"statusTipTitleHasFilter": "過濾器",
	"statusTipRelPre": "符合",
	"statusTipRelPost": "規則",
	"statusTipHeaderAll": "符合全部規則。",
	"statusTipHeaderAny": "任意相符規則。",
	"defaultItemsName": "項目",
	"filterBarMsgHasFilterTemplate": "已顯示 ${1} ${2} 的 ${0}。",
	"filterBarMsgNoFilterTemplate": "無已套用的過濾器",
	"filterBarDefButton": "定義過濾器",
	"waiFilterBarDefButton": "過濾表格",
	"a11yFilterBarDefButton": "過濾器...",
	"filterBarClearButton": "清除過濾器",
	"waiFilterBarClearButton": "清除過濾器",
	"closeFilterBarBtn": "關閉過濾列",
	"clearFilterMsg": "此將移除過慮器以及顯示全部可用的記錄。",
	"anyColumnOption": "全部直欄",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "True 值",
	"radioFalseLabel": "False 值",
	"beginTimeRangeLabel": "時間範圍起始值",
	"endTimeRangeLabel": "時間範圍結束值",
	"beginDateRangeLabel": "日期範圍起始值",
	"endDateRangeLabel": "日期範圍結束值",
	"startsWithExpr": "${0}*"
})
);

