define({     
//Body
	loadingInfo: "Učitavanje...",
	emptyInfo: "Nema stavki za prikaz",
	loadFailInfo: "Učitavanje podataka nije uspjelo!",
	loadMore: "Učitaj više",
	loadMoreLoading: "Učitavanje...",
	loadPrevious: "Učitaj prethodno",
	loadPreviousLoading: "Učitavanje...",

//FilterBar
	"clearFilterDialogTitle": "Brisanje filtera",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Filter nije primijenjen.",
	"defineFilter": "Definiraj filter",
	"conditionEqual": "jednako",
	"conditionNotEqual": "nije jednako",
	"conditionLess": "je manje od",
	"conditionLessEqual": "manje ili jednako",
	"conditionGreater": "je veće od",
	"conditionGreaterEqual": "veće ili jednako",
	"conditionContain": "sadrži",
	"conditionIs": "je",
	"conditionStartWith": "počinje sa",
	"conditionEndWith": "završava sa",
	"conditionNotContain": "ne sadrži",
	"conditionIsNot": "nije",
	"conditionNotStartWith": "ne počinje sa",
	"conditionNotEndWith": "ne završava sa",
	"conditionBefore": "prije",
	"conditionAfter": "poslije",
	"conditionRange": "raspon",
	"conditionIsEmpty": "je prazan",
	"all": "svi",
	"any": "bilo koji",
	"relationAll": "sva pravila",
	"waiRelAll": "Usporedi sva sljedeća pravila:",
	"relationAny": "bilo koje pravilo",
	"waiRelAny": "Usporedi bilo koje od sljedećih pravila:",
	"relationMsgFront": "Odgovara",
	"relationMsgTail": "",
	"and": "i",
	"or": "ili",
	"addRuleButton": "Bilo koje pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Ukloni pravilo",
	"waiRemoveRuleButtonTemplate": "Ukloni pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtera",
	"cancelButton": "Opoziv",
	"waiCancelButton": "Opoziv ovog dijaloga",
	"clearButton": "Obriši",
	"waiClearButton": "Obriši filter",
	"filterButton": "Filter",
	"waiFilterButton": "Predaj filter",
	"columnSelectLabel": "Stupac:",
	"waiColumnSelectTemplate": "Stupac za pravilo ${0}",
	"conditionSelectLabel": "Uvjet:",
	"waiConditionSelectTemplate": "Uvjet za pravilo ${0}",
	"valueBoxLabel": "Vrijednost:",
	"waiValueBoxTemplate": "Unesite vrijednost filtera za pravilo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Stupac",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Traka filtera",
	"statusTipMsg": "Kliknite traku filtera za filtriranje po vrijednostima u ${0}.",
	"anycolumn": "bilo koji stupac",
	"statusTipTitleNoFilter": "Traka filtera",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Odgovara",
	"statusTipRelPost": "pravila.",
	"statusTipHeaderAll": "Usporedi sva pravila.",
	"statusTipHeaderAny": "Usporedi bilo koja pravila.",
	"defaultItemsName": "stavke",
	"filterBarMsgHasFilterTemplate": "${0} od ${1} ${2} prikazano.",
	"filterBarMsgNoFilterTemplate": "Filter nije primijenjen",
	"filterBarDefButton": "Definiraj filter",
	"waiFilterBarDefButton": "Filtriraj tablicu",
	"a11yFilterBarDefButton": "Filtriraj...",
	"filterBarClearButton": "Obriši filter",
	"waiFilterBarClearButton": "Obriši filter",
	"closeFilterBarBtn": "Zatvori traku filtera",
	"clearFilterMsg": "Ovo uklanja filter i prikazuje sve raspoložive slogove.",
	"anyColumnOption": "Bilo koji stupac",
	"trueLabel": "Istinito",
	"falseLabel": "Lažno",
	"radioTrueLabel": "Vrijednost istinito",
	"radioFalseLabel": "Vrijednost lažno",
	"beginTimeRangeLabel": "Početna vrijednost vremenskog raspona",
	"endTimeRangeLabel": "Završna vrijednost vremenskog raspona",
	"beginDateRangeLabel": "Početna vrijednost raspona datuma",
	"endDateRangeLabel": "Završna vrijednost raspona datuma",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Jedan sort",
	nestedSort: "Ugniježđeni sort",
	ascending: "Kliknite za uzlazno sortiranje",
	descending: "Kliknite za silazno sortiranje",
	sortingState: "${0} - ${1}",
	unsorted: "Ne sortiraj ovaj stupac",
	waiSingleSortLabel: "${0} - sortiranje po ${1}. Izaberite sortiranje po ${2}",
	waiNestedSortLabel:"${0} - ugniježđeno sortiranje po ${1}. Izaberite ugniježđeno sortiranje po ${2}",

//PaginationBar
	pagerWai: 'Dojavljivač',

	pageIndex: '${0}',
	pageIndexTitle: 'Stranica ${0}',

	firstPageTitle: 'Prva stranica',
	prevPageTitle: 'Prethodna stranica',
	nextPageTitle: 'Sljedeća stranica',
	lastPageTitle: 'Posljednja stranica',

	pageSize: '${0}',
	pageSizeTitle: '${0} stavki po stranici',
	pageSizeAll: 'Sve',
	pageSizeAllTitle: 'Sve stavke',

	description: '${0} - ${1} od ${2} stavki.',
	descriptionEmpty: 'Mreža je prazna.',

	summary: 'Ukupno: ${0}',
	summaryWithSelection: 'Ukupno: ${0} Izabrano: ${1}',

	gotoBtnTitle: 'Idi na određenu stranicu',

	gotoDialogTitle: 'Idi na stranicu',
	gotoDialogMainMsg: 'Navedite broj stranice:',
	gotoDialogPageCount: '(${0} stranica)',
	gotoDialogOKBtn: 'Idi',
	gotoDialogCancelBtn: 'Opoziv',
	// for drop down pagination bar
	pageLabel: 'Stranica',
	pageSizeLabel: 'Redovi',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Brisanje filtera',
	buildFilterMenuLabel: 'Izgradi filter&hellip;',
	apply: 'Primijeni filter',

//Sort
	helpMsg: '${0} - Kliknite za sortiranje ili upotrijebite control-klik za dodavanje u sortiranje',
	singleHelpMsg: '${0} - Kliknite za sortiranje',
	priorityOrder: 'prioritet sortiranja ${0}',

//SummaryBar
	summaryTotal: 'Ukupno: ${0}',
	summarySelected: 'Izabrano: ${0}',
	summaryRange: 'Raspon: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Pritisnite razmaknicu za izbor svih.",	//need translation
	indirectDeselectAll: "Pritisnite razmaknicu za poništavanje izbora svih.",	//need translation
	treeExpanded: "Control + strelica lijevo za skupljanje ovog reda.",	//need translation
	treeCollapsed: "Control + strelica desno za proširivanje ovog reda."	//need translation
});

