//>>built
define("dojox/drawing/stencil/_Base","dojo,dojo/fx/easing,../util/oo,../annotations/BoxShadow,../annotations/Angle,../annotations/Label,../defaults".split(","),function(c,p,i,q,r,s,t){i=i.declare(function(a){c.mixin(this,a);this.style=a.style||t.copy();if(a.stencil)this.stencil=a.stencil,this.util=a.stencil.util,this.mouse=a.stencil.mouse,this.container=a.stencil.container,this.style=a.stencil.style;this.shortType=this.util.abbr(this.type);this.isText=/Text/.test(this.type);this.isLine=/Line|Vector|Axes|Arrow/.test(this.type);
this.renderHit=this.style.renderHitLayer;if(!this.renderHit&&this.style.renderHitLines&&this.isLine)this.renderHit=!0;if(!this.renderHit&&this.style.useSelectedStyle){this.useSelectedStyle=!0;this.selCopy=c.clone(this.style.selected);for(var b in this.style.norm)void 0===this.style.selected[b]&&(this.style.selected[b]=this.style.norm[b]);this.textSelected=c.clone(this.style.text);this.textSelected.color=this.style.selected.fill}this.angleSnap=this.style.angleSnap||1;this.marginZero=a.marginZero||
this.style.anchors.marginZero;this.id=a.id||this.util.uid(this.type);this._cons=[];!this.annotation&&!this.subShape&&this.util.attr(this.container,"id",this.id);this.connect(this,"onBeforeRender","preventNegativePos");this._offX=this.mouse.origin.x;this._offY=this.mouse.origin.y;if(this.isText)this.align=a.align||this.align,this.valign=a.valign||this.valign,a.data&&a.data.makeFit?(b=this.makeFit(a.data.text,a.data.width),this.textSize=this.style.text.size=b.size,this._lineHeight=b.box.h):(this.textSize=
parseInt(this.style.text.size,10),this._lineHeight=1.4*this.textSize),this.deleteEmptyCreate=void 0!==a.deleteEmptyCreate?a.deleteEmptyCreate:this.style.text.deleteEmptyCreate,this.deleteEmptyModify=void 0!==a.deleteEmptyModify?a.deleteEmptyModify:this.style.text.deleteEmptyModify;this.attr(a.data);if(!this.noBaseRender){if(a.points){if(a.data&&!1===a.data.closePath)this.closePath=!1;this.setPoints(a.points);this.connect(this,"render",this,"onRender",!0);this.baseRender&&this.enabled&&this.render();
a.label&&this.setLabel(a.label);a.shadow&&this.addShadow(a.shadow)}else if(a.data)a.data.width=a.data.width?a.data.width:this.style.text.minWidth,a.data.height=a.data.height?a.data.height:this._lineHeight,this.setData(a.data),this.connect(this,"render",this,"onRender",!0),this.baseRender&&this.enabled&&this.render(a.data.text),this.baseRender&&a.label&&this.setLabel(a.label),this.baseRender&&a.shadow&&this.addShadow(a.shadow);else if(this.draws)this.points=[],this.data={},this.connectMouse(),this._postRenderCon=
c.connect(this,"render",this,"_onPostRender");if(this.showAngle)this.angleLabel=new r({stencil:this});this.enabled||(this.disable(),this.moveToBack(),this.render(a.data.text))}},{type:"dojox.drawing.stencil",minimumSize:10,enabled:!0,drawingType:"stencil",setData:function(a){this.data=a;this.points=this.dataToPoints()},setPoints:function(a){this.points=a;if(this.pointsToData)this.data=this.pointsToData()},onDelete:function(){},onBeforeRender:function(){},onModify:function(){},onChangeData:function(){},
onChangeText:function(){},onRender:function(){this._postRenderCon=c.connect(this,"render",this,"_onPostRender");this.created=!0;this.disconnectMouse();this.shape?this.shape.superClass=this:this.container.superClass=this;this._setNodeAtts(this)},onChangeStyle:function(){this._isBeingModified=!0;this.enabled?(this.style.current=this.style.norm,this.style.currentHit=this.style.hitNorm,this.style.currentText=this.style.text):(this.style.current=this.style.disabled,this.style.currentText=this.style.textDisabled,
this.style.currentHit=this.style.hitNorm);if(this.selected){if(this.useSelectedStyle)this.style.current=this.style.selected,this.style.currentText=this.textSelected;this.style.currentHit=this.style.hitSelected}else if(this.highlighted)this.style.currentHit=this.style.hitHighlighted;this.render()},animate:function(a){console.warn("ANIMATE..........................");var b=a.d||a.duration||1E3,f=a.ms||20,h=a.ease||p.linear,l=(new Date).getTime(),d=0,e=!0,g,j;c.isArray(a.start)?(g=a.start,j=a.end):c.isObject(a.start)?
(g=a.start,j=a.end,e=!1):console.warn("No data provided to animate");var i=setInterval(c.hitch(this,function(){var a=(new Date).getTime()-l,f=h(1-a/b);if(a>b||100<d++)clearInterval(i);else if(e){var o=[];c.forEach(g,function(a,b){o.push({x:(j[b].x-g[b].x)*f+g[b].x,y:(j[b].y-g[b].y)*f+g[b].y})});this.setPoints(o);this.render()}else{var a={},m;for(m in g)a[m]=(j[m]-g[m])*f+g[m];this.attr(a)}}),f)},attr:function(a,b){var f=this.enabled?this.style.norm:this.style.disabled,h=this.enabled?this.style.text:
this.style.textDisabled,l=this.textSelected||{},d,e,g,j=c.toJson(f),i=c.toJson(h),k={x:!0,y:!0,r:!0,height:!0,width:!0,radius:!0,angle:!0},n=!1;"object"!=typeof a?(d={},d[a]=b):d=c.clone(a);if(d.width)g=d.width,delete d.width;for(e in d){e in f&&(f[e]=d[e]);e in h&&(h[e]=d[e]);e in l&&(l[e]=d[e]);if(e in k)if(k[e]=d[e],n=!0,"radius"==e&&void 0===d.angle)d.angle=k.angle=this.getAngle();else if("angle"==e&&void 0===d.radius)d.radius=k.radius=this.getRadius();"text"==e&&this.setText(d.text);"label"==
e&&this.setLabel(d.label)}if(void 0!==d.borderWidth)f.width=d.borderWidth;if(this.useSelectedStyle){for(e in this.style.norm)void 0===this.selCopy[e]&&(this.style.selected[e]=this.style.norm[e]);this.textSelected.color=this.style.selected.color}if(this.created){if(void 0!==d.x||void 0!==d.y){l=this.getBounds(!0);k={dx:0,dy:0};for(e in d)if("x"==e||"y"==e||"r"==e)k["d"+e]=d[e]-l[e];this.transformPoints(k)}e=this.points;if(void 0!==d.angle)this.dataToPoints({x:this.data.x1,y:this.data.y1,angle:d.angle,
radius:d.radius});else if(void 0!==g)e[1].x=e[2].x=e[0].x+g,this.pointsToData(e);if(void 0!==d.height&&void 0===d.angle)e[2].y=e[3].y=e[0].y+d.height,this.pointsToData(e);if(void 0!==d.r)this.data.r=Math.max(0,d.r);if(n||i!=c.toJson(h)||j!=c.toJson(f))this.onChangeStyle(this);d.width=g;if(void 0!=d.cosphi)!this.data?this.data={cosphi:d.cosphi}:this.data.cosphi=d.cosphi,this.style.zAxis=0!=d.cosphi?!0:!1}},exporter:function(){var a=this.type.substring(this.type.lastIndexOf(".")+1).charAt(0).toLowerCase()+
this.type.substring(this.type.lastIndexOf(".")+2),b=c.clone(this.style.norm);b.borderWidth=b.width;delete b.width;"path"==a?b.points=this.points:b=c.mixin(b,this.data);b.type=a;if(this.isText)b.text=this.getText(),b=c.mixin(b,this.style.text),delete b.minWidth,delete b.deleteEmptyCreate,delete b.deleteEmptyModify;if(a=this.getLabel())b.label=a;return b},disable:function(){this.renderHit=this.enabled=!1;this.onChangeStyle(this)},enable:function(){this.renderHit=this.enabled=!0;this.onChangeStyle(this)},
select:function(){this.selected=!0;this.onChangeStyle(this)},deselect:function(a){a?setTimeout(c.hitch(this,function(){this.selected=!1;this.onChangeStyle(this)}),200):(this.selected=!1,this.onChangeStyle(this))},_toggleSelected:function(){this.selected&&(this.deselect(),setTimeout(c.hitch(this,"select"),0))},highlight:function(){this.highlighted=!0;this.onChangeStyle(this)},unhighlight:function(){this.highlighted=!1;this.onChangeStyle(this)},moveToFront:function(){this.container&&this.container.moveToFront()},
moveToBack:function(){this.container&&this.container.moveToBack()},onTransformBegin:function(){this._isBeingModified=!0},onTransformEnd:function(){this._isBeingModified=!1;this.onModify(this)},onTransform:function(){if(!this._isBeingModified)this.onTransformBegin();this.setPoints(this.points);this.render()},transformPoints:function(a){if(a.dx||a.dy){var b=c.clone(this.points),f=!1;c.forEach(this.points,function(b){b.x+=a.dx;b.y+=a.dy;if(b.x<this.marginZero||b.y<this.marginZero)f=!0});f?(this.points=
b,console.error("Attempt to set object '"+this.id+"' to less than zero.")):(this.onTransform(),this.onTransformEnd())}},applyTransform:function(a){this.transformPoints(a)},setTransform:function(a){this.attr({x:a.dx,y:a.dy})},getTransform:function(){return this.selected?this.container.getParent().getTransform():{dx:0,dy:0}},addShadow:function(a){a=!0===a?{}:a;a.stencil=this;this.shadow=new q(a)},removeShadow:function(){this.shadow.destroy()},setLabel:function(a){this._label?void 0!=a&&this._label.setLabel(a):
this._label=new s.Label({text:a,util:this.util,mouse:this.mouse,stencil:this,annotation:!0,container:this.container,labelPosition:this.labelPosition})},getLabel:function(){return this._label?this._label.getText():null},getAngle:function(){var a=this.pointsToData(),a=this.util.angle({start:{x:a.x1,y:a.y1},x:a.x2,y:a.y2},this.angleSnap);0>a&&(a=360+a);return a},getRadius:function(){var a=this.getBounds(!0);return this.util.length({start:{x:a.x1,y:a.y1},x:a.x2,y:a.y2})},getBounds:function(a){var b=this.points,
f,c;return 2==b.length?(a?(a=b[0].x,f=b[0].y,c=b[1].x,b=b[1].y):(a=b[0].x<b[1].x?b[0].x:b[1].x,f=b[0].y<b[1].y?b[0].y:b[1].y,c=b[0].x<b[1].x?b[1].x:b[0].x,b=b[0].y<b[1].y?b[1].y:b[0].y),{x1:a,y1:f,x2:c,y2:b,x:a,y:f,w:c-a,h:b-f}):{x1:b[0].x,y1:b[0].y,x2:b[2].x,y2:b[2].y,x:b[0].x,y:b[0].y,w:b[2].x-b[0].x,h:b[2].y-b[0].y}},preventNegativePos:function(){if(!this._isBeingModified&&this.points&&this.points.length){if("dojox.drawing.tools.custom.Axes"==this.type){var a=this.marginZero,b=this.marginZero;
c.forEach(this.points,function(b){a=Math.min(b.y,a)});c.forEach(this.points,function(a){b=Math.min(a.x,b)});a<this.marginZero&&c.forEach(this.points,function(b){b.y+=this.marginZero-a},this);b<this.marginZero&&c.forEach(this.points,function(a){a.x+=this.marginZero-b},this)}else c.forEach(this.points,function(a){a.x=0>a.x?this.marginZero:a.x;a.y=0>a.y?this.marginZero:a.y});this.setPoints(this.points)}},_onPostRender:function(){if(this._isBeingModified)this.onModify(this),this._isBeingModified=!1;if(!this.editMode&&
!this.selected&&this._prevData&&c.toJson(this._prevData)!=c.toJson(this.data))this.onChangeData(this),this._prevData=c.clone(this.data);else if(!this._prevData&&(!this.isText||this.getText()))this._prevData=c.clone(this.data)},_setNodeAtts:function(a){this.util.attr(a,"drawingType",this.enabled&&(!this.annotation||"label"==this.drawingType)?this.drawingType:"")},destroy:function(){if(!this.destroyed){if(this.data||this.points&&this.points.length)this.onDelete(this);this.disconnectMouse();this.disconnect(this._cons);
c.disconnect(this._postRenderCon);this.remove(this.shape,this.hit);this.destroyed=!0}},remove:function(){var a=arguments;if(!a.length){if(!this.shape)return;a=[this.shape]}for(var b=0;b<a.length;b++)a[b]&&a[b].removeShape()},connectMult:function(){1<arguments.length?this._cons.push(this.connect.apply(this,arguments)):c.isArray(arguments[0][0])?c.forEach(arguments[0],function(a){this._cons.push(this.connect.apply(this,a))},this):this._cons.push(this.connect.apply(this,arguments[0]))},connect:function(a,
b,f,h,i){var d;if("object"!=typeof a)f?(h=f,f=b,b=a,a=this):(h=b,b=a,a=f=this);else if(h){if(i)return d=c.connect(a,b,function(a){c.hitch(f,h)(a);c.disconnect(d)}),this._cons.push(d),d}else h=f,f=this;d=c.connect(a,b,f,h);this._cons.push(d);return d},disconnect:function(a){a&&(c.isArray(a)||(a=[a]),c.forEach(a,c.disconnect,c))},connectMouse:function(){this._mouseHandle=this.mouse.register(this)},disconnectMouse:function(){this.mouse.unregister(this._mouseHandle)},render:function(){},dataToPoints:function(){},
pointsToData:function(){},onDown:function(){this._downOnCanvas=!0;c.disconnect(this._postRenderCon);this._postRenderCon=null},onMove:function(){},onDrag:function(){},onUp:function(){}});c.setObject("dojox.drawing.stencil._Base",i);return i});