//>>built
define("dijit/_editor/plugins/FontChoice","dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/i18n,dojo/_base/lang,dojo/store/Memory,../../registry,../../_Widget,../../_TemplatedMixin,../../_WidgetsInTemplateMixin,../../form/FilteringSelect,../_Plugin,../range,dojo/i18n!../nls/FontChoice".split(","),function(h,g,p,q,i,r,s,e,t,u,v,k,l){var e=g("dijit._editor.plugins._FontDropDown",[e,t,u],{label:"",plainText:!1,templateString:"<span style='white-space: nowrap' class='dijit dijitReset dijitInline'><label class='dijitLeft dijitInline' for='${selectId}'>${label}</label><input data-dojo-type='dijit.form.FilteringSelect' required='false' data-dojo-props='labelType:\"html\", labelAttr:\"label\", searchAttr:\"name\"' tabIndex='-1' id='${selectId}' data-dojo-attach-point='select' value=''/></span>",
postMixInProperties:function(){this.inherited(arguments);this.strings=q.getLocalization("dijit._editor","FontChoice");this.label=this.strings[this.command];this.id=s.getUniqueId(this.declaredClass.replace(/\./g,"_"));this.selectId=this.id+"_select";this.inherited(arguments)},postCreate:function(){this.select.set("store",new r({idProperty:"value",data:h.map(this.values,function(b){var a=this.strings[b]||b;return{label:this.getLabel(b,a),name:a,value:b}},this)}));this.select.set("value","",!1);this.disabled=
this.select.get("disabled")},_setValueAttr:function(b,a){a=!1!==a;this.select.set("value",0>h.indexOf(this.values,b)?"":b,a);if(!a)this.select._lastValueReported=null},_getValueAttr:function(){return this.select.get("value")},focus:function(){this.select.focus()},_setDisabledAttr:function(b){this.disabled=b;this.select.set("disabled",b)}}),m=g("dijit._editor.plugins._FontNameDropDown",e,{generic:!1,command:"fontName",postMixInProperties:function(){if(!this.values)this.values=this.generic?["serif",
"sans-serif","monospace","cursive","fantasy"]:["Arial","Times New Roman","Comic Sans MS","Courier New"];this.inherited(arguments)},getLabel:function(b,a){return this.plainText?a:"<div style='font-family: "+b+"'>"+a+"</div>"},_setValueAttr:function(b,a){this.generic&&(b={Arial:"sans-serif",Helvetica:"sans-serif",Myriad:"sans-serif",Times:"serif","Times New Roman":"serif","Comic Sans MS":"cursive","Apple Chancery":"cursive",Courier:"monospace","Courier New":"monospace",Papyrus:"fantasy","Estrangelo Edessa":"cursive",
Gabriola:"fantasy"}[b]||b);this.inherited(arguments,[b,!1!==a])}}),n=g("dijit._editor.plugins._FontSizeDropDown",e,{command:"fontSize",values:[1,2,3,4,5,6,7],getLabel:function(b,a){return this.plainText?a:"<font size="+b+"'>"+a+"</font>"},_setValueAttr:function(b,a){a=!1!==a;b.indexOf&&-1!=b.indexOf("px")&&(b={10:1,13:2,16:3,18:4,24:5,32:6,48:7}[parseInt(b,10)]||b);this.inherited(arguments,[b,a])}}),o=g("dijit._editor.plugins._FormatBlockDropDown",e,{command:"formatBlock",values:"noFormat,p,h1,h2,h3,pre".split(","),
postCreate:function(){this.inherited(arguments);this.set("value","noFormat",!1)},getLabel:function(b,a){return this.plainText||"noFormat"==b?a:"<"+b+">"+a+"</"+b+">"},_execCommand:function(b,a,d){if("noFormat"===d){var c;if((a=l.getSelection(b.window))&&0<a.rangeCount){var d=a.getRangeAt(0),e;if(d){a=d.startContainer;for(c=d.endContainer;a&&a!==b.editNode&&a!==b.document.body&&1!==a.nodeType;)a=a.parentNode;for(;c&&c!==b.editNode&&c!==b.document.body&&1!==c.nodeType;)c=c.parentNode;var j=i.hitch(this,
function(a,c){if(a.childNodes&&a.childNodes.length){var d;for(d=0;d<a.childNodes.length;d++){var f=a.childNodes[d];if(1==f.nodeType&&b._sCall("inSelection",[f])){var e=f.tagName?f.tagName.toLowerCase():"";-1!==h.indexOf(this.values,e)&&c.push(f);j(f,c)}}}}),d=i.hitch(this,function(a){if(a&&a.length){for(b.beginEditing();a.length;)this._removeFormat(b,a.pop());b.endEditing()}}),f=[];if(a==c){var g;for(c=a;c&&c!==b.editNode&&c!==b.document.body;){if(1==c.nodeType&&(e=c.tagName?c.tagName.toLowerCase():
"",-1!==h.indexOf(this.values,e))){g=c;break}c=c.parentNode}j(a,f);g&&(f=[g].concat(f))}else for(c=a;b._sCall("inSelection",[c]);)1==c.nodeType&&(e=c.tagName?c.tagName.toLowerCase():"",-1!==h.indexOf(this.values,e)&&f.push(c),j(c,f)),c=c.nextSibling;d(f);b.onDisplayChanged()}}}else b.execCommand(a,d)},_removeFormat:function(b,a){if(b.customUndo){for(;a.firstChild;)p.place(a.firstChild,a,"before");a.parentNode.removeChild(a)}else{b._sCall("selectElementChildren",[a]);var d=b._sCall("getSelectedHtml",
[]);b._sCall("selectElement",[a]);b.execCommand("inserthtml",d||"")}}}),f=g("dijit._editor.plugins.FontChoice",k,{useDefaultCommand:!1,_initButton:function(){var b={fontName:m,fontSize:n,formatBlock:o}[this.command],a=this.params;if(this.params.custom)a.values=this.params.custom;var d=this.editor;this.button=new b(i.delegate({dir:d.dir,lang:d.lang},a));this.connect(this.button.select,"onChange",function(a){this.editor.focus();"fontName"==this.command&&-1!=a.indexOf(" ")&&(a="'"+a+"'");this.button._execCommand?
this.button._execCommand(this.editor,this.command,a):this.editor.execCommand(this.command,a)})},updateState:function(){var b=this.editor,a=this.command;if(b&&b.isLoaded&&a.length&&this.button){var d=this.get("disabled");this.button.set("disabled",d);if(!d){var c;try{c=b.queryCommandValue(a)||""}catch(f){c=""}(d=i.isString(c)&&c.match(/'([^']*)'/))&&(c=d[1]);if("formatBlock"===a)if(!c||"p"==c){c=null;var e;if((a=l.getSelection(this.editor.window))&&0<a.rangeCount)if(a=a.getRangeAt(0))e=a.endContainer;
for(;e&&e!==b.editNode&&e!==b.document;){if((a=e.tagName?e.tagName.toLowerCase():"")&&-1<h.indexOf(this.button.values,a)){c=a;break}e=e.parentNode}c||(c="noFormat")}else 0>h.indexOf(this.button.values,c)&&(c="noFormat");c!==this.button.get("value")&&this.button.set("value",c,!1)}}}});h.forEach(["fontName","fontSize","formatBlock"],function(b){k.registry[b]=function(a){return new f({command:b,plainText:a.plainText})}});f._FontDropDown=e;f._FontNameDropDown=m;f._FontSizeDropDown=n;f._FormatBlockDropDown=
o;return f});