define({
//Body
	loadingInfo: "Bezig met laden...",
	emptyInfo: "Geen items om af te beelden",
	loadFailInfo: "Gegevens kunnen niet worden geladen!",
	loadMore: "Meer laden",
	loadMoreLoading: "Bezig met laden...",
	loadPrevious: "Vorige laden",
	loadPreviousLoading: "Bezig met laden...",

//FilterBar
	"clearFilterDialogTitle": "Filter wissen",
	"filterDefDialogTitle": "Filteren",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Geen filter toegepast.",
	"defineFilter": "Filter definiëren",
	"conditionEqual": "gelijk aan",
	"conditionNotEqual": "niet gelijk aan",
	"conditionLess": "is kleiner dan",
	"conditionLessEqual": "kleiner dan of gelijk aan",
	"conditionGreater": "is groter dan",
	"conditionGreaterEqual": "groter dan of gelijk aan",
	"conditionContain": "bevat",
	"conditionIs": "is",
	"conditionStartWith": "begint met",
	"conditionEndWith": "eindigt op",
	"conditionNotContain": "bevat niet",
	"conditionIsNot": "is niet",
	"conditionNotStartWith": "begint niet met",
	"conditionNotEndWith": "eindigt niet op",
	"conditionBefore": "voor",
	"conditionAfter": "na",
	"conditionRange": "bereik",
	"conditionIsEmpty": "is leeg",
	"all": "alle",
	"any": "een of meer",
	"relationAll": "alle regels",
	"waiRelAll": "Voldoen aan al deze regels:",
	"relationAny": "een of meer regels",
	"waiRelAny": "Voldoen aan een van deze regels:",
	"relationMsgFront": "Overeenkomst",
	"relationMsgTail": "",
	"and": "en",
	"or": "of",
	"addRuleButton": "Regel toevoegen",
	"waiAddRuleButton": "Een nieuwe regel toevoegen",
	"removeRuleButton": "Regel verwijderen",
	"waiRemoveRuleButtonTemplate": "Regel ${0} verwijderen",
	"addRuleButton": "Filterregel toevoegen",
	"cancelButton": "Annuleren",
	"waiCancelButton": "Dit dialoogvenster annuleren",
	"clearButton": "Leegmaken",
	"waiClearButton": "Het filter wissen",
	"filterButton": "Filteren",
	"waiFilterButton": "Het filter verzenden",
	"columnSelectLabel": "Kolom",
	"waiColumnSelectTemplate": "Kolom voor regel ${0}",
	"conditionSelectLabel": "Voorwaarde",
	"waiConditionSelectTemplate": "Voorwaarde voor regel ${0}",
	"valueBoxLabel": "Waarde",
	"waiValueBoxTemplate": "Geef een filterwaarde op voor regel ${0}",
	"rangeTo": "tot",
	"rangeTemplate": "van ${0} tot ${1}",
	"statusTipHeaderColumn": "Kolom",
	"statusTipHeaderCondition": "Regels",
	"statusTipTitle": "Filterbalk",
	"statusTipMsg": "Klik hier op de filterbalk om te filteren op waarden in ${0}.",
	"anycolumn": "een kolom",
	"statusTipTitleNoFilter": "Filterbalk",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Overeenkomst",
	"statusTipRelPost": "regels.",
	"statusTipHeaderAll": "Voldoen aan alle regels.",
	"statusTipHeaderAny": "Voldoen aan een regel.",
	"defaultItemsName": "items",
	"filterBarMsgHasFilterTemplate": "${0} van ${1} ${2} afgebeeld.",
	"filterBarMsgNoFilterTemplate": "Geen filter toegepast",
	"filterBarDefButton": "Filter definiëren",
	"waiFilterBarDefButton": "De tabel filteren",
	"a11yFilterBarDefButton": "Filteren...",
	"filterBarClearButton": "Filter wissen",
	"waiFilterBarClearButton": "Het filter wissen",
	"closeFilterBarBtn": "Filterbalk sluiten",
	"clearFilterMsg": "Hiermee verwijdert u het filter en worden alle beschikbare records afgebeeld.",
	"anyColumnOption": "Een kolom",
	"trueLabel": "Waar",
	"falseLabel": "Onwaar",
	"radioTrueLabel": "Waarde waar",
	"radioFalseLabel": "Waarde onwaar",
	"beginTimeRangeLabel": "Beginwaarde tijdbereik",
	"endTimeRangeLabel": "Eindwaarde tijdbereik",
	"beginDateRangeLabel": "Beginwaarde datumbereik",
	"endDateRangeLabel": "Eindwaarde datumbereik",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Enkelvoudig sorteren",
	nestedSort: "Genest sorteren",
	ascending: "Klik om oplopend te sorteren",
	descending: "Klik om aflopend te sorteren",
	sortingState: "${0} - ${1}",
	unsorted: "Deze kolom niet sorteren",
	waiSingleSortLabel: "${0} - is gesorteerd op ${1}. Nu sorteren op ${2}",
	waiNestedSortLabel:"${0} - is genest gesorteerd op ${1}. Nu genest sorteren op ${2}",

//PaginationBar
	pagerWai: 'Pager',

	pageIndex: '${0}',
	pageIndexTitle: 'Pagina ${0}',

	firstPageTitle: 'Eerste pagina',
	prevPageTitle: 'Vorige pagina',
	nextPageTitle: 'Volgende pagina',
	lastPageTitle: 'Laatste pagina',

	pageSize: '${0}',
	pageSizeTitle: '${0} items per pagina',
	pageSizeAll: 'Alle',
	pageSizeAllTitle: 'Alle items',

	description: '${0} - ${1} van ${2} items.',
	descriptionEmpty: 'Raster is leeg.',

	summary: 'Totaal: ${0}',
	summaryWithSelection: 'Totaal: ${0} Geselecteerd: ${1}',

	gotoBtnTitle: 'Naar een specifieke pagina gaan',

	gotoDialogTitle: 'Naar pagina gaan',
	gotoDialogMainMsg: 'Geef het paginanummer op:',
	gotoDialogPageCount: ' (${0} pagina\'s)',
	gotoDialogOKBtn: 'Go',
	gotoDialogCancelBtn: 'Annuleren',
	// for drop down pagination bar
	pageLabel: 'Pagina',
	pageSizeLabel: 'Rijen',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Filter wissen',
	buildFilterMenuLabel: 'Filter bouwen&hellip;',
	apply: 'Filter toepassen',

//SummaryBar
	summary: 'Totaal: ${0}',
	summaryWithSelection: 'Totaal: ${0} Geselecteerd: ${1}'
});
