define({
//Body
	loadingInfo: "Загрузка...",
	emptyInfo: "Нет ни одного элемента",
	loadFailInfo: "Не удалось загрузить данные!",
	loadMore: "Загрузить еще",
	loadMoreLoading: "Загрузка...",
	loadPrevious: "Загрузить предыдущие",
	loadPreviousLoading: "Загрузка...",

//FilterBar
	"clearFilterDialogTitle": "Удалить фильтр",
	"filterDefDialogTitle": "Фильтр",
	"defaultRuleTitle": "Правило",
	"ruleTitleTemplate": "Правило ${ruleNumber}",
	"noFilterApplied": "Фильтр не применен.",
	"defineFilter": "Задать фильтр",
	"conditionEqual": "равно",
	"conditionNotEqual": "не равно",
	"conditionLess": "меньше, чем",
	"conditionLessEqual": "меньше или равно",
	"conditionGreater": "больше, чем",
	"conditionGreaterEqual": "больше или равно",
	"conditionContain": "содержит",
	"conditionIs": "является",
	"conditionStartWith": "начинается с",
	"conditionEndWith": "заканчивается на",
	"conditionNotContain": "не содержит",
	"conditionIsNot": "не является",
	"conditionNotStartWith": "не начинается с",
	"conditionNotEndWith": "не заканчивается на",
	"conditionBefore": "до",
	"conditionAfter": "после",
	"conditionRange": "диапазон",
	"conditionIsEmpty": "пустое",
	"all": "все",
	"any": "любой",
	"relationAll": "все правила",
	"waiRelAll": "Соответствие всем следующим правилам:",
	"relationAny": "любое правило",
	"waiRelAny": "Соответствие любому из следующих правил:",
	"relationMsgFront": "Сопоставить",
	"relationMsgTail": "",
	"and": "и",
	"or": "или",
	"addRuleButton": "Добавить правило",
	"waiAddRuleButton": "Добавить новое правило",
	"removeRuleButton": "Удалить правило",
	"waiRemoveRuleButtonTemplate": "Удалить правило ${0}",
	"addRuleButton": "Добавить правило фильтра",
	"cancelButton": "Отмена",
	"waiCancelButton": "Отменить этот диалог",
	"clearButton": "Удалить",
	"waiClearButton": "Удалить фильтр",
	"filterButton": "Фильтр",
	"waiFilterButton": "Передать фильтр",
	"columnSelectLabel": "Столбец",
	"waiColumnSelectTemplate": "Столбец для правила ${0}",
	"conditionSelectLabel": "Условие",
	"waiConditionSelectTemplate": "Условие для правила ${0}",
	"valueBoxLabel": "Значение",
	"waiValueBoxTemplate": "Задайте значение фильтра для правила ${0}",
	"rangeTo": "до",
	"rangeTemplate": "от ${0} до ${1}",
	"statusTipHeaderColumn": "Столбец",
	"statusTipHeaderCondition": "Правила",
	"statusTipTitle": "Панель фильтра",
	"statusTipMsg": "Щелкните по панели фильтра, чтобы применить фильтр к значениям в ${0}.",
	"anycolumn": "любой столбец",
	"statusTipTitleNoFilter": "Панель фильтра",
	"statusTipTitleHasFilter": "Фильтр",
	"statusTipRelPre": "Сопоставить",
	"statusTipRelPost": "правил.",
	"statusTipHeaderAll": "Соответствие всем правилам.",
	"statusTipHeaderAny": "Соответствие любому из правил.",
	"defaultItemsName": "элементов",
	"filterBarMsgHasFilterTemplate": "Показано ${0} из ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Фильтр не применен",
	"filterBarDefButton": "Задать фильтр",
	"waiFilterBarDefButton": "Применить фильтр к таблице",
	"a11yFilterBarDefButton": "Фильтр...",
	"filterBarClearButton": "Удалить фильтр",
	"waiFilterBarClearButton": "Удалить фильтр",
	"closeFilterBarBtn": "Закрыть панель фильтра",
	"clearFilterMsg": "Фильтр будет удален, и будут показаны все записи.",
	"anyColumnOption": "Любой столбец",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "Значение True",
	"radioFalseLabel": "Значение False",
	"beginTimeRangeLabel": "Начало значений диапазона времени",
	"endTimeRangeLabel": "Конец значений диапазона времени",
	"beginDateRangeLabel": "Начало значений диапазона дат",
	"endDateRangeLabel": "Конец значений диапазона дат",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Простая сортировка",
	nestedSort: "Вложенная сортировка",
	ascending: "Щелкните для сортировки по восходящей",
	descending: "Щелкните для сортировки по нисходящей",
	sortingState: "${0} - ${1}",
	unsorted: "Не сортировать этот столбец",
	waiSingleSortLabel: "${0} - рассортирован на основе элемента ${1}. Выберите сортировку на основе элемента ${2}",
	waiNestedSortLabel:"${0} - вложен с сортировкой на основе элемента ${1}. Выберите вложенную сортировку на основе элемента ${2}",

//PaginationBar
	pagerWai: 'Пейджер',

	pageIndex: '${0}',
	pageIndexTitle: 'Страница ${0}',

	firstPageTitle: 'Первая страница',
	prevPageTitle: 'Предыдущая страница',
	nextPageTitle: 'Следующая страница',
	lastPageTitle: 'Последняя страница',

	pageSize: '${0}',
	pageSizeTitle: '${0} элементов на странице',
	pageSizeAll: 'Все',
	pageSizeAllTitle: 'Все элементы',

	description: '${0} - ${1} из ${2} элементов.',
	descriptionEmpty: 'Таблица пустая.',

	summary: 'Всего: ${0}',
	summaryWithSelection: 'Всего: ${0} Выбрано: ${1}',

	gotoBtnTitle: 'Перейти на конкретную страницу',

	gotoDialogTitle: 'Перейти на страницу',
	gotoDialogMainMsg: 'Укажите номер страницы:',
	gotoDialogPageCount: '(${0} страниц)',
	gotoDialogOKBtn: 'Перейти',
	gotoDialogCancelBtn: 'Отмена',
	// for drop down pagination bar
	pageLabel: 'Страница',
	pageSizeLabel: 'Число строк',

//QuickFilter
	filterLabel: 'Фильтр',
	clearButtonTitle: 'Удалить фильтр',
	buildFilterMenuLabel: 'Потроить фильтр&hellip;',
	apply: 'Применить фильтр',

//SummaryBar
	summary: 'Всего: ${0}',
	summaryWithSelection: 'Всего: ${0} Выбрано: ${1}'
});
