define({      
//begin v1.x content
	"clearFilterDialogTitle": "Tøm filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Ikke brukt filter.",
	"defineFilter": "Definer filter",
	"conditionEqual": "er lik",
	"conditionNotEqual": "er ikke lik",
	"conditionLess": "er mindre enn",
	"conditionLessEqual": "mindre enn eller lik",
	"conditionGreater": "er større enn",
	"conditionGreaterEqual": "større enn eller lik",
	"conditionContain": "inneholder",
	"conditionIs": "er",
	"conditionStartWith": "starter med",
	"conditionEndWith": "slutter med",
	"conditionNotContain": "inneholder ikke",
	"conditionIsNot": "er ikke",
	"conditionNotStartWith": "starter ikke med",
	"conditionNotEndWith": "slutter ikke med",
	"conditionBefore": "før",
	"conditionAfter": "etter",
	"conditionRange": "område",
	"conditionIsEmpty": "er tom",
	"all": "alle",
	"any": "minst en",
	"relationAll": "alle regler",
	"waiRelAll": "Samsvar med alle disse reglene:",
	"relationAny": "minst en regel",
	"waiRelAny": "Samsvar med minst en av disse reglene:",
	"relationMsgFront": "Samsvar",
	"relationMsgTail": "",
	"and": "og",
	"or": "eller",
	"addRuleButton": "Legg til regel",
	"waiAddRuleButton": "Legg til en ny regel",
	"removeRuleButton": "Fjern regel",
	"waiRemoveRuleButtonTemplate": "Fjern regel ${0}",
	"addRuleButton": "Legg til filterregel",
	"cancelButton": "Avbryt",
	"waiCancelButton": "Avbryt denne dialogboksen",
	"clearButton": "Tøm",
	"waiClearButton": "Tøm filteret",
	"filterButton": "Filtrer",
	"waiFilterButton": "Send filteret",
	"columnSelectLabel": "Kolonne",
	"waiColumnSelectTemplate": "Kolonne for regel ${0}",
	"conditionSelectLabel": "Betingelse",
	"waiConditionSelectTemplate": "Betingelse for regel ${0}",
	"valueBoxLabel": "Verdi",
	"waiValueBoxTemplate": "Oppgi verdi som skal filtreres for regel ${0}",
	"rangeTo": "til",
	"rangeTemplate": "fra ${0} til ${1}",
	"statusTipHeaderColumn": "Kolonne",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filterlinje",
	"statusTipMsg": "Klikk på filterlinjen her for å filtrere på verdiene i ${0}.",
	"anycolumn": "enhver kolonne",
	"statusTipTitleNoFilter": "Filterlinje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Samsvar med",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Samsvar med alle reglene.",
	"statusTipHeaderAny": "Samsvar med minst en av reglene.",
	"defaultItemsName": "elementer",
	"filterBarMsgHasFilterTemplate": "${0} av ${1} ${2} vist.",
	"filterBarMsgNoFilterTemplate": "Ikke brukt filter",
	"filterBarDefButton": "Definer filter",
	"waiFilterBarDefButton": "Filtrer tabellen",
	"a11yFilterBarDefButton": "Filtrer...",
	"filterBarClearButton": "Tøm filter",
	"waiFilterBarClearButton": "Tøm filteret",
	"closeFilterBarBtn": "Lukk filterlinjen",
	"clearFilterMsg": "Dette fjerner filteret og viser alle tilgjengelige poster.",
	"anyColumnOption": "Minst en kolonne",
	"trueLabel": "Sann",
	"falseLabel": "Usann",
	"radioTrueLabel": "Verdi sann",
	"radioFalseLabel": "Verdi usann",
	"beginTimeRangeLabel": "Startverdi for tidsperiode",
	"endTimeRangeLabel": "Sluttverdi for tidsperiode",
	"beginDateRangeLabel": "Startverdi for datoperiode",
	"endDateRangeLabel": "Sluttverdi for datoperiode",
	"startsWithExpr": "${0}*"
//end v1.x content
});

