define({
//Body
	loadingInfo: "Încărcare...",
	emptyInfo: "Nu există articole de afişat",
	loadFailInfo: "Încărcarea datelor a eşuat!",
	loadMore: "Încărcare mai multe",
	loadMoreLoading: "Încărcare...",
	loadPrevious: "Încărcare anterioare",
	loadPreviousLoading: "Încărcare...",

//FilterBar
	"clearFilterDialogTitle": "Ştergere filtru",
	"filterDefDialogTitle": "Filtru",
	"defaultRuleTitle": "Regulă",
	"ruleTitleTemplate": "Regulă ${ruleNumber}",
	"noFilterApplied": "Nu este aplicat niciun filtru.",
	"defineFilter": "Definire filtru",
	"conditionEqual": "egal",
	"conditionNotEqual": "nu este egal",
	"conditionLess": "este mai mic decât",
	"conditionLessEqual": "mai mic sau egal",
	"conditionGreater": "este mai mare decât",
	"conditionGreaterEqual": "mai mare sau egal",
	"conditionContain": "conţine",
	"conditionIs": "este",
	"conditionStartWith": "începe cu",
	"conditionEndWith": "se termină cu",
	"conditionNotContain": "nu conţine",
	"conditionIsNot": "nu este",
	"conditionNotStartWith": "nu începe cu",
	"conditionNotEndWith": "nu se termină cu",
	"conditionBefore": "înaintea",
	"conditionAfter": "după",
	"conditionRange": "interval",
	"conditionIsEmpty": "este gol",
	"all": "toate",
	"any": "oricare",
	"relationAll": "toate regulile",
	"waiRelAll": "Răspundeţi tuturor regulilor următoare:",
	"relationAny": "oricare reguli",
	"waiRelAny": "Răspundeţi oricărei dintre regulile următoare:",
	"relationMsgFront": "Răspuns",
	"relationMsgTail": "",
	"and": "şi",
	"or": "sau",
	"addRuleButton": "Adăugare regulă",
	"waiAddRuleButton": "Adăugare regulă nouă",
	"removeRuleButton": "Înlăturare regulă",
	"waiRemoveRuleButtonTemplate": "Înlăturare regulă ${0}",
	"addRuleButton": "Adăugare regulă filtru",
	"cancelButton": "Anulare",
	"waiCancelButton": "Anulaţi acest dialog",
	"clearButton": "Ştergere",
	"waiClearButton": "Ştergeţi filtrul",
	"filterButton": "Filtru",
	"waiFilterButton": "Lansaţi în execuţie filtrul",
	"columnSelectLabel": "Coloană",
	"waiColumnSelectTemplate": "Coloană pentru regulă ${0}",
	"conditionSelectLabel": "Condiţie",
	"waiConditionSelectTemplate": "Condiţie pentru regula ${0}",
	"valueBoxLabel": "Valoare",
	"waiValueBoxTemplate": "Introduceţi valoarea pentru filtrarea pentru regulă ${0}",
	"rangeTo": "la",
	"rangeTemplate": "din ${0} la ${1}",
	"statusTipHeaderColumn": "Coloană",
	"statusTipHeaderCondition": "Reguli",
	"statusTipTitle": "Bară de filtru",
	"statusTipMsg": "Faceţi clic pe bara de filtru aici pentru a filtra valorile în ${0}.",
	"anycolumn": "orice coloană",
	"statusTipTitleNoFilter": "Bară de filtru",
	"statusTipTitleHasFilter": "Filtru",
	"statusTipRelPre": "Răspuns",
	"statusTipRelPost": "reguli.",
	"statusTipHeaderAll": "Potrivire cu toate regulile.",
	"statusTipHeaderAny": "Potrivire cu orice regulă.",
	"defaultItemsName": "articole",
	"filterBarMsgHasFilterTemplate": "${0} din ${1} ${2} afişate.",
	"filterBarMsgNoFilterTemplate": "Niciun filtru nu este aplicat",
	"filterBarDefButton": "Definire filtru",
	"waiFilterBarDefButton": "Filtrare tabelă",
	"a11yFilterBarDefButton": "Filtru...",
	"filterBarClearButton": "Ştergere filtru",
	"waiFilterBarClearButton": "Ştergeţi filtrul",
	"closeFilterBarBtn": "Închidere bară de filtru",
	"clearFilterMsg": "Aceasta va înlătura filtrul şi va afişa toate înregistrările disponibile.",
	"anyColumnOption": "Orice coloană",
	"trueLabel": "Adevărat",
	"falseLabel": "Fals",
	"radioTrueLabel": "Valoare Adevărat",
	"radioFalseLabel": "Valoare Fals",
	"beginTimeRangeLabel": "Valoare de început interval timp",
	"endTimeRangeLabel": "Valoare de sfârşit interval timp",
	"beginDateRangeLabel": "Valoare de început interval dată",
	"endDateRangeLabel": "Valoare de sfârşit interval dată",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Sortare unică",
	nestedSort: "Sortare imbricată",
	ascending: "Faceţi clic pentru sortare Crescătoare",
	descending: "Faceţi clic pentru sortare Descrescătoare",
	sortingState: "${0} - ${1}",
	unsorted: "Să nu fie sortară această coloană",
	waiSingleSortLabel: "${0} - este sortată după ${1}. Alegeţi sortarea după ${2}",
	waiNestedSortLabel:"${0} - este sortată imbricat după ${1}. Alegeţi sortarea imbricată după ${2}",

//PaginationBar
	pagerWai: 'Paginator',
	pageIndex: '${0}',
	pageIndexTitle: 'Pagina ${0}',
	firstPageTitle: 'Prima pagină',
	prevPageTitle: 'Pagina anterioară',
	nextPageTitle: 'Pagina următoare',
	lastPageTitle: 'Ultima pagină',
	pageSize: '${0}',
	pageSizeTitle: '${0} articole pe pagină',
	pageSizeAll: 'Toate',
	pageSizeAllTitle: 'Toate articolele',
	description: '${0} - ${1} din ${2} articole.',
	descriptionEmpty: 'Grila este goală.',
	// OneUI blueprint
	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Selectate: ${1}',
	gotoBtnTitle: 'Deplasare la o pagină anumită',
	gotoDialogTitle: 'Deplasare la pagină',
	gotoDialogMainMsg: 'Specificaţi numărul de pagină:',
	gotoDialogPageCount: '(${0} pagini)',
	gotoDialogOKBtn: 'Deplasare',
	gotoDialogCancelBtn: 'Anulare',
	// for drop down pagination bar
	pageLabel: 'Pagina',
	pageSizeLabel: 'Rânduri',

//QuickFilter
	filterLabel: 'Filtru',
	clearButtonTitle: 'Ştergere filtru',
	buildFilterMenuLabel: 'Construire filtru&hellip;',
	apply: 'Aplicare filtru',

//SummaryBar
	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Selectate: ${1}'
});
