define({      
//begin v1.x content
	"clearFilterDialogTitle": "Tyhjennä suodatin",
	"filterDefDialogTitle": "Suodatin",
	"defaultRuleTitle": "Sääntö",
	"ruleTitleTemplate": "Sääntö ${ruleNumber}",
	"noFilterApplied": "Mikään suodatin ei ole käytössä.",
	"defineFilter": "Määritä suodatin",
	"conditionEqual": "yhtä suuri kuin",
	"conditionNotEqual": "ei ole yhtä suuri kuin",
	"conditionLess": "on pienempi kuin",
	"conditionLessEqual": "pienempi tai yhtä suuri kuin",
	"conditionGreater": "on suurempi kuin",
	"conditionGreaterEqual": "suurempi tai yhtä suuri kuin",
	"conditionContain": "sisältää",
	"conditionIs": "on",
	"conditionStartWith": "alussa on",
	"conditionEndWith": "lopussa on",
	"conditionNotContain": "ei sisällä",
	"conditionIsNot": "ei ole",
	"conditionNotStartWith": "alussa ei ole",
	"conditionNotEndWith": "lopussa ei ole",
	"conditionBefore": "ennen",
	"conditionAfter": "jälkeen",
	"conditionRange": "vaihtelualue",
	"conditionIsEmpty": "on tyhjä",
	"all": "kaikki",
	"any": "mikä tahansa",
	"relationAll": "kaikki säännöt",
	"waiRelAll": "Täsmäytä kaikki seuraavat säännöt:",
	"relationAny": "mitkä tahansa säännöt",
	"waiRelAny": "Täsmäytä mitkä tahansa seuraavista säännöistä:",
	"relationMsgFront": "Vastine",
	"relationMsgTail": "",
	"and": "ja",
	"or": "tai",
	"addRuleButton": "Lisää sääntö",
	"waiAddRuleButton": "Lisää uusi sääntö",
	"removeRuleButton": "Poista sääntö",
	"waiRemoveRuleButtonTemplate": "Poista sääntö ${0}",
	"addRuleButton": "Lisää suodatussääntö",
	"cancelButton": "Peruuta",
	"waiCancelButton": "Peruuta keskustelu",
	"clearButton": "Tyhjennä",
	"waiClearButton": "Tyhjennä suodatin",
	"filterButton": "Suodata",
	"waiFilterButton": "Lähetä suodatin",
	"columnSelectLabel": "Sarake",
	"waiColumnSelectTemplate": "Säännön ${0} sarake",
	"conditionSelectLabel": "Ehto",
	"waiConditionSelectTemplate": "Säännön ${0} ehto",
	"valueBoxLabel": "Arvo",
	"waiValueBoxTemplate": "Syötä säännön ${0} suodatettava arvo",
	"rangeTo": "kohde",
	"rangeTemplate": "lähde ${0}, kohde ${1}",
	"statusTipHeaderColumn": "Sarake",
	"statusTipHeaderCondition": "Säännöt",
	"statusTipTitle": "Suodatinpalkki",
	"statusTipMsg": "Napsauta suodatinpalkkia kohteen ${0} arvojen suodattamiseksi.",
	"anycolumn": "mikä tahansa sarake",
	"statusTipTitleNoFilter": "Suodatinpalkki",
	"statusTipTitleHasFilter": "Suodatin",
	"statusTipRelPre": "Vastine",
	"statusTipRelPost": "säännöt.",
	"statusTipHeaderAll": "Täsmäytä kaikki säännöt.",
	"statusTipHeaderAny": "Täsmäytä mitkä tahansa säännöt.",
	"defaultItemsName": "nimikkeet",
	"filterBarMsgHasFilterTemplate": "näkyvissä ${0} / ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Mikään suodatin ei ole käytössä",
	"filterBarDefButton": "Määritä suodatin",
	"waiFilterBarDefButton": "Suodata taulukko",
	"a11yFilterBarDefButton": "Suodata...",
	"filterBarClearButton": "Tyhjennä suodatin",
	"waiFilterBarClearButton": "Tyhjennä suodatin",
	"closeFilterBarBtn": "Sulje suodatinpalkki",
	"clearFilterMsg": "Tämä toimenpide poistaa suodattimen ja näyttää kaikki saatavilla olevat tallenteet.",
	"anyColumnOption": "Mikä tahansa sarake",
	"trueLabel": "Tosi",
	"falseLabel": "Epätosi",
	"radioTrueLabel": "Arvo tosi",
	"radioFalseLabel": "Arvo epätosi",
	"beginTimeRangeLabel": "Aikajakson alkuarvo",
	"endTimeRangeLabel": "Aikajakson lopetusarvo",
	"beginDateRangeLabel": "Päivämäärävälin alkuarvo",
	"endDateRangeLabel": "Päivämäärävälin loppuarvo",
	"startsWithExpr": "${0}*"
//end v1.x content
});

