define(
({
	"clearFilterDialogTitle": "Filter löschen",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Kein Filter angewendet",
	"defineFilter": "Filter definieren",
	"conditionEqual": "gleich",
	"conditionNotEqual": "ist nicht gleich",
	"conditionLess": "ist kleiner als",
	"conditionLessEqual": "kleiner-gleich",
	"conditionGreater": "ist größer als",
	"conditionGreaterEqual": "größer-gleich",
	"conditionContain": "enthält",
	"conditionIs": "ist",
	"conditionStartWith": "beginnt mit",
	"conditionEndWith": "endet mit",
	"conditionNotContain": "enthält nicht",
	"conditionIsNot": "ist nicht",
	"conditionNotStartWith": "beginnt nicht mit",
	"conditionNotEndWith": "endet nicht mit",
	"conditionBefore": "vor",
	"conditionAfter": "nach",
	"conditionRange": "Bereich",
	"conditionIsEmpty": "ist leer",
	"all": "alle",
	"any": "beliebig",
	"relationAll": "Alle Regeln",
	"waiRelAll": "Übereinstimmung mit allen folgenden Regeln:",
	"relationAny": "Beliebige Regeln",
	"waiRelAny": "Übereinstimmung mit einer beliebigen der folgenden Regeln:",
	"relationMsgFront": "Übereinstimmung",
	"relationMsgTail": "",
	"and": "und",
	"or": "oder",
	"addRuleButton": "Regel hinzufügen",
	"waiAddRuleButton": "Neue Regel hinzufügen",
	"removeRuleButton": "Regel entfernen",
	"waiRemoveRuleButtonTemplate": "Regel ${0} entfernen",
	"addRuleButton": "Filterregel hinzufügen",
	"cancelButton": "Abbrechen",
	"waiCancelButton": "Dialog abbrechen",
	"clearButton": "Abwählen",
	"waiClearButton": "Filter abwählen",
	"filterButton": "Filter",
	"waiFilterButton": "Filter übergeben",
	"columnSelectLabel": "Spalte",
	"waiColumnSelectTemplate": "Spalte für Regel ${0}",
	"conditionSelectLabel": "Bedingung",
	"waiConditionSelectTemplate": "Bedingung für Regel ${0}",
	"valueBoxLabel": "Wert",
	"waiValueBoxTemplate": "Filterwert für Regel ${0} eingeben",
	"rangeTo": "bis",
	"rangeTemplate": "von ${0} bis ${1}",
	"statusTipHeaderColumn": "Spalte",
	"statusTipHeaderCondition": "Regeln",
	"statusTipTitle": "Filterleiste",
	"statusTipMsg": "Kicken Sie auf die Filterleiste, um nach Werten in ${0} zu filtern.",
	"anycolumn": "Beliebige Spalte",
	"statusTipTitleNoFilter": "Filterleiste",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Abgleich mit",
	"statusTipRelPost": "Regeln.",
	"statusTipHeaderAll": "Alle Regel abgleichen.",
	"statusTipHeaderAny": "Beliebige Regeln abgleichen.",
	"defaultItemsName": "Einträge",
	"filterBarMsgHasFilterTemplate": "${0} von ${1} ${2} angezeigt.",
	"filterBarMsgNoFilterTemplate": "Kein Filter angewendet",
	"filterBarDefButton": "Filter definieren",
	"waiFilterBarDefButton": "Tabelle filtern",
	"a11yFilterBarDefButton": "Filter...",
	"filterBarClearButton": "Filter löschen",
	"waiFilterBarClearButton": "Filter abwählen",
	"closeFilterBarBtn": "Filterleiste schließen",
	"clearFilterMsg": "Diese Aktion entfernt den Filter und zeigt alle verfügbaren Datensätze an.",
	"anyColumnOption": "Beliebige Spalte",
	"trueLabel": "Wahr",
	"falseLabel": "Falsch",
	"radioTrueLabel": "Wert wahr",
	"radioFalseLabel": "Wert falsch",
	"beginTimeRangeLabel": "Anfangswert des Zeitbereichs",
	"endTimeRangeLabel": "Endwert des Zeitbereichs",
	"beginDateRangeLabel": "Anfangswert des Datumsbereichs",
	"endDateRangeLabel": "Endwert des Datumsbereichs",
	"startsWithExpr": "${0}*"
})
);

