define({      
//begin v1.x content
	"clearFilterDialogTitle": "ล้างตัวกรอง",
	"filterDefDialogTitle": "ตัวกรอง",
	"defaultRuleTitle": "กฎ",
	"ruleTitleTemplate": "กฎ ${ruleNumber}",
	"noFilterApplied": "ไม่ได้ใช้ตัวกรอง",
	"defineFilter": "กำหนดตัวกรอง",
	"conditionEqual": "เท่ากัน",
	"conditionNotEqual": "ไม่เท่ากัน",
	"conditionLess": "น้อยกว่า",
	"conditionLessEqual": "น้อยกว่าหรือเท่ากัน",
	"conditionGreater": "มากกว่า",
	"conditionGreaterEqual": "มากกว่าหรือเท่ากัน",
	"conditionContain": "มี",
	"conditionIs": "เป็น",
	"conditionStartWith": "เริ่มต้นด้วย",
	"conditionEndWith": "สิ้นสุดด้วย",
	"conditionNotContain": "ไม่มี",
	"conditionIsNot": "ไม่เป็น",
	"conditionNotStartWith": "ไม่ได้เริ่มต้นด้วย",
	"conditionNotEndWith": "ไม่ได้สิ้นสุดด้วย",
	"conditionBefore": "ก่อน",
	"conditionAfter": "หลังจาก",
	"conditionRange": "ช่วง",
	"conditionIsEmpty": "ว่าง",
	"all": "ทั้งหมด",
	"any": "ใดๆ",
	"relationAll": "กฎทั้งหมด",
	"waiRelAll": "ตรงกับกฎทั้งหมดต่อไปนี้:",
	"relationAny": "กฎใดๆ",
	"waiRelAny": "ตรงกับกฎใดๆ ต่อไปนี้:",
	"relationMsgFront": "จับคู่",
	"relationMsgTail": "",
	"and": "และ",
	"or": "หรือ",
	"addRuleButton": "เพิ่มกฎ",
	"waiAddRuleButton": "เพิ่มกฎใหม่",
	"removeRuleButton": "ลบกฎ",
	"waiRemoveRuleButtonTemplate": "ลบกฎ ${0}",
	"addRuleButton": "เพิ่มกฎตัวกรอง",
	"cancelButton": "ยกเลิก",
	"waiCancelButton": "ยกเลิกไดอะล็อกนี้",
	"clearButton": "ล้าง",
	"waiClearButton": "ล้างตัวกรอง",
	"filterButton": "ตัวกรอง",
	"waiFilterButton": "ส่งตัวกรอง",
	"columnSelectLabel": "คอลัมน์",
	"waiColumnSelectTemplate": "คอลัมน์สำหรับกฎ ${0}",
	"conditionSelectLabel": "เงื่อนไข",
	"waiConditionSelectTemplate": "เงื่อนไขสำหรับกฎ ${0}",
	"valueBoxLabel": "ค่า",
	"waiValueBoxTemplate": "ป้อนค่าตัวกรองสำหรับกฎ ${0}",
	"rangeTo": "ถึง",
	"rangeTemplate": "จาก ${0} ถึง ${1}",
	"statusTipHeaderColumn": "คอลัมน์",
	"statusTipHeaderCondition": "กฎ",
	"statusTipTitle": "แถบตัวกรอง",
	"statusTipMsg": "คลิกแถบตัวกรองที่นี่เพื่อกรองค่าใน ${0}",
	"anycolumn": "คอลัมน์ใดๆ",
	"statusTipTitleNoFilter": "แถบตัวกรอง",
	"statusTipTitleHasFilter": "ตัวกรอง",
	"statusTipRelPre": "จับคู่",
	"statusTipRelPost": "กฎ",
	"statusTipHeaderAll": "ตรงกับกฎทั้งหมด",
	"statusTipHeaderAny": "ตรงกับกฎใดๆ",
	"defaultItemsName": "ไอเท็ม",
	"filterBarMsgHasFilterTemplate": "${0} จาก ${1} ${2} แสดงขึ้น",
	"filterBarMsgNoFilterTemplate": "ไม่ได้ใช้ตัวกรอง",
	"filterBarDefButton": "กำหนดตัวกรอง",
	"waiFilterBarDefButton": "กรองตาราง",
	"a11yFilterBarDefButton": "กรอง...",
	"filterBarClearButton": "ล้างตัวกรอง",
	"waiFilterBarClearButton": "ล้างตัวกรอง",
	"closeFilterBarBtn": "ปิดแถบตัวกรอง",
	"clearFilterMsg": "สิ่งนี้จะลบตัวกรองและแสดงเร็กคอร์ดที่มีอยู่ทั้งหมด",
	"anyColumnOption": "คอลัมน์ใดๆ",
	"trueLabel": "จริง",
	"falseLabel": "เท็จ",
	"radioTrueLabel": "ค่าจริง",
	"radioFalseLabel": "ค่าเท็จ",
	"beginTimeRangeLabel": "ค่าเริ่มต้นช่วงเวลา",
	"endTimeRangeLabel": "ค่าสิ้นสุดช่วงเวลา",
	"beginDateRangeLabel": "ค่าเริ่มต้นช่วงวันที่",
	"endDateRangeLabel": "ค่าสิ้นสุดช่วงวันที่",
	"startsWithExpr": "${0}*"
//end v1.x content
});

