define({
//Body
	loadingInfo: "กำลังโหลด...",
	emptyInfo: "ไม่มีไอเท็มแสดง",
	loadFailInfo: "ล้มเหลวในการโหลดข้อมูล!",
	loadMore: "โหลดเพิ่มเติม   ",
	loadMoreLoading: "กำลังโหลด...",
	loadPrevious: "โหลดก่อนหน้า",
	loadPreviousLoading: "กำลังโหลด...",

//FilterBar
	"clearFilterDialogTitle": "ล้างตัวกรอง",
	"filterDefDialogTitle": "ตัวกรอง",
	"defaultRuleTitle": "กฎ",
	"ruleTitleTemplate": "กฎ ${ruleNumber}",
	"noFilterApplied": "ไม่ได้ใช้ตัวกรอง",
	"defineFilter": "กำหนดตัวกรอง",
	"conditionEqual": "เท่ากัน",
	"conditionNotEqual": "ไม่เท่ากัน",
	"conditionLess": "น้อยกว่า",
	"conditionLessEqual": "น้อยกว่าหรือเท่ากัน",
	"conditionGreater": "มากกว่า",
	"conditionGreaterEqual": "มากกว่าหรือเท่ากัน",
	"conditionContain": "มี",
	"conditionIs": "เป็น",
	"conditionStartWith": "เริ่มต้นด้วย",
	"conditionEndWith": "สิ้นสุดด้วย",
	"conditionNotContain": "ไม่มี",
	"conditionIsNot": "ไม่เป็น",
	"conditionNotStartWith": "ไม่ได้เริ่มต้นด้วย",
	"conditionNotEndWith": "ไม่ได้สิ้นสุดด้วย",
	"conditionBefore": "ก่อน",
	"conditionAfter": "หลังจาก",
	"conditionRange": "ช่วง",
	"conditionIsEmpty": "ว่าง",
	"all": "ทั้งหมด",
	"any": "ใดๆ",
	"relationAll": "กฎทั้งหมด",
	"waiRelAll": "ตรงกับกฎทั้งหมดต่อไปนี้:",
	"relationAny": "กฎใดๆ",
	"waiRelAny": "ตรงกับกฎใดๆ ต่อไปนี้:",
	"relationMsgFront": "จับคู่",
	"relationMsgTail": "",
	"and": "และ",
	"or": "หรือ",
	"addRuleButton": "เพิ่มกฎ",
	"waiAddRuleButton": "เพิ่มกฎใหม่",
	"removeRuleButton": "ลบกฎ",
	"waiRemoveRuleButtonTemplate": "ลบกฎ ${0}",
	"addRuleButton": "เพิ่มกฎตัวกรอง",
	"cancelButton": "ยกเลิก",
	"waiCancelButton": "ยกเลิกไดอะล็อกนี้",
	"clearButton": "ล้าง",
	"waiClearButton": "ล้างตัวกรอง",
	"filterButton": "ตัวกรอง",
	"waiFilterButton": "ส่งตัวกรอง",
	"columnSelectLabel": "คอลัมน์",
	"waiColumnSelectTemplate": "คอลัมน์สำหรับกฎ ${0}",
	"conditionSelectLabel": "เงื่อนไข",
	"waiConditionSelectTemplate": "เงื่อนไขสำหรับกฎ ${0}",
	"valueBoxLabel": "ค่า",
	"waiValueBoxTemplate": "ป้อนค่าตัวกรองสำหรับกฎ ${0}",
	"rangeTo": "ถึง",
	"rangeTemplate": "จาก ${0} ถึง ${1}",
	"statusTipHeaderColumn": "คอลัมน์",
	"statusTipHeaderCondition": "กฎ",
	"statusTipTitle": "แถบตัวกรอง",
	"statusTipMsg": "คลิกแถบตัวกรองที่นี่เพื่อกรองค่าใน ${0}",
	"anycolumn": "คอลัมน์ใดๆ",
	"statusTipTitleNoFilter": "แถบตัวกรอง",
	"statusTipTitleHasFilter": "ตัวกรอง",
	"statusTipRelPre": "จับคู่",
	"statusTipRelPost": "กฎ",
	"statusTipHeaderAll": "ตรงกับกฎทั้งหมด",
	"statusTipHeaderAny": "ตรงกับกฎใดๆ",
	"defaultItemsName": "ไอเท็ม",
	"filterBarMsgHasFilterTemplate": "${0} จาก ${1} ${2} แสดงขึ้น",
	"filterBarMsgNoFilterTemplate": "ไม่ได้ใช้ตัวกรอง",
	"filterBarDefButton": "กำหนดตัวกรอง",
	"waiFilterBarDefButton": "กรองตาราง",
	"a11yFilterBarDefButton": "กรอง...",
	"filterBarClearButton": "ล้างตัวกรอง",
	"waiFilterBarClearButton": "ล้างตัวกรอง",
	"closeFilterBarBtn": "ปิดแถบตัวกรอง",
	"clearFilterMsg": "สิ่งนี้จะลบตัวกรองและแสดงเร็กคอร์ดที่มีอยู่ทั้งหมด",
	"anyColumnOption": "คอลัมน์ใดๆ",
	"trueLabel": "จริง",
	"falseLabel": "เท็จ",
	"radioTrueLabel": "ค่าจริง",
	"radioFalseLabel": "ค่าเท็จ",
	"beginTimeRangeLabel": "ค่าเริ่มต้นช่วงเวลา",
	"endTimeRangeLabel": "ค่าสิ้นสุดช่วงเวลา",
	"beginDateRangeLabel": "ค่าเริ่มต้นช่วงวันที่",
	"endDateRangeLabel": "ค่าสิ้นสุดช่วงวันที่",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "การเรียงลำดับชั้นเดียว",
	nestedSort: "การเรียงลำดับที่มีกลุ่มย่อย",
	ascending: "คลิกเพื่อเรียงลำดับจากน้อยไปมาก",
	descending: "คลิกเพื่อเรียงลำดับจากมากไปน้อย",
	sortingState: "${0} - ${1}",
	unsorted: "อย่าเรียงลำดับคอลัมน์นี้",
	waiSingleSortLabel: "${0} - เรียงลำดับตาม ${1} เลือกเพื่อเรียงลำดับตาม ${2}",
	waiNestedSortLabel:"${0} - เรียงลำดับที่มีกลุ่มย่อยตาม ${1} เลือกเพื่อเรียงลำดับที่มีกลุ่มย่อยตาม ${2}",

//PaginationBar
	pagerWai: 'เพเจอร์',

	pageIndex: '${0}',
	pageIndexTitle: 'หน้า ${0}',

	firstPageTitle: 'หน้าแรก',
	prevPageTitle: 'หน้าก่อนหน้านี้',
	nextPageTitle: 'หน้าถัดไป',
	lastPageTitle: 'หน้าหลังสุด',

	pageSize: '${0}',
	pageSizeTitle: '${0} ไอเท็มต่อหน้า',
	pageSizeAll: 'ทั้งหมด',
	pageSizeAllTitle: 'ไอเท็มทั้งหมด',

	description: '${0} - ${1} จาก ${2} ไอเท็ม',
	descriptionEmpty: 'เส้นกริดว่าง',

	summary: 'ทั้งหมด: ${0}',
	summaryWithSelection: 'ทั้งหมด: ${0} ที่เลือก: ${1}',

	gotoBtnTitle: 'ไปยังหน้าที่ระบุ',

	gotoDialogTitle: 'ไปยังหน้า',
	gotoDialogMainMsg: 'ระบุหมายเลขหน้า:',
	gotoDialogPageCount: '(${0} หน้า)',
	gotoDialogOKBtn: 'ไป',
	gotoDialogCancelBtn: 'ยกเลิก',
	// for drop down pagination bar
	pageLabel: 'หน้า',
	pageSizeLabel: 'แถว',

//QuickFilter
	filterLabel: 'ตัวกรอง',
	clearButtonTitle: 'ล้างตัวกรอง',
	buildFilterMenuLabel: 'สร้างตัวกรอง&hellip;',
	apply: 'ใช้ตัวกรอง',

//SummaryBar
	summary: 'ทั้งหมด: ${0}',
	summaryWithSelection: 'ทั้งหมด: ${0} ที่เลือก: ${1}'
});
