//>>built
define("dojox/app/controllers/Transition","dojo/_base/lang,dojo/_base/declare,dojo/on,dojo/Deferred,dojo/when,dojox/css3/transit,../Controller".split(","),function(h,j,n,o,k,l,m){return j("dojox.app.controllers.Transition",m,{proceeding:!1,waitingQueue:[],constructor:function(a,c){this.events={transition:this.transition,startTransition:this.onStartTransition};this.inherited(arguments)},transition:function(a){this.proceedTransition(a)},onStartTransition:function(a){a.preventDefault&&a.preventDefault();
a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();var c=a.detail.target,f=/#(.+)/;!c&&f.test(a.detail.href)&&(c=a.detail.href.match(f)[1]);this.transition({viewId:c,opts:h.mixin({reverse:!1},a.detail)})},proceedTransition:function(a){if(this.proceeding)this.app.log("in app/controllers/Transition proceedTransition push event",a),this.waitingQueue.push(a);else{this.proceeding=!0;this.app.log("in app/controllers/Transition proceedTransition calling trigger load",a);var c=a.params||{};a.opts&&
a.opts.params&&(c=a.params||a.opts.params);this.app.trigger("load",{viewId:a.viewId,params:c,callback:h.hitch(this,function(){var f=this._doTransition(a.viewId,a.opts,c,this.app);k(f,h.hitch(this,function(){this.proceeding=!1;var a=this.waitingQueue.shift();a&&this.proceedTransition(a)}))})})}},_getDefaultTransition:function(a){for(var c=a.defaultTransition;!c&&a.parent;)a=a.parent,c=a.defaultTransition;return c},_doTransition:function(a,c,f,d){this.app.log("in app/controllers/Transition._doTransition transitionTo=[",
a,"], parent.name=[",d.name,"], opts=",c);if(!d)throw Error("view parent not found in transition.");var i,g,b,e=d.selectedChild,a=a?a.split(","):d.defaultView.split(",");i=a.shift();g=a.join(",");b=d.children[d.id+"_"+i];if(!b)throw Error("child view must be loaded before transition.");b.params=f||b.params;if(!g&&b.defaultView)g=b.defaultView;if(e){if(b!==e){for(a=e.selectedChild;a;)this.app.log("< in Transition._doTransition calling subChild.beforeDeactivate subChild name=[",a.name,"], parent.name=[",
a.parent.name,"], next!==current path"),a.beforeDeactivate(),a=a.selectedChild;this.app.log("< in Transition._doTransition calling current.beforeDeactivate current name=[",e.name,"], parent.name=[",e.parent.name,"], next!==current path");e.beforeDeactivate();this.app.log("> in Transition._doTransition calling next.beforeActivate next name=[",b.name,"], parent.name=[",b.parent.name,"], next!==current path");b.beforeActivate();this.app.log("> in Transition._doTransition calling app.triggger select view next name=[",
b.name,"], parent.name=[",b.parent.name,"], next!==current path");this.app.trigger("select",{parent:d,view:b});d=l(e.domNode,b.domNode,h.mixin({},c,{transition:this._getDefaultTransition(d)||"none"}));d.then(h.hitch(this,function(){for(var a=e.selectedChild;a;)this.app.log("  < in Transition._doTransition calling subChild.afterDeactivate subChild name=[",a.name,"], parent.name=[",a.parent.name,"], next!==current path"),a.afterDeactivate(),a=a.selectedChild;this.app.log("  < in Transition._doTransition calling current.afterDeactivate current name=[",
e.name,"], parent.name=[",e.parent.name,"], next!==current path");e.afterDeactivate();this.app.log("  > in Transition._doTransition calling next.afterActivate next name=[",b.name,"], parent.name=[",b.parent.name,"], next!==current path");b.afterActivate();g&&this._doTransition(g,c,f,b)}));return d}this.app.log("< in Transition._doTransition calling next.beforeDeactivate next name=[",b.name,"], parent.name=[",b.parent.name,"], next==current path");b.beforeDeactivate();this.app.log("  < in Transition._doTransition calling next.afterDeactivate next name=[",
b.name,"], parent.name=[",b.parent.name,"], next==current path");b.afterDeactivate();this.app.log("> in Transition._doTransition calling next.beforeActivate next name=[",b.name,"], parent.name=[",b.parent.name,"], next==current path");b.beforeActivate();this.app.log("  > in Transition._doTransition calling next.afterActivate next name=[",b.name,"], parent.name=[",b.parent.name,"], next==current path");b.afterActivate();this.app.log("> in Transition._doTransition calling app.triggger select view next name=[",
b.name,"], parent.name=[",b.parent.name,"], next==current path");this.app.trigger("select",{parent:d,view:b});if(g)return this._doTransition(g,c,f,b)}else this.app.log("> in Transition._doTransition calling next.beforeActivate next name=[",b.name,"], parent.name=[",b.parent.name,"],  !current path,"),b.beforeActivate(),this.app.log("> in Transition._doTransition calling next.afterActivate next name=[",b.name,"], parent.name=[",b.parent.name,"],  !current path"),b.afterActivate(),this.app.log("  > in Transition._doTransition calling app.triggger select view next name=[",
b.name,"], parent.name=[",b.parent.name,"], !current path"),this.app.trigger("select",{parent:d,view:b})}})});