define({      
//begin v1.x content
	"clearFilterDialogTitle": "Effacer le filtre",
	"filterDefDialogTitle": "Filtrer",
	"defaultRuleTitle": "Règle",
	"ruleTitleTemplate": "Règle ${ruleNumber}",
	"noFilterApplied": "Aucun filtre appliqué.",
	"defineFilter": "Définir le filtre",
	"conditionEqual": "égal",
	"conditionNotEqual": "est différent de",
	"conditionLess": "est inférieur à",
	"conditionLessEqual": "inférieur ou égal",
	"conditionGreater": "est supérieur à",
	"conditionGreaterEqual": "supérieur ou égal",
	"conditionContain": "contient",
	"conditionIs": "est",
	"conditionStartWith": "commence par",
	"conditionEndWith": "se termine par",
	"conditionNotContain": "ne contient pas",
	"conditionIsNot": "n'est pas",
	"conditionNotStartWith": "ne commence pas par",
	"conditionNotEndWith": "ne se termine pas par",
	"conditionBefore": "avant",
	"conditionAfter": "après",
	"conditionRange": "plage",
	"conditionIsEmpty": "est vide",
	"all": "tout",
	"any": "n'importe laquelle",
	"relationAll": "toutes les règles",
	"waiRelAll": "Satisfaire à toutes les règles suivantes :",
	"relationAny": "n'importe quelles règles",
	"waiRelAny": "Satisfaire à une quelconque des règles suivantes :",
	"relationMsgFront": "Correspondance",
	"relationMsgTail": "",
	"and": "et",
	"or": "ou",
	"addRuleButton": "Ajouter une règle",
	"waiAddRuleButton": "Ajouter une nouvelle règle",
	"removeRuleButton": "Supprimer la règle",
	"waiRemoveRuleButtonTemplate": "Supprimer la règle ${0}",
	"addRuleButton": "Ajouter une règle de filtre",
	"cancelButton": "Annuler",
	"waiCancelButton": "Annuler cette boîte de dialogue",
	"clearButton": "Effacer",
	"waiClearButton": "Effacer le filtre",
	"filterButton": "Filtrer",
	"waiFilterButton": "Soumettre le filtre",
	"columnSelectLabel": "Colonne",
	"waiColumnSelectTemplate": "Colonne pour la règle ${0}",
	"conditionSelectLabel": "Condition",
	"waiConditionSelectTemplate": "Condition pour la règle ${0}",
	"valueBoxLabel": "Valeur",
	"waiValueBoxTemplate": "Saisir la valeur à filtrer pour la règle ${0}",
	"rangeTo": "à",
	"rangeTemplate": "de ${0} à ${1}",
	"statusTipHeaderColumn": "Colonne",
	"statusTipHeaderCondition": "Règles",
	"statusTipTitle": "Barre de filtre",
	"statusTipMsg": "Cliquer sur la barre de filtre ici pour filtrer sur les valeurs de ${0}.",
	"anycolumn": "n'importe quelle colonne",
	"statusTipTitleNoFilter": "Barre de filtre",
	"statusTipTitleHasFilter": "Filtrer",
	"statusTipRelPre": "Correspondance",
	"statusTipRelPost": "règles.",
	"statusTipHeaderAll": "Satisfaire à toutes les règles.",
	"statusTipHeaderAny": "Satisfaire à une règle quelconque.",
	"defaultItemsName": "éléments",
	"filterBarMsgHasFilterTemplate": "${0} sur ${1} ${2} affichés.",
	"filterBarMsgNoFilterTemplate": "Aucun filtre appliqué",
	"filterBarDefButton": "Définir le filtre",
	"waiFilterBarDefButton": "Filtrer le tableau",
	"a11yFilterBarDefButton": "Filtrer...",
	"filterBarClearButton": "Effacer le filtre",
	"waiFilterBarClearButton": "Effacer le filtre",
	"closeFilterBarBtn": "Fermer la barre de filtre",
	"clearFilterMsg": "Cela supprimera le filtre et affichera tous les enregistrements disponibles.",
	"anyColumnOption": "N'importe quelle colonne",
	"trueLabel": "Vrai",
	"falseLabel": "Faux",
	"radioTrueLabel": "Valeur Vrai",
	"radioFalseLabel": "Valeur Faux",
	"beginTimeRangeLabel": "Valeur du début de la plage de temps",
	"endTimeRangeLabel": "Valeur de la fin de la plage de temps",
	"beginDateRangeLabel": "Valeur du début de la plage de dates",
	"endDateRangeLabel": "Valeur de la fin de la plage de dates",
	"startsWithExpr": "${0}*"
//end v1.x content
});

