define(
({
	"clearFilterDialogTitle": "محو ترشيح البيانات",
	"filterDefDialogTitle": "‏ترشيح البيانات‏",
	"defaultRuleTitle": "القاعدة",
	"ruleTitleTemplate": "قاعدة ${ruleNumber}",
	"noFilterApplied": "لم يتم تطبيق ترشيح البيانات.",
	"defineFilter": "تعريف ترشيح البيانات",
	"conditionEqual": "يساوي",
	"conditionNotEqual": "غير مساوي الى",
	"conditionLess": "‏أقل من‏",
	"conditionLessEqual": "أقل من أو يساوي",
	"conditionGreater": "‏أكبر من‏",
	"conditionGreaterEqual": "أكبر من أو يساوي",
	"conditionContain": "يحتوي",
	"conditionIs": "يكون",
	"conditionStartWith": "يبدأ بالحروف",
	"conditionEndWith": "ينتهي بالحروف",
	"conditionNotContain": "لا يتضمن",
	"conditionIsNot": "ليس",
	"conditionNotStartWith": "لا يبدأ بـ",
	"conditionNotEndWith": "لا ينتهي بـ",
	"conditionBefore": "قبل",
	"conditionAfter": "بعد",
	"conditionRange": "مدى",
	"conditionIsEmpty": "خالي",
	"all": "كل",
	"any": "أي",
	"relationAll": "كل القواعد",
	"waiRelAll": "مطابقة الكل للقواعد التالية:",
	"relationAny": "أي قواعد",
	"waiRelAny": "مطابقة أي من القواعد التالية:",
	"relationMsgFront": "مطابقة",
	"relationMsgTail": "",
	"and": "and",
	"or": "أو",
	"addRuleButton": "اضافة قاعدة",
	"waiAddRuleButton": "اضافة قاعدة جديدة",
	"removeRuleButton": "ازالة قاعدة",
	"waiRemoveRuleButtonTemplate": "ازالة قاعدة ${0}",
	"addRuleButton": "اضافة قاعدة ترشيح بيانات",
	"cancelButton": "الغاء الأمر",
	"waiCancelButton": "الغاء هذا الحوار",
	"clearButton": "محو",
	"waiClearButton": "محو ترشيح البيانات",
	"filterButton": "‏ترشيح البيانات‏",
	"waiFilterButton": "احالة ترشيح البيانات",
	"columnSelectLabel": "العمود",
	"waiColumnSelectTemplate": "العمود للقاعدة ${0}",
	"conditionSelectLabel": "الشرط",
	"waiConditionSelectTemplate": "الشرط للعمود ${0}",
	"valueBoxLabel": "قيمة",
	"waiValueBoxTemplate": "ادخال قيمة لترشيح بيانات القاعدة ${0}",
	"rangeTo": "الى",
	"rangeTemplate": "من ${0} الى ${1}",
	"statusTipHeaderColumn": "العمود",
	"statusTipHeaderCondition": "قواعد",
	"statusTipTitle": "خط ترشيح البيانات",
	"statusTipMsg": "اضغط خط ترشيح البيانات هنا لترشيح بيانات القيم في ${0}.",
	"anycolumn": "أي عمود",
	"statusTipTitleNoFilter": "خط ترشيح البيانات",
	"statusTipTitleHasFilter": "‏ترشيح البيانات‏",
	"statusTipRelPre": "مطابقة",
	"statusTipRelPost": "قواعد.",
	"statusTipHeaderAll": "مطابقة كل القواعد.",
	"statusTipHeaderAny": "مطابقة أية قواعد.",
	"defaultItemsName": "البنود",
	"filterBarMsgHasFilterTemplate": "${0} من ${1} ${2} عرض.",
	"filterBarMsgNoFilterTemplate": "لم يتم تطبيق ترشيح البيانات",
	"filterBarDefButton": "تعريف ترشيح البيانات",
	"waiFilterBarDefButton": "ترشيح بيانات الجدول",
	"a11yFilterBarDefButton": "ترشيح بيانات...",
	"filterBarClearButton": "محو ترشيح البيانات",
	"waiFilterBarClearButton": "محو ترشيح البيانات",
	"closeFilterBarBtn": "اغلاق خط ترشيح البيانات",
	"clearFilterMsg": "سيقوم هذا بازالة مرشح البيانات وعرض كل السجلات المتاحة.",
	"anyColumnOption": "أي عمود",
	"trueLabel": "True",
	"falseLabel": "خطأ",
	"radioTrueLabel": "قيمة True",
	"radioFalseLabel": "قيمة False",
	"beginTimeRangeLabel": "بداية قيمة مدى الوقت",
	"endTimeRangeLabel": "نهاية قيمة مدى الوقت",
	"beginDateRangeLabel": "بداية قيمة مدى التاريخ",
	"endDateRangeLabel": "نهاية قيمة مدى التاريخ",
	"startsWithExpr": "${0}*"
})
);

