define({     
//Body
	loadingInfo: "تحميل...",
	emptyInfo: "لا يوجد بنود ليتم عرضها",
	loadFailInfo: "لم يتم تحميل البيانات بنجاح!",
	loadMore: "المزيد من التحميل",
	loadMoreLoading: "تحميل...",
	loadPrevious: "تحميل السابق",
	loadPreviousLoading: "تحميل...",

//FilterBar
	"clearFilterDialogTitle": "محو ترشيح البيانات",
	"filterDefDialogTitle": "‏ترشيح البيانات‏",
	"defaultRuleTitle": "القاعدة",
	"ruleTitleTemplate": "قاعدة ${ruleNumber}",
	"noFilterApplied": "لم يتم تطبيق ترشيح البيانات.",
	"defineFilter": "تعريف ترشيح البيانات",
	"conditionEqual": "يساوي",
	"conditionNotEqual": "غير مساوي الى",
	"conditionLess": "‏أقل من‏",
	"conditionLessEqual": "أقل من أو يساوي",
	"conditionGreater": "‏أكبر من‏",
	"conditionGreaterEqual": "أكبر من أو يساوي",
	"conditionContain": "يحتوي",
	"conditionIs": "يكون",
	"conditionStartWith": "يبدأ بالحروف",
	"conditionEndWith": "ينتهي بالحروف",
	"conditionNotContain": "لا يتضمن",
	"conditionIsNot": "ليس",
	"conditionNotStartWith": "لا يبدأ بـ",
	"conditionNotEndWith": "لا ينتهي بـ",
	"conditionBefore": "قبل",
	"conditionAfter": "بعد",
	"conditionRange": "مدى",
	"conditionIsEmpty": "خالي",
	"all": "كل",
	"any": "أي",
	"relationAll": "كل القواعد",
	"waiRelAll": "مطابقة الكل للقواعد التالية:",
	"relationAny": "أي قاعدة",
	"waiRelAny": "مطابقة أي من القواعد التالية:",
	"relationMsgFront": "مطابقة",
	"relationMsgTail": "",
	"and": "and",
	"or": "أو",
	"addRuleButton": "اضافة قاعدة",
	"waiAddRuleButton": "اضافة قاعدة جديدة",
	"removeRuleButton": "ازالة قاعدة",
	"waiRemoveRuleButtonTemplate": "ازالة قاعدة ${0}",
	"addRuleButton": "اضافة قاعدة ترشيح بيانات",
	"cancelButton": "الغاء الأمر",
	"waiCancelButton": "الغاء هذا الحوار",
	"clearButton": "محو",
	"waiClearButton": "محو ترشيح البيانات",
	"filterButton": "‏ترشيح البيانات‏",
	"waiFilterButton": "احالة ترشيح البيانات",
	"columnSelectLabel": "عمود:",
	"waiColumnSelectTemplate": "العمود للقاعدة ${0}",
	"conditionSelectLabel": "الشرط:",
	"waiConditionSelectTemplate": "الشرط للعمود ${0}",
	"valueBoxLabel": "القيمة:",
	"waiValueBoxTemplate": "ادخال قيمة لترشيح بيانات القاعدة ${0}",
	"rangeTo": "الى",
	"rangeTemplate": "من ${0} الى ${1}",
	"statusTipHeaderColumn": "العمود",
	"statusTipHeaderCondition": "قواعد",
	"statusTipTitle": "خط ترشيح البيانات",
	"statusTipMsg": "اضغط خط ترشيح البيانات هنا لترشيح بيانات القيم في ${0}.",
	"anycolumn": "أي عمود",
	"statusTipTitleNoFilter": "خط ترشيح البيانات",
	"statusTipTitleHasFilter": "‏ترشيح البيانات‏",
	"statusTipRelPre": "مطابقة",
	"statusTipRelPost": "قواعد.",
	"statusTipHeaderAll": "مطابقة كل القواعد.",
	"statusTipHeaderAny": "مطابقة أية قواعد.",
	"defaultItemsName": "البنود",
	"filterBarMsgHasFilterTemplate": "${0} من ${1} ${2} عرض.",
	"filterBarMsgNoFilterTemplate": "لم يتم تطبيق ترشيح البيانات",
	"filterBarDefButton": "تعريف ترشيح البيانات",
	"waiFilterBarDefButton": "ترشيح بيانات الجدول",
	"a11yFilterBarDefButton": "ترشيح بيانات...",
	"filterBarClearButton": "محو ترشيح البيانات",
	"waiFilterBarClearButton": "محو ترشيح البيانات",
	"closeFilterBarBtn": "اغلاق خط ترشيح البيانات",
	"clearFilterMsg": "سيقوم هذا بازالة مرشح البيانات وعرض كل السجلات المتاحة.",
	"anyColumnOption": "أي عمود",
	"trueLabel": "True",
	"falseLabel": "خطأ",
	"radioTrueLabel": "قيمة True",
	"radioFalseLabel": "قيمة False",
	"beginTimeRangeLabel": "بداية قيمة مدى الوقت",
	"endTimeRangeLabel": "نهاية قيمة مدى الوقت",
	"beginDateRangeLabel": "بداية قيمة مدى التاريخ",
	"endDateRangeLabel": "نهاية قيمة مدى التاريخ",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "فرز منفرد",
	nestedSort: "فرز متداخل",
	ascending: "اضغط ليتم الفرز تصاعديا",
	descending: "اضغط ليتم الفرز تنازليا",
	sortingState: "${0} - ${1}",
	unsorted: "عدم فرز هذا العمود",
	waiSingleSortLabel: "تم فرز ${0} - بواسطة ${1}. اختر ليتم الفرز بواسطة ${2}",
	waiNestedSortLabel:"${0} - متداخل وتم فرزه بواسطة ${1}. اختر ليتم التداخل والفرز بواسطة ${2}",

//PaginationBar
	pagerWai: 'البيجر',

	pageIndex: '${0}',
	pageIndexTitle: 'صفحة ${0}',

	firstPageTitle: 'الصفحة الأولى',
	prevPageTitle: 'الصفحة السابقة',
	nextPageTitle: 'الصفحة التالية',
	lastPageTitle: 'الصفحة الأخيرة',

	pageSize: '${0}',
	pageSizeTitle: '${0} بنود لكل صفحة',
	pageSizeAll: 'الكل',
	pageSizeAllTitle: 'كل البنود',

	description: '${0} - ${1} من ${2} بنود.',
	descriptionEmpty: 'الشبكة خالية.',

	summary: 'الاجمالي: ${0}',
	summaryWithSelection: 'الاجمالي: ${0} المحدد: ${1}',

	gotoBtnTitle: 'اذهب الى صفحة خاصة',

	gotoDialogTitle: 'اذهب الى صفحة',
	gotoDialogMainMsg: 'تحديد رقم الصفحة:',
	gotoDialogPageCount: '(${0} صفحات)',
	gotoDialogOKBtn: 'بدء',
	gotoDialogCancelBtn: 'الغاء الأمر',
	// for drop down pagination bar
	pageLabel: 'صفحة',
	pageSizeLabel: 'صفوف',

//QuickFilter
	filterLabel: '‏ترشيح البيانات‏',
	clearButtonTitle: 'محو ترشيح البيانات',
	buildFilterMenuLabel: 'بناء مرشح البيانات&hellip;',
	apply: 'تطبيق ترشيح البيانات',

//Sort
	helpMsg: '${0} - اضغط ليتم الفرز أو التحكم -اضغط للاضافة الى الفرز',
	singleHelpMsg: '${0} - اضغط ليتم الفرز',
	priorityOrder: 'أولوية الفرز ${0}',

//SummaryBar
	summaryTotal: 'الاجمالي: ${0}',
	summarySelected: 'المحدد: ${0}',
	summaryRange: 'المدى: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "اضغط مفتاح المساحة SPACE لتحديد الكل.",	//need translation
	indirectDeselectAll: "اضغط مفتاح المساحة SPACE لالغاء تحديد الكل.",	//need translation
	treeExpanded: "اضغط مفتاح Control + مفتاح سهم لليسار لطي هذا الصف.",	//need translation
	treeCollapsed: "اضغط مفتاح Control + مفتاح سهم لليمين لعرض هذا الصف."	//need translation
});

