define({
//Body
	loadingInfo: "ロード中...",
	emptyInfo: "表示する項目がありません",
	loadFailInfo: "データのロードに失敗しました!",
	loadMore: "さらにロード",
	loadMoreLoading: "ロード中...",
	loadPrevious: "前の項目をロード",
	loadPreviousLoading: "ロード中...",

//FilterBar
	"clearFilterDialogTitle": "フィルターのクリア",
	"filterDefDialogTitle": "フィルター",
	"defaultRuleTitle": "ルール",
	"ruleTitleTemplate": "ルール ${ruleNumber}",
	"noFilterApplied": "フィルターが適用されていません。",
	"defineFilter": "フィルターの定義",
	"conditionEqual": "等しい",
	"conditionNotEqual": "等しくない",
	"conditionLess": "より小",
	"conditionLessEqual": "より小または等しい",
	"conditionGreater": "より大",
	"conditionGreaterEqual": "より大または等しい",
	"conditionContain": "含む",
	"conditionIs": "一致する",
	"conditionStartWith": "先頭文字",
	"conditionEndWith": "終了文字",
	"conditionNotContain": "含まない",
	"conditionIsNot": "一致しない",
	"conditionNotStartWith": "先頭文字が次のもの以外",
	"conditionNotEndWith": "終了文字が次のもの以外",
	"conditionBefore": "より前",
	"conditionAfter": "より後",
	"conditionRange": "範囲",
	"conditionIsEmpty": "空である",
	"all": "すべて",
	"any": "いずれか",
	"relationAll": "すべてのルール",
	"waiRelAll": "次のルールのすべてに一致:",
	"relationAny": "いずれかのルール",
	"waiRelAny": "次のルールのいずれかに一致:",
	"relationMsgFront": "一致",
	"relationMsgTail": "",
	"and": "および",
	"or": "または",
	"addRuleButton": "ルールの追加",
	"waiAddRuleButton": "新規ルールの追加",
	"removeRuleButton": "ルールの削除",
	"waiRemoveRuleButtonTemplate": "ルール ${0} の削除",
	"addRuleButton": "フィルター・ルールの追加",
	"cancelButton": "キャンセル",
	"waiCancelButton": "このダイアログをキャンセル",
	"clearButton": "クリア",
	"waiClearButton": "フィルターのクリア",
	"filterButton": "フィルター",
	"waiFilterButton": "フィルターの実行依頼",
	"columnSelectLabel": "列",
	"waiColumnSelectTemplate": "ルール ${0} の列",
	"conditionSelectLabel": "条件",
	"waiConditionSelectTemplate": "ルール ${0} の条件",
	"valueBoxLabel": "値",
	"waiValueBoxTemplate": "フィルター操作を行ってルール ${0} を検出するための値を入力",
	"rangeTo": "範囲",
	"rangeTemplate": "${0} から ${1} まで",
	"statusTipHeaderColumn": "列",
	"statusTipHeaderCondition": "ルール",
	"statusTipTitle": "フィルター・バー",
	"statusTipMsg": "このフィルター・バーをクリックして、${0} の値にフィルターを適用します。",
	"anycolumn": "いずれかの列",
	"statusTipTitleNoFilter": "フィルター・バー",
	"statusTipTitleHasFilter": "フィルター",
	"statusTipRelPre": " ",
	"statusTipRelPost": "件のルールに一致。",
	"statusTipHeaderAll": "すべてのルールに一致。",
	"statusTipHeaderAny": "いずれかのルールに一致。",
	"defaultItemsName": "項目",
	"filterBarMsgHasFilterTemplate": "${0}/${1} ${2} が表示されました。",
	"filterBarMsgNoFilterTemplate": "フィルターが適用されていません",
	"filterBarDefButton": "フィルターの定義",
	"waiFilterBarDefButton": "テーブルのフィルタリング",
	"a11yFilterBarDefButton": "フィルター...",
	"filterBarClearButton": "フィルターのクリア",
	"waiFilterBarClearButton": "フィルターのクリア",
	"closeFilterBarBtn": "フィルター・バーを閉じる",
	"clearFilterMsg": "これにより、フィルターが削除され、使用可能なすべてのレコードが表示されます。",
	"anyColumnOption": "いずれかの列",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "値 True",
	"radioFalseLabel": "値 False",
	"beginTimeRangeLabel": "時刻範囲値の始まり",
	"endTimeRangeLabel": "時刻範囲値の終わり",
	"beginDateRangeLabel": "日付範囲値の始まり",
	"endDateRangeLabel": "日付範囲値の終わり",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "単一ソート",
	nestedSort: "ネスト・ソート",
	ascending: "クリックして昇順にソート",
	descending: "クリックして降順にソート",
	sortingState: "${0} - ${1}",
	unsorted: "この列をソートしない",
	waiSingleSortLabel: "${0} - ${1} でソートされています。${2} でのソートを選択してください",
	waiNestedSortLabel:"${0} - ${1} でネスト・ソートされています。${2} でのネスト・ソートを選択してください",

//PaginationBar
	pagerWai: 'ページャー',

	pageIndex: '${0}',
	pageIndexTitle: 'ページ ${0}',

	firstPageTitle: '最初のページ',
	prevPageTitle: '前のページ',
	nextPageTitle: '次のページ',
	lastPageTitle: '最後のページ',

	pageSize: '${0}',
	pageSizeTitle: 'ページ当たり ${0} 項目',
	pageSizeAll: 'すべて',
	pageSizeAllTitle: 'すべての項目',

	description: '${0} - ${1}/${2} 項目。',
	descriptionEmpty: 'グリッドが空です。',

	summary: '合計: ${0}',
	summaryWithSelection: '合計: ${0} 選択済み: ${1}',

	gotoBtnTitle: '特定のページに移動',

	gotoDialogTitle: 'ページに移動',
	gotoDialogMainMsg: 'ページ番号の指定:',
	gotoDialogPageCount: ' (${0} ページ)',
	gotoDialogOKBtn: '移動',
	gotoDialogCancelBtn: 'キャンセル',
	// for drop down pagination bar
	pageLabel: 'ページ',
	pageSizeLabel: '行',

//QuickFilter
	filterLabel: 'フィルター',
	clearButtonTitle: 'フィルターのクリア',
	buildFilterMenuLabel: 'フィルターの作成&hellip;',
	apply: 'フィルターの適用',

//SummaryBar
	summary: '合計: ${0}',
	summaryWithSelection: '合計: ${0} 選択済み: ${1}'
});
