define({     
//Body
	loadingInfo: "Betöltés...",
	emptyInfo: "Nincsenek megjeleníthető elemek.",
	loadFailInfo: "Nem sikerült az adatok betöltése!",
	loadMore: "Továbbiak betöltése",
	loadMoreLoading: "Betöltés...",
	loadPrevious: "Előző betöltése",
	loadPreviousLoading: "Betöltés...",

//FilterBar
	"clearFilterDialogTitle": "Szűrő törlése",
	"filterDefDialogTitle": "Szűrő",
	"defaultRuleTitle": "Szabály",
	"ruleTitleTemplate": "${ruleNumber}. szabály",
	"noFilterApplied": "Nincs szűrő alkalmazva.",
	"defineFilter": "Szűrő meghatározása",
	"conditionEqual": "egyenlő",
	"conditionNotEqual": "nem egyenlő",
	"conditionLess": "kisebb, mint",
	"conditionLessEqual": "kisebb vagy egyenlő",
	"conditionGreater": "nagyobb, mint",
	"conditionGreaterEqual": "nagyobb vagy egyenlő",
	"conditionContain": "tartalmazza",
	"conditionIs": "pontosan",
	"conditionStartWith": "kezdete",
	"conditionEndWith": "vége",
	"conditionNotContain": "nem tartalmazza",
	"conditionIsNot": "nem",
	"conditionNotStartWith": "nem kezdete",
	"conditionNotEndWith": "nem vége",
	"conditionBefore": "előtt",
	"conditionAfter": "után",
	"conditionRange": "tartomány",
	"conditionIsEmpty": "üres",
	"all": "mind",
	"any": "bármely",
	"relationAll": "minden szabály",
	"waiRelAll": "Megfelel a következő összes szabálynak:",
	"relationAny": "bármely szabály",
	"waiRelAny": "Megfelel a következő bármely szabálynak:",
	"relationMsgFront": "Megfeleltetés",
	"relationMsgTail": "",
	"and": "és",
	"or": "vagy",
	"addRuleButton": "Szabály hozzáadása",
	"waiAddRuleButton": "Új szabály hozzáadása",
	"removeRuleButton": "Szabály eltávolítása",
	"waiRemoveRuleButtonTemplate": "${0} szabály eltávolítása",
	"addRuleButton": "Szűrőszabály hozzáadása",
	"cancelButton": "Mégse",
	"waiCancelButton": "A párbeszédablak bezárása",
	"clearButton": "Törlés",
	"waiClearButton": "A szűrő törlése",
	"filterButton": "Szűrő",
	"waiFilterButton": "A szűrő elküldése",
	"columnSelectLabel": "Oszlop:",
	"waiColumnSelectTemplate": "${0} szabály oszlopa",
	"conditionSelectLabel": "Feltétel:",
	"waiConditionSelectTemplate": "${0} szabály feltétele",
	"valueBoxLabel": "Érték:",
	"waiValueBoxTemplate": "Írja be a szűrni kívánt értéket a(z) ${0} szabályhoz",
	"rangeTo": "-",
	"rangeTemplate": "${0} - ${1}",
	"statusTipHeaderColumn": "Oszlop",
	"statusTipHeaderCondition": "Szabályok",
	"statusTipTitle": "Szűrősáv",
	"statusTipMsg": "Kattintson erre a szűrősávra a(z) ${0} értékeinek szűréséhez.",
	"anycolumn": "bármely oszlop",
	"statusTipTitleNoFilter": "Szűrősáv",
	"statusTipTitleHasFilter": "Szűrő",
	"statusTipRelPre": "Megfeleltetés",
	"statusTipRelPost": "szabály.",
	"statusTipHeaderAll": "Minden szabálynak megfelel.",
	"statusTipHeaderAny": "Bármely szabálynak megfelel.",
	"defaultItemsName": "elemek",
	"filterBarMsgHasFilterTemplate": "${0} / ${1} ${2} megjelenítve.",
	"filterBarMsgNoFilterTemplate": "Nincs szűrő alkalmazva.",
	"filterBarDefButton": "Szűrő meghatározása",
	"waiFilterBarDefButton": "Táblázat szűrése",
	"a11yFilterBarDefButton": "Szűrő...",
	"filterBarClearButton": "Szűrő törlése",
	"waiFilterBarClearButton": "A szűrő törlése",
	"closeFilterBarBtn": "Szűrősáv bezárása",
	"clearFilterMsg": "Eltávolítja a szűrőt és megjelenít minden elérhető rekordot.",
	"anyColumnOption": "Bármely oszlop",
	"trueLabel": "Igaz",
	"falseLabel": "Hamis",
	"radioTrueLabel": "Érték igaz",
	"radioFalseLabel": "Érték hamis",
	"beginTimeRangeLabel": "Időtartomány érték kezdete",
	"endTimeRangeLabel": "Időtartomány érték vége",
	"beginDateRangeLabel": "Dátumtartomány érték kezdete",
	"endDateRangeLabel": "Dátumtartomány érték vége",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Egyszerű rendezés",
	nestedSort: "Beágyazott rendezés",
	ascending: "Kattintson ide a növekvő rendezéshez",
	descending: "Kattintson ide a csökkenő rendezéshez",
	sortingState: "${0} - ${1}",
	unsorted: "Ne rendezze ezt az oszlopot",
	waiSingleSortLabel: "${0} rendezve ${1} alapján. Válassza ki ${2} alapján történő rendezéshez.",
	waiNestedSortLabel:"${0} egymásba ágyazottan rendezve ${1} alapján. Válassza ki ${2} alapján történő egymásba ágyazott rendezéshez.",

//PaginationBar
	pagerWai: 'Személyhívó',

	pageIndex: '${0}',
	pageIndexTitle: '${0}. oldal',

	firstPageTitle: 'Első oldal',
	prevPageTitle: 'Előző oldal',
	nextPageTitle: 'Következő oldal',
	lastPageTitle: 'Utolsó oldal',

	pageSize: '${0}',
	pageSizeTitle: '${0} elem oldalanként',
	pageSizeAll: 'Mind',
	pageSizeAllTitle: 'Összes elem',

	description: '${0} - ${1} / ${2} elem.',
	descriptionEmpty: 'A rács üres.',

	summary: 'Összesen: ${0}',
	summaryWithSelection: 'Összesen: ${0} Kijelölve: ${1}',

	gotoBtnTitle: 'Ugrás adott oldalra',

	gotoDialogTitle: 'Ugrás adott oldalra',
	gotoDialogMainMsg: 'Adja meg az oldalszámot:',
	gotoDialogPageCount: '(${0} oldal)',
	gotoDialogOKBtn: 'Mehet',
	gotoDialogCancelBtn: 'Mégse',
	// for drop down pagination bar
	pageLabel: 'Oldal',
	pageSizeLabel: 'Sorok',

//QuickFilter
	filterLabel: 'Szűrő',
	clearButtonTitle: 'Szűrő törlése',
	buildFilterMenuLabel: 'Szűrő összeállítása&hellip;',
	apply: 'Szűrő alkalmazása',

//Sort
	helpMsg: '${0} - Kattintson a rendezéshez, vagy kattintson a Ctrl gomb lenyomva tartása mellett a rendezés kiegészítéséhez',
	singleHelpMsg: '${0} - Kattintson a rendezéshez',
	priorityOrder: '${0} rendezési prioritás',

//SummaryBar
	summaryTotal: 'Összesen: ${0}',
	summarySelected: 'Kijelölt: ${0}',
	summaryRange: 'Tartomány: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Nyomja meg a szóközt az összes kijelöléséhez. ",	//need translation
	indirectDeselectAll: "Nyomja meg a szóközt a kijelölések megszüntetéséhez. ",	//need translation
	treeExpanded: "Ctrl+balra mutató nyíl a sor összehúzásához.",	//need translation
	treeCollapsed: "Ctrl+jobbra mutató nyíl a sor kibontásához. "	//need translation
});

