define(
({
	"clearFilterDialogTitle": "Очистити фільтр",
	"filterDefDialogTitle": "Фільтр",
	"defaultRuleTitle": "Правило",
	"ruleTitleTemplate": "Правило ${ruleNumber}",
	"noFilterApplied": "Фільтри не використовуються.",
	"defineFilter": "Визначити фільтр",
	"conditionEqual": "дорівнює",
	"conditionNotEqual": "не дорівнює",
	"conditionLess": "менше за",
	"conditionLessEqual": "менше або дорівнює",
	"conditionGreater": "більше за",
	"conditionGreaterEqual": "більше або дорівнює",
	"conditionContain": "містить",
	"conditionIs": "дорівнює",
	"conditionStartWith": "починається з",
	"conditionEndWith": "закінчується на",
	"conditionNotContain": "не містить",
	"conditionIsNot": "не дорівнює",
	"conditionNotStartWith": "не починається з",
	"conditionNotEndWith": "не закінчується на",
	"conditionBefore": "до",
	"conditionAfter": "після",
	"conditionRange": "діапазон",
	"conditionIsEmpty": "порожній",
	"all": "всі",
	"any": "будь-яке",
	"relationAll": "всі правила",
	"waiRelAll": "Відповідає всім наступним правилам:",
	"relationAny": "будь-які правила",
	"waiRelAny": "Відповідає будь-якому з наступних правил:",
	"relationMsgFront": "Відповідає",
	"relationMsgTail": "",
	"and": "та",
	"or": "або",
	"addRuleButton": "Додати правило",
	"waiAddRuleButton": "Додати нове правило",
	"removeRuleButton": "Видалити правило",
	"waiRemoveRuleButtonTemplate": "Видалити правило ${0}",
	"addRuleButton": "Додати правило фільтрації",
	"cancelButton": "Скасувати",
	"waiCancelButton": "Скасувати це вікно",
	"clearButton": "Очистити",
	"waiClearButton": "Очистити фільтр",
	"filterButton": "Фільтр",
	"waiFilterButton": "Застосувати фільтр",
	"columnSelectLabel": "Стовпчик",
	"waiColumnSelectTemplate": "Стовпчик для правила ${0}",
	"conditionSelectLabel": "Умова",
	"waiConditionSelectTemplate": "Умова правила ${0}",
	"valueBoxLabel": "Значення",
	"waiValueBoxTemplate": "Введіть значення для фільтрації за правилом ${0}",
	"rangeTo": "до",
	"rangeTemplate": "з ${0} до ${1}",
	"statusTipHeaderColumn": "Стовпчик",
	"statusTipHeaderCondition": "Правила",
	"statusTipTitle": "Панель фільтрів",
	"statusTipMsg": "Клацніть на панелі фільтрів для фільтрації за значеннями у ${0}.",
	"anycolumn": "будь-який стовпець",
	"statusTipTitleNoFilter": "Панель фільтрів",
	"statusTipTitleHasFilter": "Фільтр",
	"statusTipRelPre": "Відповідає",
	"statusTipRelPost": "правила.",
	"statusTipHeaderAll": "Відповідає всім правилам.",
	"statusTipHeaderAny": "Відповідає хоча б одному правилу.",
	"defaultItemsName": "елементи",
	"filterBarMsgHasFilterTemplate": "Показано ${0} з ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Фільтр не використовується",
	"filterBarDefButton": "Визначити фільтр",
	"waiFilterBarDefButton": "Фільтрувати таблицю",
	"a11yFilterBarDefButton": "Фільтр...",
	"filterBarClearButton": "Очистити фільтр",
	"waiFilterBarClearButton": "Очистити фільтр",
	"closeFilterBarBtn": "Закрити панель фільтрів",
	"clearFilterMsg": "Ця опція видаляє фільтр та показує всі доступні записи.",
	"anyColumnOption": "Будь-який стовпець",
	"trueLabel": "Істина",
	"falseLabel": "Неправда",
	"radioTrueLabel": "Значення True",
	"radioFalseLabel": "Значення False",
	"beginTimeRangeLabel": "Початкове значення диапазону часу",
	"endTimeRangeLabel": "Кінцеве значення диапазону часу",
	"beginDateRangeLabel": "Початкове значення диапазону дат",
	"endDateRangeLabel": "Кінцеве значення диапазону дат",
	"startsWithExpr": "${0}*"
})
);
