define({     
//Body
	loadingInfo: "Φόρτωση...",
	emptyInfo: "Δεν υπάρχουν στοιχεία για εμφάνιση.",
	loadFailInfo: "Απέτυχε η φόρτωση δεδομένων!",
	loadMore: "Φόρτωση περισσοτέρων",
	loadMoreLoading: "Φόρτωση...",
	loadPrevious: "Φόρτωση προηγούμενου",
	loadPreviousLoading: "Φόρτωση...",

//FilterBar
	"clearFilterDialogTitle": "Εκκαθάριση φίλτρου",
	"filterDefDialogTitle": "Φίλτρο",
	"defaultRuleTitle": "Κανόνας",
	"ruleTitleTemplate": "Κανόνας ${ruleNumber}",
	"noFilterApplied": "Δεν έχει εφαρμοστεί φίλτρο.",
	"defineFilter": "Ορισμός φίλτρου",
	"conditionEqual": "ίσο",
	"conditionNotEqual": "όχι ίσο",
	"conditionLess": "είναι μικρότερο από",
	"conditionLessEqual": "μικρότερο ή ίσο",
	"conditionGreater": "είναι μεγαλύτερο από",
	"conditionGreaterEqual": "μεγαλύτερο ή ίσο",
	"conditionContain": "περιέχει",
	"conditionIs": "είναι",
	"conditionStartWith": "αρχίζει από",
	"conditionEndWith": "τελειώνει σε",
	"conditionNotContain": "δεν περιέχει",
	"conditionIsNot": "δεν είναι",
	"conditionNotStartWith": "δεν αρχίζει από",
	"conditionNotEndWith": "δεν τελειώνει σε",
	"conditionBefore": "πριν",
	"conditionAfter": "μετά",
	"conditionRange": "εύρος",
	"conditionIsEmpty": "είναι κενό",
	"all": "όλα",
	"any": "οποιοδήποτε",
	"relationAll": "όλοι οι κανόνες",
	"waiRelAll": "Αντιστοιχία με όλους τους παρακάτω κανόνες:",
	"relationAny": "οποιοσδήποτε κανόνας",
	"waiRelAny": "Αντιστοιχία με οποιονδήποτε από τους παρακάτω κανόνες:",
	"relationMsgFront": "Αντιστοιχία",
	"relationMsgTail": "",
	"and": "και",
	"or": "ή",
	"addRuleButton": "Προσθήκη κανόνα",
	"waiAddRuleButton": "Προσθήκη νέου κανόνα",
	"removeRuleButton": "Αφαίρεση κανόνα",
	"waiRemoveRuleButtonTemplate": "Αφαίρεση κανόνα ${0}",
	"addRuleButton": "Προσθήκη κανόνα φίλτρου",
	"cancelButton": "Ακύρωση",
	"waiCancelButton": "Ακύρωση αυτού του πλαισίου διαλόγου",
	"clearButton": "Εκκαθάριση",
	"waiClearButton": "Εκκαθάριση του φίλτρου",
	"filterButton": "Φίλτρο",
	"waiFilterButton": "Υποβολή του φίλτρου",
	"columnSelectLabel": "Στήλη:",
	"waiColumnSelectTemplate": "Στήλη για τον κανόνα ${0}",
	"conditionSelectLabel": "Συνθήκη:",
	"waiConditionSelectTemplate": "Συνθήκη για τον κανόνα ${0}",
	"valueBoxLabel": "Τιμή:",
	"waiValueBoxTemplate": "Καταχωρήστε τιμή φίλτρου για τον κανόνα ${0}",
	"rangeTo": "έως",
	"rangeTemplate": "από ${0} έως ${1}",
	"statusTipHeaderColumn": "Στήλη",
	"statusTipHeaderCondition": "Κανόνες",
	"statusTipTitle": "Γραμμή φίλτρου",
	"statusTipMsg": "Πατήστε στη γραμμή φίλτρου για φιλτράρισμα με βάση τις τιμές στο ${0}.",
	"anycolumn": "οποιαδήποτε στήλη",
	"statusTipTitleNoFilter": "Γραμμή φίλτρου",
	"statusTipTitleHasFilter": "Φίλτρο",
	"statusTipRelPre": "Αντιστοιχία",
	"statusTipRelPost": "κανόνες.",
	"statusTipHeaderAll": "Αντιστοιχία με όλους τους κανόνες.",
	"statusTipHeaderAny": "Αντιστοιχία με οποιουσδήποτε κανόνες.",
	"defaultItemsName": "στοιχεία",
	"filterBarMsgHasFilterTemplate": "Εμφανίζονται ${0} από ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Δεν έχει εφαρμοστεί φίλτρο",
	"filterBarDefButton": "Ορισμός φίλτρου",
	"waiFilterBarDefButton": "Φιλτράρισμα του πίνακα",
	"a11yFilterBarDefButton": "Φιλτράρισμα...",
	"filterBarClearButton": "Εκκαθάριση φίλτρου",
	"waiFilterBarClearButton": "Εκκαθάριση του φίλτρου",
	"closeFilterBarBtn": "Κλείσιμο γραμμής φίλτρου",
	"clearFilterMsg": "Με την επιλογή αυτή θα αφαιρεθεί το φίλτρο και θα εμφανιστούν όλες οι διαθέσιμες εγγραφές.",
	"anyColumnOption": "Οποιαδήποτε στήλη",
	"trueLabel": "Αληθής",
	"falseLabel": "Ψευδής",
	"radioTrueLabel": "Τιμή αληθής",
	"radioFalseLabel": "Τιμή ψευδής",
	"beginTimeRangeLabel": "Άρχική τιμή χρονικού εύρους",
	"endTimeRangeLabel": "Τελική τιμή χρονικού εύρους",
	"beginDateRangeLabel": "Αρχική τιμή εύρους ημερομηνιών",
	"endDateRangeLabel": "Τελική τιμή εύρους ημερομηνιών",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Απλή ταξινόμηση",
	nestedSort: "Ένθετη ταξινόμηση",
	ascending: "Πατήστε εδώ για ταξινόμηση σε αύξουσα σειρά",
	descending: "Πατήστε εδώ για ταξινόμηση σε φθίνουσα σειρά",
	sortingState: "${0} - ${1}",
	unsorted: "Χωρίς ταξινόμηση αυτής της στήλης",
	waiSingleSortLabel: "${0} - ταξινομήθηκε κατά ${1}. Επιλέξτε ταξινόμηση κατά ${2}",
	waiNestedSortLabel:"${0} - ταξινομήθηκε με ένθετη ταξινόμηση κατά ${1}. Επιλέξτε ένθετη ταξινόμηση κατά ${2}",

//PaginationBar
	pagerWai: 'Συσκευή τηλεειδοποίησης',

	pageIndex: '${0}',
	pageIndexTitle: 'Σελίδα ${0}',

	firstPageTitle: 'Πρώτη σελίδα',
	prevPageTitle: 'Προηγούμενη σελίδα',
	nextPageTitle: 'Επόμενη σελίδα',
	lastPageTitle: 'Τελευταία σελίδα',

	pageSize: '${0}',
	pageSizeTitle: '${0} στοιχεία ανά σελίδα',
	pageSizeAll: 'Όλα',
	pageSizeAllTitle: 'Όλα τα στοιχεία',

	description: '${0} - ${1} από ${2} στοιχεία.',
	descriptionEmpty: 'Το πλέγμα είναι κενό.',

	summary: 'Σύνολο: ${0}',
	summaryWithSelection: 'Σύνολο: ${0} Επιλεγμένα: ${1}',

	gotoBtnTitle: 'Μετάβαση σε συγκεκριμένη σελίδα',

	gotoDialogTitle: 'Μετάβαση σε σελίδα',
	gotoDialogMainMsg: 'Καθορίστε τον αριθμό σελίδας:',
	gotoDialogPageCount: ' (${0} σελίδες)',
	gotoDialogOKBtn: 'Μετάβαση',
	gotoDialogCancelBtn: 'Ακύρωση',
	// for drop down pagination bar
	pageLabel: 'Σελίδα',
	pageSizeLabel: 'Γραμμές',

//QuickFilter
	filterLabel: 'Φίλτρο',
	clearButtonTitle: 'Εκκαθάριση φίλτρου',
	buildFilterMenuLabel: 'Δημιουργία φίλτρου&hellip;',
	apply: 'Εφαρμογή φίλτρου',

//Sort
	helpMsg: '${0} - Πατήστε τη στήλη για ταξινόμηση ή πατήστε την κρατώντας το πλήκτρο Ctrl για να την προσθέσετε για ταξινόμηση',
	singleHelpMsg: '${0} - Πατήστε τη στήλη για ταξινόμηση',
	priorityOrder: 'προτεραιότητα ταξινόμησης ${0}',

//SummaryBar
	summaryTotal: 'Σύνολο: ${0}',
	summarySelected: 'Επιλεγμένα: ${0}',
	summaryRange: 'Εύρος: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Πατήστε το πλήκτρο διαστήματος για να επιλεγούν όλα.",	//need translation
	indirectDeselectAll: "Πατήστε το πλήκτρο διαστήματος για να αποεπιλεγούν όλα.",	//need translation
	treeExpanded: "Πατήστε Ctrl + αριστερό βέλος για σύμπτυξη αυτής της γραμμής.",	//need translation
	treeCollapsed: "Πατήστε Ctrl + δεξί βέλος για ανάπτυξη αυτής της γραμμής."	//need translation
});

