define({     
//Body
	loadingInfo: "טעינה...‏",
	emptyInfo: "אין פריטים להצגה",
	loadFailInfo: "כשל בטעינת הנתונים!",
	loadMore: "טעינת עוד",
	loadMoreLoading: "טעינה...‏",
	loadPrevious: "טעינת הקודם",
	loadPreviousLoading: "טעינה...‏",

//FilterBar
	"clearFilterDialogTitle": "ניקוי מסנן",
	"filterDefDialogTitle": "מסנן",
	"defaultRuleTitle": "כלל",
	"ruleTitleTemplate": "כלל ${ruleNumber}",
	"noFilterApplied": "לא הוחל מסנן.",
	"defineFilter": "הגדרת מסנן",
	"conditionEqual": "שווה",
	"conditionNotEqual": "אינו שווה",
	"conditionLess": "קטן מ-",
	"conditionLessEqual": "קטן או שווה",
	"conditionGreater": "גדול מ-",
	"conditionGreaterEqual": "גדול או שווה",
	"conditionContain": "מכיל",
	"conditionIs": "הוא",
	"conditionStartWith": "מתחיל עם",
	"conditionEndWith": "מסתיים עם",
	"conditionNotContain": "אינו מכיל",
	"conditionIsNot": "אינו",
	"conditionNotStartWith": "אינו מתחיל עם",
	"conditionNotEndWith": "אינו מסתיים עם",
	"conditionBefore": "לפני",
	"conditionAfter": "אחרי",
	"conditionRange": "טווח",
	"conditionIsEmpty": "ריק",
	"all": "הכל",
	"any": "כלשהו",
	"relationAll": "כל הכללים",
	"waiRelAll": "התאמה לכל הכללים שלהלן:",
	"relationAny": "כלל כלשהו",
	"waiRelAny": "התאמה לכלל כלשהו הכללים שלהלן:",
	"relationMsgFront": "התאמה",
	"relationMsgTail": "",
	"and": "וגם",
	"or": "או",
	"addRuleButton": "הוספת כלל",
	"waiAddRuleButton": "הוספת כלל חדש",
	"removeRuleButton": "סילוק כלל",
	"waiRemoveRuleButtonTemplate": "סילוק הכלל ${0}",
	"addRuleButton": "הוספת כלל מסנן ",
	"cancelButton": "ביטול",
	"waiCancelButton": "ביטול דו-שיח זה",
	"clearButton": "ניקוי",
	"waiClearButton": "ניקוי המסנן",
	"filterButton": "מסנן",
	"waiFilterButton": "הגשת המסנן",
	"columnSelectLabel": "עמודה:",
	"waiColumnSelectTemplate": "עמודה עבור הכלל ${0}",
	"conditionSelectLabel": "תנאי: ",
	"waiConditionSelectTemplate": "תנאי עבור הכלל ${0}",
	"valueBoxLabel": "ערך:",
	"waiValueBoxTemplate": "ציינו ערך לסינון עבור הכלל ${0}",
	"rangeTo": "עד",
	"rangeTemplate": "מ-${0} עד ${1}",
	"statusTipHeaderColumn": "עמודה",
	"statusTipHeaderCondition": "כללים",
	"statusTipTitle": "סרגל סינון",
	"statusTipMsg": "לחצנו על סרגל הסינון כאן כדי לסנן לפי ערכים בתוך ${0}.",
	"anycolumn": "עמודה כלשהי",
	"statusTipTitleNoFilter": "סרגל סינון",
	"statusTipTitleHasFilter": "מסנן",
	"statusTipRelPre": "התאמה",
	"statusTipRelPost": "כללים.",
	"statusTipHeaderAll": "התאמה לכל הכללים.",
	"statusTipHeaderAny": "התאמה לכלל כלשהו.",
	"defaultItemsName": "פריטים",
	"filterBarMsgHasFilterTemplate": "מוצגים ${0} מתוך ${1} ${2}.‏",
	"filterBarMsgNoFilterTemplate": "לא הוחל מסנן.",
	"filterBarDefButton": "הגדרת מסנן",
	"waiFilterBarDefButton": "סינון הטבלה",
	"a11yFilterBarDefButton": "סינון...‏",
	"filterBarClearButton": "ניקוי מסנן",
	"waiFilterBarClearButton": "ניקוי המסנן",
	"closeFilterBarBtn": "סגירת סרגל הסינון",
	"clearFilterMsg": "פעולה זו תסלק את המסנן ותציג את כל הרשומות הזמינות.",
	"anyColumnOption": "עמודה כלשהי",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "ערך True",
	"radioFalseLabel": "ערך False",
	"beginTimeRangeLabel": "התחלת ערך טווח שעות",
	"endTimeRangeLabel": "סוף ערך טווח שעות",
	"beginDateRangeLabel": "התחלת ערך טווח תאריכים",
	"endDateRangeLabel": "סוף ערך טווח תאריכים",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "מיון יחיד",
	nestedSort: "מיון מקונן",
	ascending: "לחצו כדי למיין בסדר עולה",
	descending: "לחצו כדי למיין בסדר יורד",
	sortingState: "${0} - ${1}",
	unsorted: "לא למיין עמודה זו",
	waiSingleSortLabel: "${0} - ממוין לפי ${1}. בחרו כדי למיין לפי ${2}",
	waiNestedSortLabel:"${0} - ממוין בקינון לפי ${1}. בחרו כדי למיין בקינון לפי ${2}",

//PaginationBar
	pagerWai: 'דפדוף',

	pageIndex: '${0}',
	pageIndexTitle: 'עמוד ${0}',

	firstPageTitle: 'עמוד ראשון',
	prevPageTitle: 'העמוד הקודם',
	nextPageTitle: 'העמוד הבא',
	lastPageTitle: 'עמוד אחרון',

	pageSize: '${0}',
	pageSizeTitle: '${0} פריטים בעמוד',
	pageSizeAll: 'הכל',
	pageSizeAllTitle: 'כל הפריטים',

	description: '${0} - ${1} מתוך ${2} פריטים. ',
	descriptionEmpty: 'הסריג ריק. ',

	summary: 'סך הכל: ${0}',
	summaryWithSelection: 'סך הכל: ${0} נבחרו: ${1}',

	gotoBtnTitle: 'מעבר לעמוד מסוים',

	gotoDialogTitle: 'מעבר לעמוד',
	gotoDialogMainMsg: 'ציינו את מספר העמוד:',
	gotoDialogPageCount: '(${0} עמודים)',
	gotoDialogOKBtn: 'ביצוע',
	gotoDialogCancelBtn: 'ביטול',
	// for drop down pagination bar
	pageLabel: 'עמוד',
	pageSizeLabel: 'שורות',

//QuickFilter
	filterLabel: 'מסנן',
	clearButtonTitle: 'ניקוי מסנן',
	buildFilterMenuLabel: 'בניית מסנן&hellip;‏ ',
	apply: 'החלת מסנן ',

//Sort
	helpMsg: '${0} - לחיצה למיון או control-לחיצה להוספה למיון ',
	singleHelpMsg: '${0} - לחיצה למיון ',
	priorityOrder: 'קדימות מיון ${0}',

//SummaryBar
	summaryTotal: 'סך הכל: ${0}',
	summarySelected: 'נבחרו: ${0}',
	summaryRange: 'טווח: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "לחצו על מקש הרווח כדי לבחור הכל. ",	//need translation
	indirectDeselectAll: "לחצו על מקש הרווח כדי לבטל את בחירת הכל. ",	//need translation
	treeExpanded: "Control + חץ שמאלה לכיווץ שורה זו. ",	//need translation
	treeCollapsed: "Control + חץ ימינה להרחבת שורה זו."	//need translation
});

