define({      
//begin v1.x content
	"clearFilterDialogTitle": "محو ترشيح البيانات",
	"filterDefDialogTitle": "ترشيح البيانات",
	"defaultRuleTitle": "قاعدة",
	"ruleTitleTemplate": "القاعدة ${ruleNumber}",
	"noFilterApplied": "لم يتم تطبيق مرشح بيانات.",
	"defineFilter": "تعريف ترشيح البيانات",
	"conditionEqual": "يساوي",
	"conditionNotEqual": "لا يساوي",
	"conditionLess": "أصغر من",
	"conditionLessEqual": "أصغر من أو يساوي",
	"conditionGreater": "أكبر من",
	"conditionGreaterEqual": "أكبر من أو يساوي",
	"conditionContain": "يتضمن",
	"conditionIs": "هو",
	"conditionStartWith": "يبدأ بالحروف",
	"conditionEndWith": "ينتهي بالحروف",
	"conditionNotContain": "لا يتضمن",
	"conditionIsNot": "ليس",
	"conditionNotStartWith": "لا يبدأ بالحروف",
	"conditionNotEndWith": "لا ينتهي بالحروف",
	"conditionBefore": "قبل",
	"conditionAfter": "بعد",
	"conditionRange": "المدى",
	"conditionIsEmpty": "خالي",
	"all": "الكل",
	"any": "أى ",
	"relationAll": "كل القواعد",
	"waiRelAll": "مطابقة كل القواعد التالية:",
	"relationAny": "أية قواعد",
	"waiRelAny": "مطابقة أي من القواعد التالية:",
	"relationMsgFront": "مطابقة",
	"relationMsgTail": "",
	"and": "and",
	"or": "or",
	"addRuleButton": "اضافة قاعدة",
	"waiAddRuleButton": "اضافة قاعدة جديدة",
	"removeRuleButton": "ازالة قاعدة",
	"waiRemoveRuleButtonTemplate": "ازالة القاعدة ${0}",
	"addRuleButton": "اضافة قاعدة ترشيح",
	"cancelButton": "الغاء",
	"waiCancelButton": "الغاء مربع الحوار هذا",
	"clearButton": "محو",
	"waiClearButton": "محو ترشيح البيانات",
	"filterButton": "ترشيح البيانات",
	"waiFilterButton": "احالة ترشيح البيانات",
	"columnSelectLabel": "عمود",
	"waiColumnSelectTemplate": "العمود للقاعدة ${0}",
	"conditionSelectLabel": "الشرط",
	"waiConditionSelectTemplate": "الشرط للقاعدة ${0}",
	"valueBoxLabel": "القيمة",
	"waiValueBoxTemplate": "أدخل قيمة لترشيح البيانات للقاعدة ${0}",
	"rangeTo": "الى",
	"rangeTemplate": "من ${0} الى ${1}",
	"statusTipHeaderColumn": "عمود",
	"statusTipHeaderCondition": "القواعد",
	"statusTipTitle": "خط ترشيح البيانات",
	"statusTipMsg": "اضغط على خط ترشيح البيانات هنا لترشيح البيانات بناءا على القيم التي توجد في ${0}.",
	"anycolumn": "أي عمود",
	"statusTipTitleNoFilter": "خط ترشيح البيانات",
	"statusTipTitleHasFilter": "ترشيح البيانات",
	"statusTipRelPre": "مطابقة",
	"statusTipRelPost": "القواعد.",
	"statusTipHeaderAll": "مطابقة كل القواعد.",
	"statusTipHeaderAny": "مطابقة أي قواعد.",
	"defaultItemsName": "بنود",
	"filterBarMsgHasFilterTemplate": "يتم عرض ${0} من ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "لم يتم تطبيق أي ترشيح للبيانات.",
	"filterBarDefButton": "تعريف ترشيح البيانات",
	"waiFilterBarDefButton": "ترشيح بيانات الجدول",
	"a11yFilterBarDefButton": "ترشيح البيانات...",
	"filterBarClearButton": "محو ترشيح البيانات",
	"waiFilterBarClearButton": "محو ترشيح البيانات",
	"closeFilterBarBtn": "اغلاق خط ترشيح البيانات",
	"clearFilterMsg": "سيؤدي هذا الى ازالة ترشيح البيانات وعرض كل السجلات المتاحة.",
	"anyColumnOption": "أي عمود",
	"trueLabel": "متحقق",
	"falseLabel": "غير متحقق",
	"radioTrueLabel": "قيمة صحيح",
	"radioFalseLabel": "قيمة خطأ",
	"beginTimeRangeLabel": "بدء قيمة مدى الوقت",
	"endTimeRangeLabel": "نهاية قيمة مدى الوقت",
	"beginDateRangeLabel": "بدء قيمة مدى التاريخ",
	"endDateRangeLabel": "نهاية قيمة مدى التاريخ",
	"startsWithExpr": "${0}*"
//end v1.x content
});

