define({      
//begin v1.x content
	"clearFilterDialogTitle": "Rensa filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Inget filter tillämpat.",
	"defineFilter": "Definiera filter",
	"conditionEqual": "lika med",
	"conditionNotEqual": "inte lika med",
	"conditionLess": "är mindre än",
	"conditionLessEqual": "mindre eller lika med",
	"conditionGreater": "är större än",
	"conditionGreaterEqual": "större än eller lika med",
	"conditionContain": "innehåller",
	"conditionIs": "är",
	"conditionStartWith": "börjar med",
	"conditionEndWith": "slutar med",
	"conditionNotContain": "innehåller inte",
	"conditionIsNot": "är inte",
	"conditionNotStartWith": "börjar inte med",
	"conditionNotEndWith": "slutar inte med",
	"conditionBefore": "före",
	"conditionAfter": "efter",
	"conditionRange": "intervall",
	"conditionIsEmpty": "är tom",
	"all": "alla",
	"any": "någon",
	"relationAll": "alla regler",
	"waiRelAll": "Matcha alla följande regler:",
	"relationAny": "någon regel",
	"waiRelAny": "Matcha någon av följande regler:",
	"relationMsgFront": "Matcha",
	"relationMsgTail": "",
	"and": "och",
	"or": "eller",
	"addRuleButton": "Lägg till regel",
	"waiAddRuleButton": "Lägg till en ny regel",
	"removeRuleButton": "Ta bort regel",
	"waiRemoveRuleButtonTemplate": "Ta bort regel ${0}",
	"addRuleButton": "Lägg till filterregel",
	"cancelButton": "Avbryt",
	"waiCancelButton": "Avbryt dialogen",
	"clearButton": "Rensa",
	"waiClearButton": "Rensa filtret",
	"filterButton": "Filter",
	"waiFilterButton": "Filtrera",
	"columnSelectLabel": "Kolumn",
	"waiColumnSelectTemplate": "Kolumn för regel ${0}",
	"conditionSelectLabel": "Villkor",
	"waiConditionSelectTemplate": "Villkor för regel ${0}",
	"valueBoxLabel": "Värde",
	"waiValueBoxTemplate": "Ange värde för filtrering efter regeln ${0}",
	"rangeTo": "till",
	"rangeTemplate": "från ${0} till ${1}",
	"statusTipHeaderColumn": "Kolumn",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filterfält",
	"statusTipMsg": "Klicka på filterfältet om du vill filtrera värden i ${0}.",
	"anycolumn": "alla kolumner",
	"statusTipTitleNoFilter": "Filterfält",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Matcha",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Matcha alla regler.",
	"statusTipHeaderAny": "Matcha någon av reglerna.",
	"defaultItemsName": "objekt",
	"filterBarMsgHasFilterTemplate": "${0} av ${1} ${2} visas.",
	"filterBarMsgNoFilterTemplate": "Inget filter tillämpat",
	"filterBarDefButton": "Definiera filter",
	"waiFilterBarDefButton": "Filtrera tabellen",
	"a11yFilterBarDefButton": "Filter...",
	"filterBarClearButton": "Rensa filter",
	"waiFilterBarClearButton": "Rensa filtret",
	"closeFilterBarBtn": "Stäng filterfält",
	"clearFilterMsg": "Tar bort filtret och visar alla tillgängliga poster.",
	"anyColumnOption": "Någon kolumn",
	"trueLabel": "Sant",
	"falseLabel": "Falskt",
	"radioTrueLabel": "Värdet Sant",
	"radioFalseLabel": "Värdet Falskt",
	"beginTimeRangeLabel": "Startvärde för tidsintervall",
	"endTimeRangeLabel": "Slutvärde för tidsintervall",
	"beginDateRangeLabel": "Startvärde för datumintervall",
	"endDateRangeLabel": "Slutvärde för datumintervall",
	"startsWithExpr": "${0}*"
//end v1.x content
});

