//>>built
define("dojox/widget/Portlet","dojo/_base/declare,dojo/_base/kernel,dojo/fx,dijit/TitlePane,./PortletSettings,./PortletDialogSettings".split(","),function(g,h,j,i){h.experimental("dojox.widget.Portlet");return g("dojox.widget.Portlet",[i,dijit._Container],{resizeChildren:!0,closable:!0,_parents:null,_size:null,dragRestriction:!1,buildRendering:function(){this.inherited(arguments);dojo.style(this.domNode,"visibility","hidden")},postCreate:function(){this.inherited(arguments);dojo.addClass(this.domNode,
"dojoxPortlet");dojo.removeClass(this.arrowNode,"dijitArrowNode");dojo.addClass(this.arrowNode,"dojoxPortletIcon dojoxArrowDown");dojo.addClass(this.titleBarNode,"dojoxPortletTitle");dojo.addClass(this.hideNode,"dojoxPortletContentOuter");dojo.addClass(this.domNode,"dojoxPortlet-"+(!this.dragRestriction?"movable":"nonmovable"));var a=this;if(this.resizeChildren){this.subscribe("/dnd/drop",function(){a._updateSize()});this.subscribe("/Portlet/sizechange",function(b){a.onSizeChange(b)});this.connect(window,
"onresize",function(){a._updateSize()});var c=dojo.hitch(this,function(b,c){var d=dijit.byId(b);if(d.selectChild){var e=this.subscribe(b+"-selectChild",function(b){for(var c=a.domNode.parentNode;c;){if(c==b.domNode){a.unsubscribe(e);a._updateSize();break}c=c.parentNode}}),f=dijit.byId(c);d&&f&&a._parents.push({parent:d,child:f})}}),d;this._parents=[];for(var b=this.domNode.parentNode;null!=b;b=b.parentNode){var e=b.getAttribute?b.getAttribute("widgetId"):null;e&&(c(e,d),d=e)}}this.connect(this.titleBarNode,
"onmousedown",function(a){return dojo.hasClass(a.target,"dojoxPortletIcon")?(dojo.stopEvent(a),!1):!0});this.connect(this._wipeOut,"onEnd",function(){a._publish()});this.connect(this._wipeIn,"onEnd",function(){a._publish()});if(this.closable)this.closeIcon=this._createIcon("dojoxCloseNode","dojoxCloseNodeHover",dojo.hitch(this,"onClose")),dojo.style(this.closeIcon,"display","")},startup:function(){if(!this._started){var a=this.getChildren();this._placeSettingsWidgets();dojo.forEach(a,function(a){try{!a.started&&
!a._started&&a.startup()}catch(d){}});this.inherited(arguments);dojo.style(this.domNode,"visibility","visible")}},_placeSettingsWidgets:function(){dojo.forEach(this.getChildren(),dojo.hitch(this,function(a){if(a.portletIconClass&&a.toggle&&!a.get("portlet"))this._createIcon(a.portletIconClass,a.portletIconHoverClass,dojo.hitch(a,"toggle")),dojo.place(a.domNode,this.containerNode,"before"),a.set("portlet",this),this._settingsWidget=a}))},_createIcon:function(a,c,d){var b=dojo.create("div",{"class":"dojoxPortletIcon "+
a,waiRole:"presentation"});dojo.place(b,this.arrowNode,"before");this.connect(b,"onclick",d);c&&(this.connect(b,"onmouseover",function(){dojo.addClass(b,c)}),this.connect(b,"onmouseout",function(){dojo.removeClass(b,c)}));return b},onClose:function(){dojo.style(this.domNode,"display","none")},onSizeChange:function(a){a!=this&&this._updateSize()},_updateSize:function(){if(this.open&&this._started&&this.resizeChildren)this._timer&&clearTimeout(this._timer),this._timer=setTimeout(dojo.hitch(this,function(){for(var a=
{w:dojo.style(this.domNode,"width"),h:dojo.style(this.domNode,"height")},c=0;c<this._parents.length;c++){var d=this._parents[c],b=d.parent.selectedChildWidget;if(b&&b!=d.child)return}if(!this._size||!(this._size.w==a.w&&this._size.h==a.h)){this._size=a;var e=["resize","layout"];this._timer=null;a=this.getChildren();dojo.forEach(a,function(a){for(var b=0;b<e.length;b++)if(dojo.isFunction(a[e[b]])){try{a[e[b]]()}catch(c){}break}});this.onUpdateSize()}}),100)},onUpdateSize:function(){},_publish:function(){dojo.publish("/Portlet/sizechange",
[this])},_onTitleClick:function(a){a.target==this.arrowNode&&this.inherited(arguments)},addChild:function(a){this._size=null;this.inherited(arguments);this._started&&(this._placeSettingsWidgets(),this._updateSize());this._started&&!a.started&&!a._started&&a.startup()},destroyDescendants:function(a){this.inherited(arguments);this._settingsWidget&&this._settingsWidget.destroyRecursive(a)},destroy:function(){this._timer&&clearTimeout(this._timer);this.inherited(arguments)},_setCss:function(){this.inherited(arguments);
dojo.style(this.arrowNode,"display",this.toggleable?"":"none")}})});