define({root:
({
	loadingInfo: "Loading...",
	emptyInfo: "No items to display",
	loadFailInfo: "Failed to load data!",
	loadMore: "Load More",
	loadMoreLoading: "Loading...",
	loadPrevious: "Load Previous",
	loadPreviousLoading: "Loading...",
	indirectSelectAll: "Press SPACE to select all.",
	indirectDeselectAll: "Press SPACE to deselect all.",
	treeExpanded: "Control + left arrow key to collapse this row.",
	treeCollapsed: "Control + right arrow key to expand this row."
}),
"ar": true,
"bg": true,
"ca": true,
"cs": true,
"da": true,
"de": true,
"el": true,
"es": true,
"fi": true,
"fr": true,
"he": true,
"hr": true,
"hu": true,
"it": true,
"ja": true,
"kk": true,
"ko": true,
"nb": true,
"nl": true,
"pl": true,
"pt": true,
"pt-pt": true,
"ro": true,
"ru": true,
"sk": true,
"sl": true,
"sv": true,
"th": true,
"tr": true,
"uk": true,
"zh": true,
"zh-tw": true
});
