define({
//Body
	loadingInfo: "Nalaganje ...",
	emptyInfo: "Ni postavk za prikaz",
	loadFailInfo: "Nalaganje podatkov ni uspelo!",
	loadMore: "Naloži več",
	loadMoreLoading: "Nalaganje ...",
	loadPrevious: "Naloži prejšnje",
	loadPreviousLoading: "Nalaganje ...",

//FilterBar
	"clearFilterDialogTitle": "Počisti filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Uporabljen ni noben filter.",
	"defineFilter": "Definiraj filter",
	"conditionEqual": "je enako",
	"conditionNotEqual": "ni enako",
	"conditionLess": "je manjše kot",
	"conditionLessEqual": "je manjše kot ali enako",
	"conditionGreater": "je večje kot",
	"conditionGreaterEqual": "je večje kot ali enako",
	"conditionContain": "vsebuje",
	"conditionIs": "je",
	"conditionStartWith": "se začne s",
	"conditionEndWith": "se konča s",
	"conditionNotContain": "ne vsebuje",
	"conditionIsNot": "ni",
	"conditionNotStartWith": "se ne začne s",
	"conditionNotEndWith": "se ne konča s",
	"conditionBefore": "pred",
	"conditionAfter": "za",
	"conditionRange": "obseg",
	"conditionIsEmpty": "je prazno",
	"all": "vse",
	"any": "kateri koli",
	"relationAll": "vsa pravila",
	"waiRelAll": "Ujema se z vsemi od naslednjih pravil:",
	"relationAny": "katerakoli pravila",
	"waiRelAny": "Ujema se s katerimkoli od naslednjih pravil:",
	"relationMsgFront": "Ujemanje",
	"relationMsgTail": "",
	"and": "in",
	"or": "ali",
	"addRuleButton": "Dodaj pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Odstrani pravilo",
	"waiRemoveRuleButtonTemplate": "Odstrani pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtra",
	"cancelButton": "Prekliči",
	"waiCancelButton": "Prekliči to pogovorno okno",
	"clearButton": "Počisti",
	"waiClearButton": "Počisti filter",
	"filterButton": "Filter",
	"waiFilterButton": "Predloži filter",
	"columnSelectLabel": "Stolpec",
	"waiColumnSelectTemplate": "Stolpec za pravilo ${0}",
	"conditionSelectLabel": "Pogoj",
	"waiConditionSelectTemplate": "Pogoj za pravilo ${0}",
	"valueBoxLabel": "Vrednost",
	"waiValueBoxTemplate": "Vnesite vrednost za filter pravila ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Stolpec",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Vrstica za filtriranje",
	"statusTipMsg": "Kliknite vrstico za filtriranje tukaj, da prefiltrirate vrednosti v ${0}.",
	"anycolumn": "katerikoli stolpec",
	"statusTipTitleNoFilter": "Vrstica za filtriranje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Ujemanje",
	"statusTipRelPost": "pravil.",
	"statusTipHeaderAll": "Ujemanje vseh pravil.",
	"statusTipHeaderAny": "Ujemanje vseh pravil.",
	"defaultItemsName": "postavke",
	"filterBarMsgHasFilterTemplate": "Prikazanih je ${0} od ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Uveljavljen ni noben filter.",
	"filterBarDefButton": "Definiraj filter",
	"waiFilterBarDefButton": "Filtriraj tabelo",
	"a11yFilterBarDefButton": "Filtriraj ...",
	"filterBarClearButton": "Počisti filter",
	"waiFilterBarClearButton": "Počisti filter",
	"closeFilterBarBtn": "Zapri vrstico za filtriranje",
	"clearFilterMsg": "S tem boste odstranili filter in prikazali se bodo vsi razpoložljivi zapisi.",
	"anyColumnOption": "Katerikoli stolpec",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "Vrednost True",
	"radioFalseLabel": "Vrednost False",
	"beginTimeRangeLabel": "Začetek vrednosti časovnega obsega",
	"endTimeRangeLabel": "Konec vrednosti časovnega obsega",
	"beginDateRangeLabel": "Začetek vrednosti datumskega obsega",
	"endDateRangeLabel": "Konec vrednosti datumskega obsega",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Enostavno razvrščanje",
	nestedSort: "Ugnezdeno razvrščanje",
	ascending: "Kliknite, če želite zagnati naraščajoče razvrščanje",
	descending: "Kliknite, če želite zagnati padajoče razvrščanje",
	sortingState: "${0} - ${1}",
	unsorted: "Ne razvrščaj tega stolpca",
	waiSingleSortLabel: "${0} - je razvrščen glede na ${1}. Izberi razvrščanje glede na ${2}",
	waiNestedSortLabel:"${0} - je ugnezden glede na ${1}. Izberi ugnezditev glede na ${2}",

//PaginationBar
	pagerWai: 'Pozivnik',

	pageIndex: '${0}',
	pageIndexTitle: 'Stran ${0}',

	firstPageTitle: 'Prva stran',
	prevPageTitle: 'Prejšnja stran',
	nextPageTitle: 'Naslednja stran',
	lastPageTitle: 'Zadnja stran',

	pageSize: '${0}',
	pageSizeTitle: '${0} postavk na stran',
	pageSizeAll: 'Vse',
	pageSizeAllTitle: 'Vse postavke',

	description: '${0}-${1} od ${2} postavk.',
	descriptionEmpty: 'Mreža je prazna.',

	summary: 'Skupaj: ${0}',
	summaryWithSelection: 'Skupaj: ${0} Izbranih: ${1}',

	gotoBtnTitle: 'Pojdi na specifično stran',

	gotoDialogTitle: 'Pojdi na stran',
	gotoDialogMainMsg: 'Navedite številko strani:',
	gotoDialogPageCount: '(${0} strani)',
	gotoDialogOKBtn: 'Pojdi',
	gotoDialogCancelBtn: 'Prekliči',
	// for drop down pagination bar
	pageLabel: 'Stran',
	pageSizeLabel: 'Vrstice',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Počisti filter',
	buildFilterMenuLabel: 'Ustvari filter&hellip;',
	apply: 'Uporabi filter',

//Sort
	helpMsg: '${0} - Kliknite za razvrščanje ali pa pritisnite ctrl in kliknite, da dodate v razvrščanje',
	singleHelpMsg: '${0} - Kliknite za razvrščanje',
	priorityOrder: 'razvrščanje prednosti ${0}',

//SummaryBar
	summaryTotal: 'Skupaj: ${0}',
	summarySelected: 'Izbranih: ${0}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Press SPACE to select all.",	//need translation
	indirectDeselectAll: "Press SPACE to deselect all.",	//need translation
	treeExpanded: "Control + left arrow key to collapse this row.",	//need translation
	treeCollapsed: "Control + right arrow key to expand this row."	//need translation
});
