define(
({
	"clearFilterDialogTitle": "Ryd filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Intet filter anvendt.",
	"defineFilter": "Definér filter",
	"conditionEqual": "lig med",
	"conditionNotEqual": "er forskellig fra",
	"conditionLess": "er mindre end",
	"conditionLessEqual": "mindre end eller lig med",
	"conditionGreater": "er større end",
	"conditionGreaterEqual": "større end eller lig med",
	"conditionContain": "indeholder",
	"conditionIs": "er",
	"conditionStartWith": "begynder med",
	"conditionEndWith": "slutter med",
	"conditionNotContain": "indeholder ikke",
	"conditionIsNot": "er ikke",
	"conditionNotStartWith": "begynder ikke med",
	"conditionNotEndWith": "slutter ikke med",
	"conditionBefore": "før",
	"conditionAfter": "efter",
	"conditionRange": "interval",
	"conditionIsEmpty": "er tom",
	"all": "alle",
	"any": "vilkårlige",
	"relationAll": "alle regler",
	"waiRelAll": "Matcher alle følgende regler:",
	"relationAny": "vilkårlige regler",
	"waiRelAny": "Matcher en eller flere af følgende regler:",
	"relationMsgFront": "Lig med",
	"relationMsgTail": "",
	"and": "og",
	"or": "eller",
	"addRuleButton": "Tilføj regel",
	"waiAddRuleButton": "Tilføj en ny regel",
	"removeRuleButton": "Fjern regel",
	"waiRemoveRuleButtonTemplate": "Fjern reglen ${0}",
	"addRuleButton": "Tilføj filterregel",
	"cancelButton": "Annullér",
	"waiCancelButton": "Annullér denne dialogboks",
	"clearButton": "Ryd",
	"waiClearButton": "Ryd filteret",
	"filterButton": "Filtrér",
	"waiFilterButton": "Send filteret",
	"columnSelectLabel": "Kolonne",
	"waiColumnSelectTemplate": "Kolonne for reglen ${0}",
	"conditionSelectLabel": "Betingelse",
	"waiConditionSelectTemplate": "Betingelse for reglen ${0}",
	"valueBoxLabel": "Værdi",
	"waiValueBoxTemplate": "Angiv værdi, der skal filtreres efter for reglen ${0}",
	"rangeTo": "til",
	"rangeTemplate": "fra ${0} til ${1}",
	"statusTipHeaderColumn": "Kolonne",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filterlinje",
	"statusTipMsg": "Klik på filterlinjen for at filtrere efter værdier i ${0}.",
	"anycolumn": "vilkårlig kolonne",
	"statusTipTitleNoFilter": "Filterlinje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Lig med",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Matcher alle regler.",
	"statusTipHeaderAny": "Matcher en hvilken som helst regel.",
	"defaultItemsName": "elementer",
	"filterBarMsgHasFilterTemplate": "${0} af ${1} ${2} vist.",
	"filterBarMsgNoFilterTemplate": "Intet filter anvendt",
	"filterBarDefButton": "Definér filter",
	"waiFilterBarDefButton": "Filtrér tabellen",
	"a11yFilterBarDefButton": "Filtrér...",
	"filterBarClearButton": "Ryd filter",
	"waiFilterBarClearButton": "Ryd filteret",
	"closeFilterBarBtn": "Luk filterlinje",
	"clearFilterMsg": "Denne funktion fjerner filteret og viser alle tilgængelige records.",
	"anyColumnOption": "Vilkårlig kolonne",
	"trueLabel": "Sand",
	"falseLabel": "Falsk",
	"radioTrueLabel": "Værdi sand",
	"radioFalseLabel": "Værdi falsk",
	"beginTimeRangeLabel": "Start på tidsintervalværdi",
	"endTimeRangeLabel": "Slut på tidsintervalværdi",
	"beginDateRangeLabel": "Start på datointervalværdi",
	"endDateRangeLabel": "Slut på datointervalværdi",
	"startsWithExpr": "${0}*"
})
);

