define({     
//Body
	loadingInfo: "Indlæser...",
	emptyInfo: "Der er ingen elementer at vise",
	loadFailInfo: "Kan ikke indlæse data.",
	loadMore: "Load More",
	loadMoreLoading: "Loading...",
	loadPrevious: "Load Previous",
	loadPreviousLoading: "Loading...",

//FilterBar
	"clearFilterDialogTitle": "Ryd filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Intet filter anvendt.",
	"defineFilter": "Definér filter",
	"conditionEqual": "lig med",
	"conditionNotEqual": "er ikke lig med",
	"conditionLess": "er mindre end",
	"conditionLessEqual": "mindre end eller lig med",
	"conditionGreater": "er større end",
	"conditionGreaterEqual": "større end eller lig med",
	"conditionContain": "indeholder",
	"conditionIs": "er",
	"conditionStartWith": "begynder med",
	"conditionEndWith": "slutter med",
	"conditionNotContain": "indeholder ikke",
	"conditionIsNot": "er ikke",
	"conditionNotStartWith": "begynder ikke med",
	"conditionNotEndWith": "slutter ikke med",
	"conditionBefore": "før",
	"conditionAfter": "efter",
	"conditionRange": "interval",
	"conditionIsEmpty": "er tom",
	"all": "alle",
	"any": "vilkårlige",
	"relationAll": "alle regler",
	"waiRelAll": "Matcher alle følgende regler:",
	"relationAny": "vilkårlige regler",
	"waiRelAny": "Matcher en eller flere af følgende regler:",
	"relationMsgFront": "Matcher",
	"relationMsgTail": "",
	"and": "og",
	"or": "eller",
	"addRuleButton": "Tilføj regel",
	"waiAddRuleButton": "Tilføj en ny regel",
	"removeRuleButton": "Fjern regel",
	"waiRemoveRuleButtonTemplate": "Fjern regel ${0}",
	"addRuleButton": "Tilføj filterregel",
	"cancelButton": "Annullér",
	"waiCancelButton": "Annullér denne dialogboks",
	"clearButton": "Ryd",
	"waiClearButton": "Ryd filteret",
	"filterButton": "Filter",
	"waiFilterButton": "Send filteret",
	"columnSelectLabel": "Kolonne:",
	"waiColumnSelectTemplate": "Kolonne for regel ${0}",
	"conditionSelectLabel": "Betingelse:",
	"waiConditionSelectTemplate": "Betingelse for regel ${0}",
	"valueBoxLabel": "Værdi:",
	"waiValueBoxTemplate": "Enter value to filter for rule ${0}",
	"rangeTo": "til",
	"rangeTemplate": "fra ${0} til ${1}",
	"statusTipHeaderColumn": "Kolonne",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filterlinje",
	"statusTipMsg": "Click the filter bar here to filter on values in ${0}.",
	"anycolumn": "vilkårlig kolonne",
	"statusTipTitleNoFilter": "Filterlinje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Matcher",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Matcher alle regler.",
	"statusTipHeaderAny": "Matcher en hvilken som helst regel.",
	"defaultItemsName": "elementer",
	"filterBarMsgHasFilterTemplate": "${0} of ${1} ${2} shown.",
	"filterBarMsgNoFilterTemplate": "No filter applied",
	"filterBarDefButton": "Define filter",
	"waiFilterBarDefButton": "Filter the table",
	"a11yFilterBarDefButton": "Filter...",
	"filterBarClearButton": "Clear filter",
	"waiFilterBarClearButton": "Ryd filteret",
	"closeFilterBarBtn": "Close filter bar",
	"clearFilterMsg": "This will remove the filter and show all available records.",
	"anyColumnOption": "Any Column",
	"trueLabel": "Sand",
	"falseLabel": "Falsk",
	"radioTrueLabel": "Value True",
	"radioFalseLabel": "Value False",
	"beginTimeRangeLabel": "Time Range Value Start",
	"endTimeRangeLabel": "Time Range Value End",
	"beginDateRangeLabel": "Date Range Value Start",
	"endDateRangeLabel": "Date Range Value End",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Single Sort",
	nestedSort: "Nested Sort",
	ascending: "Klik for at sortere stigende",
	descending: "Klik for at sortere faldende",
	sortingState: "${0} - ${1}",
	unsorted: "Do not sort this column",
	waiSingleSortLabel: "${0} - is sorted by ${1}. Choose to sort by ${2}",
	waiNestedSortLabel:"${0} - is nested sorted by ${1}. Choose to nested sort by ${2}",

//PaginationBar
	pagerWai: 'Pager',

	pageIndex: '${0}',
	pageIndexTitle: 'Page ${0}',

	firstPageTitle: 'First page',
	prevPageTitle: 'Previous page',
	nextPageTitle: 'Next page',
	lastPageTitle: 'Last page',

	pageSize: '${0}',
	pageSizeTitle: '${0} items per page',
	pageSizeAll: 'Alle',
	pageSizeAllTitle: 'All items',

	description: '${0} - ${1} of ${2} items.',
	descriptionEmpty: 'Grid is empty.',

	summary: 'Total: ${0}',
	summaryWithSelection: 'Total: ${0} Selected: ${1}',

	gotoBtnTitle: 'Go to a specific page',

	gotoDialogTitle: 'Go to Page',
	gotoDialogMainMsg: 'Specify the page number:',
	gotoDialogPageCount: '(${0} pages)',
	gotoDialogOKBtn: 'Go',
	gotoDialogCancelBtn: 'Annullér',
	// for drop down pagination bar
	pageLabel: 'Side',
	pageSizeLabel: 'Rows',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Ryd filter',
	buildFilterMenuLabel: 'Build Filter&hellip;',
	apply: 'Anvend filter',

//Sort
	helpMsg: '${0} - Klik for at sortere, eller hold Ctrl-tasten nede og klik for at tilføje til sortering',
	singleHelpMsg: '${0} - Klik for at sortere',
	priorityOrder: 'sorteringsrækkefølge ${0}',

//SummaryBar
	summaryTotal: 'Total: ${0}',
	summarySelected: 'Selected: ${0}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Tryk på mellemrumstasten for at markere alle.",	//need translation
	indirectDeselectAll: "Tryk på mellemrumstasten for at ophæve markeringen af alle.",	//need translation
	treeExpanded: "Ctrl + venstre piltast for at skjule denne række.",	//need translation
	treeCollapsed: "Ctrl + højre piltast for at udvide denne række."	//need translation
});

