//>>built
define("dojox/mobile/migrationAssist","dojo/_base/declare,dojo/_base/lang,dojo/_base/window,dojo/dom-class,dojo/dom-construct,dojo/dom-style,dojo/ready,dijit/_Container,dijit/_WidgetBase,./_ItemBase,./common,./FixedSplitterPane,./Heading,./iconUtils,./ListItem,./RoundRect,./SpinWheel,./SpinWheelSlot,./SwapView,./TabBarButton,./ToolBarButton,./View".split(","),function(d,g,c,q,h,l,r,b,m,e,f,s,t,u,i,v,n,w,x,o,p,y){var j;dojox.mobile.FlippableView=x;var k=new function(){this.dispatch=function(a,b){var c=
a.replace(/.*\./,"");this["check"+c]&&this["check"+c](b)};this.checkCarousel=function(){};this.checkFixedSplitter=function(a){if(!this._fixedSplitter_css_checked){this._fixedSplitter_css_checked=!0;var b=h.create("div",{className:"mblFixedSplitter"},c.body());0==l.get(b,"height")&&h.create("link",{href:"../themes/android/FixedSplitter.css",type:"text/css",rel:"stylesheet"},c.doc.getElementsByTagName("head")[0]);c.body().removeChild(b);setTimeout(function(){a.resize()},1E3)}};this.checkFixedSplitterPane=
function(){};this.checkFixedSplitter=function(a){if(!this._fixedSplitter_css_checked){this._fixedSplitter_css_checked=!0;var b=h.create("div",{className:"mblFixedSplitter"},c.body());0==l.get(b,"height")&&h.create("link",{href:"../themes/android/FixedSplitter.css",type:"text/css",rel:"stylesheet"},c.doc.getElementsByTagName("head")[0]);c.body().removeChild(b);setTimeout(function(){a.resize()},1E3)}};this.checkListItem=function(a){void 0!==a.sync||a.srcNodeRef&&a.srcNodeRef.getAttribute("sync");if(void 0!==
a.btnClass||a.srcNodeRef&&a.srcNodeRef.getAttribute("btnClass"))a.rightIcon=a.btnClass||a.srcNodeRef&&a.srcNodeRef.getAttribute("btnClass");if(void 0!==a.btnClass2||a.srcNodeRef&&a.srcNodeRef.getAttribute("btnClass2"))a.rightIcon2=a.btnClass2||a.srcNodeRef&&a.srcNodeRef.getAttribute("btnClass2")};this.checkSpinWheelSlot=function(a){if(a.labels&&a.labels[0]&&"["===a.labels[0].charAt(0))for(var b=0;b<a.labels.length;b++)a.labels[b]=a.labels[b].replace(/^\[*[\'\"]*/,""),a.labels[b]=a.labels[b].replace(/[\'\"]*\]*$/,
"")};this.checkSwapView=function(a){(a=a.srcNodeRef)&&(a.getAttribute("dojoType")||a.getAttribute("data-dojo-type"))};this.checkSwitch=function(){};this.checkTabBar=function(a){"segmentedControl"===(a.barType||a.srcNodeRef&&a.srcNodeRef.getAttribute("barType"))&&h.create("style",{innerHTML:".iphone_theme .mblTabBarSegmentedControl .mblTabBarButtonIconArea { display: none; }"},c.doc.getElementsByTagName("head")[0])};this.checkTabBarButton=function(a){if(0===(a["class"]||"").indexOf("mblDomButton"))if(a.icon=
a["class"],a["class"]="",a.srcNodeRef)a.srcNodeRef.className=""};this.checkToolBarButton=function(a){if(0===(a["class"]||"").indexOf("mblColor"))if(a.defaultColor=a["class"],a["class"]="",a.srcNodeRef)a.srcNodeRef.className="";if(0===(a["class"]||"").indexOf("mblDomButton"))if(a.icon=a["class"],a["class"]="",a.srcNodeRef)a.srcNodeRef.className=""}};m.prototype.postMixInProperties=function(){k.dispatch(this.declaredClass,this);dojo.forEach([s,t,v,n,o,p,y],function(a){this.declaredClass!==a.prototype.declaredClass&&
this instanceof a&&k.dispatch(a.prototype.declaredClass,this)},this)};extendSelectFunction=function(a){g.extend(a,{select:function(b){a.prototype.set.apply(this,["selected",!b])},deselect:function(){this.select(!0)}})};extendSelectFunction(p);extendSelectFunction(o);g.extend(i,{set:function(a,b){"btnClass"===a?a="rightIcon":"btnClass2"===a&&(a="rightIcon2");m.prototype.set.apply(this,[a,b])}});g.extend(n,{getValue:function(){return this.get("values")},setValue:function(a){return this.set("values",
a)}});g.extend(w,{getValue:function(){return this.get("value")},getKey:function(){return this.get("key")},setValue:function(a){return this.set("value",a)}});g.mixin(f,{createDomButton:function(){return u.createDomButton.apply(this,arguments)}});d=[];f=c.doc.styleSheets;for(b=0;b<f.length;b++)if(!f[b].href&&(i=f[b].cssRules||f[b].imports))for(e=0;e<i.length;e++)i[e].href&&d.push(i[e].href);e=c.doc.getElementsByTagName("link");for(b=0;b<e.length;b++)d.push(e[b].href);for(b=0;b<d.length;b++)-1!==d[b].indexOf("/iphone/")?
j="iphone":-1!==d[b].indexOf("/android/")?j="android":-1!==d[b].indexOf("/blackberry/")?j="blackberry":-1!==d[b].indexOf("/custom/")&&(j="custom"),q.add(c.doc.documentElement,j+"_theme"),d[b].match(/themes\/common\/(FixedSplitter.css)|themes\/common\/(SpinWheel.css)/);r(function(){dojo.hash&&(dojo.require?dojo.require("dojox.mobile.bookmarkable"):require(["dojox/mobile/bookmarkable"]))});return k});