//>>built
define("dojox/fx/text","dojo/_base/lang,./_base,dojo/_base/fx,dojo/fx,dojo/fx/easing,dojo/dom,dojo/dom-style,dojo/_base/html,dojo/_base/connect".split(","),function(s,v,n,u,m,l,o,t,r){var c=s.getObject("dojox.fx.text",!0);c._split=function(a){function f(b){var d=b.nextSibling;if("SPAN"==b.tagName&&1==b.childNodes.length&&3==b.firstChild.nodeType){var e=t.coords(b,!0);n++;o.set(b,{padding:0,margin:0,top:a.crop?"0px":e.t+"px",left:a.crop?"0px":e.l+"px",display:"inline"});b=a.pieceAnimation(b,e,i,n,
m);s.isArray(b)?h=h.concat(b):h[h.length]=b}else b.firstChild&&f(b.firstChild);d&&f(d)}var b=a.node=l.byId(a.node),d=b.style,j=o.getComputedStyle(b),i=t.coords(b,!0);a.duration=a.duration||1E3;a.words=a.words||!1;var g=a.text&&"string"==typeof a.text?a.text:b.innerHTML,e=d.height,c=d.width,h=[];o.set(b,{height:j.height,width:j.width});for(var d=/(<\/?\w+((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[^'">\s]+))?)+\s*|\s*)\/?>)/g,j=a.words?/(<\/?\w+((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[^'">\s]+))?)+\s*|\s*)\/?>)\s*|([^\s<]+\s*)/g:
/(<\/?\w+((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[^'">\s]+))?)+\s*|\s*)\/?>)\s*|([^\s<]\s*)/g,j="string"==typeof a.text?a.text.match(j):b.innerHTML.match(j),k="",m=0,n=0,p=0;p<j.length;p++){var q=j[p];q.match(d)?k+=q:(k+="<span>"+q+"</span>",m++)}b.innerHTML=k;f(b.firstChild);d=u.combine(h);r.connect(d,"onEnd",d,function(){b.innerHTML=g;o.set(b,{height:e,width:c})});a.onPlay&&r.connect(d,"onPlay",d,a.onPlay);a.onEnd&&r.connect(d,"onEnd",d,a.onEnd);return d};c.explode=function(a){a.node=l.byId(a.node);a.distance=
a.distance||1;a.duration=a.duration||1E3;a.random=a.random||0;if("undefined"==typeof a.fade)a.fade=!0;if("undefined"==typeof a.sync)a.sync=!0;a.random=Math.abs(a.random);a.pieceAnimation=function(f,b,d){var j=b.h,i=b.w,g=2*a.distance,e=a.duration,c=parseFloat(f.style.top),h=parseFloat(f.style.left),k=0,l=0,r=0;a.random&&(k=Math.random()*a.random+Math.max(1-a.random,0),g*=k,e*=k,k=a.unhide&&a.sync||!a.unhide&&!a.sync?a.duration-e:0,l=Math.random()-0.5,r=Math.random()-0.5);var j=(d.h-j)/2-(b.y-d.y),
b=(d.w-i)/2-(b.x-d.x),d=Math.sqrt(Math.pow(b,2)+Math.pow(j,2)),p=c-j*g+d*r,q=h-b*g+d*l,g=n.animateProperty({node:f,duration:e,delay:k,easing:a.easing||(a.unhide?m.sinOut:m.circOut),beforeBegin:a.unhide?function(){a.fade&&o.set(f,"opacity",0);f.style.position=a.crop?"relative":"absolute";f.style.top=p+"px";f.style.left=q+"px"}:function(){f.style.position=a.crop?"relative":"absolute"},properties:{top:a.unhide?{start:p,end:c}:{start:c,end:p},left:a.unhide?{start:q,end:h}:{start:h,end:q}}});return a.fade?
(e=n.animateProperty({node:f,duration:e,delay:k,easing:a.fadeEasing||m.quadOut,properties:{opacity:a.unhide?{start:0,end:1}:{end:0}}}),a.unhide?[e,g]:[g,e]):g};return c._split(a)};c.converge=function(a){a.unhide=!0;return c.explode(a)};c.disintegrate=function(a){a.node=l.byId(a.node);a.duration=a.duration||1500;a.distance=a.distance||1.5;a.random=a.random||0;if(!a.fade)a.fade=!0;var f=Math.abs(a.random);a.pieceAnimation=function(b,d,j,c,g){var e=a.interval||a.duration/(1.5*g),d=a.duration-g*e,l=Math.random()*
g*e,c=a.reverseOrder||0>a.distance?c*e:(g-c)*e,c=l*f+Math.max(1-f,0)*c,h={};if(a.unhide){if(h.top={start:parseFloat(b.style.top)-j.h*a.distance,end:parseFloat(b.style.top)},a.fade)h.opacity={start:0,end:1}}else if(h.top={end:parseFloat(b.style.top)+j.h*a.distance},a.fade)h.opacity={end:0};return n.animateProperty({node:b,duration:d,delay:c,easing:a.easing||(a.unhide?m.sinIn:m.circIn),properties:h,beforeBegin:a.unhide?function(){a.fade&&o.set(b,"opacity",0);b.style.position=a.crop?"relative":"absolute";
b.style.top=h.top.start+"px"}:function(){b.style.position=a.crop?"relative":"absolute"}})};return c._split(a)};c.build=function(a){a.unhide=!0;return c.disintegrate(a)};c.blockFadeOut=function(a){a.node=l.byId(a.node);a.duration=a.duration||1E3;a.random=a.random||0;var f=Math.abs(a.random);a.pieceAnimation=function(b,d,c,i,g){var e=a.interval||a.duration/(1.5*g),d=a.duration-g*e,c=Math.random()*g*e,i=a.reverseOrder?(g-i)*e:i*e,i=c*f+Math.max(1-f,0)*i;return n.animateProperty({node:b,duration:d,delay:i,
easing:a.easing||m.sinInOut,properties:{opacity:a.unhide?{start:0,end:1}:{end:0}},beforeBegin:a.unhide?function(){o.set(b,"opacity",0)}:void 0})};return c._split(a)};c.blockFadeIn=function(a){a.unhide=!0;return c.blockFadeOut(a)};c.backspace=function(a){a.node=l.byId(a.node);a.words=!1;a.duration=a.duration||2E3;a.random=a.random||0;var f=Math.abs(a.random),b=10;a.pieceAnimation=function(d,c,i,g,e){var c=a.interval||a.duration/(1.5*e),i="textContent"in d?d.textContent:d.innerText,l=i.match(/\s/g);
if("undefined"==typeof a.wordDelay)a.wordDelay=2*c;a.unhide||(b=(e-g-1)*c);var h,k;a.fixed?a.unhide&&(h=function(){o.set(d,"opacity",0)}):a.unhide?(h=function(){d.style.display="none"},k=function(){d.style.display="inline"}):k=function(){d.style.display="none"};g=n.animateProperty({node:d,duration:1,delay:b,easing:a.easing||m.sinInOut,properties:{opacity:a.unhide?{start:0,end:1}:{end:0}},beforeBegin:h,onEnd:k});a.unhide&&(e=Math.random()*i.length*c,h=e*f/2+Math.max(1-f/2,0)*a.wordDelay,b+=e*f+Math.max(1-
f,0)*c*i.length+h*(l&&i.lastIndexOf(l[l.length-1])==i.length-1));return g};return c._split(a)};c.type=function(a){a.unhide=!0;return c.backspace(a)};return c});