define({
//Body
	loadingInfo: "Ładowanie...",
	emptyInfo: "Brak pozycji do wyświetlenia",
	loadFailInfo: "Nie powiodła się próba załadowania danych.",
	loadMore: "Ładuj więcej",
	loadMoreLoading: "Ładowanie...",
	loadPrevious: "Ładuj poprzednie",
	loadPreviousLoading: "Ładowanie...",

//FilterBar
	"clearFilterDialogTitle": "Wyczyść filtr",
	"filterDefDialogTitle": "Filtr",
	"defaultRuleTitle": "Reguła ",
	"ruleTitleTemplate": "Reguła ${ruleNumber}",
	"noFilterApplied": "Nie zastosowano filtru. ",
	"defineFilter": "Zdefiniuj filtr",
	"conditionEqual": "równe",
	"conditionNotEqual": "różne od",
	"conditionLess": "mniejsze od",
	"conditionLessEqual": "mniejsze lub równe",
	"conditionGreater": "większe od",
	"conditionGreaterEqual": "większe lub równe",
	"conditionContain": "zawiera",
	"conditionIs": "jest",
	"conditionStartWith": "zaczyna się od",
	"conditionEndWith": "kończy się na",
	"conditionNotContain": "nie zawiera",
	"conditionIsNot": "nie jest",
	"conditionNotStartWith": "nie zaczyna się od",
	"conditionNotEndWith": "nie kończy się na",
	"conditionBefore": "przed",
	"conditionAfter": "po",
	"conditionRange": "zakres",
	"conditionIsEmpty": "jest pusty",
	"all": "wszystkie",
	"any": "dowolna",
	"relationAll": "wszystkie reguły",
	"waiRelAll": "Dopasuj wszystkie poniższe reguły:",
	"relationAny": "dowolna reguła",
	"waiRelAny": "Dopasuj dowolną z poniższych reguł:",
	"relationMsgFront": "Dopasuj",
	"relationMsgTail": "",
	"and": "i",
	"or": "lub",
	"addRuleButton": "Dodaj regułę",
	"waiAddRuleButton": "Dodaj nową regułę",
	"removeRuleButton": "Usuń regułę",
	"waiRemoveRuleButtonTemplate": "Usuń regułę ${0}",
	"addRuleButton": "Dodaj regułę filtru",
	"cancelButton": "Anuluj",
	"waiCancelButton": "Anuluj to okno dialogowe",
	"clearButton": "Wyczyść",
	"waiClearButton": "Wyczyść filtr",
	"filterButton": "Filtruj",
	"waiFilterButton": "Wprowadź ten filtr",
	"columnSelectLabel": "Kolumna",
	"waiColumnSelectTemplate": "Kolumna dla reguły ${0}",
	"conditionSelectLabel": "Warunek",
	"waiConditionSelectTemplate": "Warunek dla reguły ${0}",
	"valueBoxLabel": "Wartość",
	"waiValueBoxTemplate": "Wprowadź wartość, aby filtrować dla reguły ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Kolumna",
	"statusTipHeaderCondition": "Reguły",
	"statusTipTitle": "Pasek filtru",
	"statusTipMsg": "Kliknij pasek filtru tutaj, aby filtrować według wartości w ${0}.",
	"anycolumn": "dowolna kolumna",
	"statusTipTitleNoFilter": "Pasek filtru",
	"statusTipTitleHasFilter": "Filtr",
	"statusTipRelPre": "Dopasuj",
	"statusTipRelPost": "reguły.",
	"statusTipHeaderAll": "Dopasuj wszystkie role.",
	"statusTipHeaderAny": "Dopasuj dowolne role.",
	"defaultItemsName": "elementy",
	"filterBarMsgHasFilterTemplate": "Wyświetlane ${2}: ${0} z ${1}.",
	"filterBarMsgNoFilterTemplate": "Filtr wyłączony",
	"filterBarDefButton": "Zdefiniuj filtr",
	"waiFilterBarDefButton": "Filtruj tabelę",
	"a11yFilterBarDefButton": "Filtruj...",
	"filterBarClearButton": "Wyczyść filtr",
	"waiFilterBarClearButton": "Wyczyść filtr",
	"closeFilterBarBtn": "Zamknij pasek filtru",
	"clearFilterMsg": "Filtr zostanie usunięty i wyświetlone będą wszystkie dostępne rekordy.",
	"anyColumnOption": "Dowolna kolumna",
	"trueLabel": "Prawda",
	"falseLabel": "Fałsz",
	"radioTrueLabel": "Wartość Prawda",
	"radioFalseLabel": "Wartość Fałsz",
	"beginTimeRangeLabel": "Wartość początkowa zakresu czasu",
	"endTimeRangeLabel": "Wartość końcowa zakresu czasu",
	"beginDateRangeLabel": "Wartość początkowa zakresu dat",
	"endDateRangeLabel": "Wartość końcowa zakresu dat",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Pojedyncze sortowanie",
	nestedSort: "Zagnieżdżone sortowanie",
	ascending: "Kliknij, aby posortować rosnąco",
	descending: "Kliknij, aby posortować malejąco",
	sortingState: "${0} - ${1}",
	unsorted: "Nie sortuj tej kolumny",
	waiSingleSortLabel: "${0} - jest sortowane wg ${1}. Wybierz sortowanie wg ${2}",
	waiNestedSortLabel:"${0} - jest ponownie sortowane wg ${1}. Wybierz zagnieżdżone sortowanie wg ${2}",

//PaginationBar
	pagerWai: 'Program stronicujący',

	pageIndex: '${0}',
	pageIndexTitle: 'Strona ${0}',

	firstPageTitle: 'Pierwsza strona',
	prevPageTitle: 'Poprzednia strona',
	nextPageTitle: 'Następna strona',
	lastPageTitle: 'Ostatnia strona',

	pageSize: '${0}',
	pageSizeTitle: '${0} elementów na stronę',
	pageSizeAll: 'Wszystko',
	pageSizeAllTitle: 'Wszystkie elementy',

	description: '${0} - elementy ${1} z ${2}. ',
	descriptionEmpty: 'Siatka jest pusta.',

	summary: 'Łącznie: ${0}',
	summaryWithSelection: 'Łącznie: ${0} Wybranych: ${1}',

	gotoBtnTitle: 'Idź do określonej strony',

	gotoDialogTitle: 'Idź do strony',
	gotoDialogMainMsg: 'Podaj numer strony:',
	gotoDialogPageCount: '(${0} stron)',
	gotoDialogOKBtn: 'Idź',
	gotoDialogCancelBtn: 'Anuluj',
	// for drop down pagination bar
	pageLabel: 'Strona',
	pageSizeLabel: 'Wiersze',

//QuickFilter
	filterLabel: 'Filtr',
	clearButtonTitle: 'Wyczyść filtr',
	buildFilterMenuLabel: 'Utwórz filtr&hellip;',
	apply: 'Zastosuj filtr',

//Sort
	helpMsg: '${0} - Kliknij, aby posortować, albo kliknij, przytrzymując klawisz Ctrl, aby dodać do sortowania',
	singleHelpMsg: '${0} - Kliknij, aby posortować',
	priorityOrder: 'priorytet sortowania: ${0}',

//SummaryBar
	summaryTotal: 'Łącznie: ${0}',
	summarySelected: 'Wybranych: ${0}',
	summaryRange: 'Range: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Press SPACE to select all.",	//need translation
	indirectDeselectAll: "Press SPACE to deselect all.",	//need translation
	treeExpanded: "Control + left arrow key to collapse this row.",	//need translation
	treeCollapsed: "Control + right arrow key to expand this row."	//need translation
});
