define({     
//Body
	loadingInfo: "Laster inn...",
	emptyInfo: "Ingen elementer å vise",
	loadFailInfo: "Kunne ikke laste inn data!",
	loadMore: "Last inn mer",
	loadMoreLoading: "Laster inn...",
	loadPrevious: "Last inn forrige",
	loadPreviousLoading: "Laster inn...",

//FilterBar
	"clearFilterDialogTitle": "Tøm filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Ikke brukt filter.",
	"defineFilter": "Definer filter",
	"conditionEqual": "er lik",
	"conditionNotEqual": "er ikke lik",
	"conditionLess": "er mindre enn",
	"conditionLessEqual": "mindre enn eller lik",
	"conditionGreater": "er større enn",
	"conditionGreaterEqual": "større enn eller lik",
	"conditionContain": "inneholder",
	"conditionIs": "er",
	"conditionStartWith": "begynner med",
	"conditionEndWith": "slutter med",
	"conditionNotContain": "inneholder ikke",
	"conditionIsNot": "er ikke",
	"conditionNotStartWith": "begynner ikke med",
	"conditionNotEndWith": "slutter ikke med",
	"conditionBefore": "før",
	"conditionAfter": "etter",
	"conditionRange": "område",
	"conditionIsEmpty": "er tom",
	"all": "alle",
	"any": "minst en",
	"relationAll": "alle regler",
	"waiRelAll": "Samsvar med alle følgende regler:",
	"relationAny": "minst en regel",
	"waiRelAny": "Samsvar med minst en av følgende regler:",
	"relationMsgFront": "Samsvar med",
	"relationMsgTail": "",
	"and": "og",
	"or": "eller",
	"addRuleButton": "Legg til regel",
	"waiAddRuleButton": "Legg til en ny regel",
	"removeRuleButton": "Fjern regel",
	"waiRemoveRuleButtonTemplate": "Fjern regel ${0}",
	"addRuleButton": "Legg til filterregel",
	"cancelButton": "Avbryt",
	"waiCancelButton": "Avbryt denne dialogboksen",
	"clearButton": "Tøm",
	"waiClearButton": "Tøm filteret",
	"filterButton": "Filtrer",
	"waiFilterButton": "Send filteret",
	"columnSelectLabel": "Kolonne:",
	"waiColumnSelectTemplate": "Kolonne for regel ${0}",
	"conditionSelectLabel": "Betingelse:",
	"waiConditionSelectTemplate": "Betingelse for regel ${0}",
	"valueBoxLabel": "Verdi:",
	"waiValueBoxTemplate": "Oppgi verdi som skal filtreres for regel ${0}",
	"rangeTo": "til",
	"rangeTemplate": "fra ${0} til ${1}",
	"statusTipHeaderColumn": "Kolonne",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filterlinje",
	"statusTipMsg": "Klikk på filterlinjen her for å filtrere på verdier i ${0}.",
	"anycolumn": "enhver kolonne",
	"statusTipTitleNoFilter": "Filterlinje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Samsvar med",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Samsvar med alle regler.",
	"statusTipHeaderAny": "Samsvar med minst en regel.",
	"defaultItemsName": "elementer",
	"filterBarMsgHasFilterTemplate": "${0} av ${1} ${2} vist.",
	"filterBarMsgNoFilterTemplate": "Det er ikke brukt filter",
	"filterBarDefButton": "Definer filter",
	"waiFilterBarDefButton": "Filtrer tabellen",
	"a11yFilterBarDefButton": "Filtrer...",
	"filterBarClearButton": "Tøm filter",
	"waiFilterBarClearButton": "Tøm filteret",
	"closeFilterBarBtn": "Lukk filterlinje",
	"clearFilterMsg": "Dette fjerner filteret og viser alle tilgjengelige poster.",
	"anyColumnOption": "Minst en kolonne",
	"trueLabel": "Sann",
	"falseLabel": "Usann",
	"radioTrueLabel": "Verdi sann",
	"radioFalseLabel": "Verdi usann",
	"beginTimeRangeLabel": "Startverdi for tidsrom",
	"endTimeRangeLabel": "Sluttverdi for tidsrom",
	"beginDateRangeLabel": "Startverdi for datoområde",
	"endDateRangeLabel": "Sluttverdi for datoområde",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Enkel sortering",
	nestedSort: "Nestet sortering",
	ascending: "Klikk for å sortere stigende",
	descending: "Klikk for å sortere synkende",
	sortingState: "${0} - ${1}",
	unsorted: "Ikke sorter denne kolonnen",
	waiSingleSortLabel: "${0} - er sortert etter ${1}. Velg å sortere etter ${2}",
	waiNestedSortLabel:"${0} - er sortert med nestet sortering etter ${1}. Velg å sortere med nestet sortering etter ${2}",

//PaginationBar
	pagerWai: 'Sidevelger',

	pageIndex: '${0}',
	pageIndexTitle: 'Side ${0}',

	firstPageTitle: 'Første side',
	prevPageTitle: 'Forrige side',
	nextPageTitle: 'Neste side',
	lastPageTitle: 'Siste side',

	pageSize: '${0}',
	pageSizeTitle: '${0} elementer per side',
	pageSizeAll: 'Alle',
	pageSizeAllTitle: 'Alle elementer',

	description: '${0} - ${1} av ${2} elementer.',
	descriptionEmpty: 'Rutenettet er tomt.',

	summary: 'Totalt: ${0}',
	summaryWithSelection: 'Totalt: ${0} Valgt: ${1}',

	gotoBtnTitle: 'Gå til en bestemt side',

	gotoDialogTitle: 'Gå til side',
	gotoDialogMainMsg: 'Angi sidetall:',
	gotoDialogPageCount: ' (${0} sider)',
	gotoDialogOKBtn: 'OK',
	gotoDialogCancelBtn: 'Avbryt',
	// for drop down pagination bar
	pageLabel: 'Side',
	pageSizeLabel: 'Rader',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Tøm filter',
	buildFilterMenuLabel: 'Bygg filter&hellip;',
	apply: 'Bruk filter',

//Sort
	helpMsg: '${0} - Klikk for å sortere eller Control+klikk for å legge til i sortering',
	singleHelpMsg: '${0} - Klikk for å sortere',
	priorityOrder: 'sorteringsrekkefølge ${0}',

//SummaryBar
	summaryTotal: 'Totalt: ${0}',
	summarySelected: 'Valgt: ${0}',
	summaryRange: 'Område: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Trykk på mellomromstasten for å velge alle.",	//need translation
	indirectDeselectAll: "Trykk på mellomromstasten for å oppheve valg av alle.",	//need translation
	treeExpanded: "Control+venstrepil for å komprimere denne raden.",	//need translation
	treeCollapsed: "Control+høyrepil for å utvide denne raden."	//need translation
});

